; NOTE: Assertions have been autogenerated by utils/update_analyze_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes="print<cost-model>" 2>&1 -disable-output -cost-kind=all -mtriple=aarch64 < %s -intrinsic-cost-strategy=pattern-match-cost | FileCheck %s -check-prefix=CHECK-BASE
; RUN: opt -passes="print<cost-model>" 2>&1 -disable-output -cost-kind=all -mtriple=aarch64 -mattr=+dotprod < %s -intrinsic-cost-strategy=pattern-match-cost | FileCheck %s -check-prefix=CHECK-DOTPROD

define void @partial_reduce_dot() {
 ; sdot
; CHECK-BASE-LABEL: 'partial_reduce_dot'
; CHECK-BASE-NEXT:  Cost Model: Found costs of Invalid for: pattern rooted at %1 = call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v16i32(<4 x i32> poison, <16 x i32> %mul.0)
; CHECK-BASE-NEXT:  Cost Model: Found costs of Invalid for: pattern rooted at %2 = call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v16i32(<4 x i32> poison, <16 x i32> %mul.1)
;
; CHECK-DOTPROD-LABEL: 'partial_reduce_dot'
; CHECK-DOTPROD-NEXT:  Cost Model: Found costs of RThru:1 CodeSize:Invalid Lat:Invalid SizeLat:Invalid for: pattern rooted at %1 = call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v16i32(<4 x i32> poison, <16 x i32> %mul.0)
; CHECK-DOTPROD-NEXT:  Cost Model: Found costs of RThru:1 CodeSize:Invalid Lat:Invalid SizeLat:Invalid for: pattern rooted at %2 = call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v16i32(<4 x i32> poison, <16 x i32> %mul.1)
;
 %sextA = sext <16 x i8> poison to <16 x i32>
 %sextB = sext <16 x i8> poison to <16 x i32>
 %mul.0 = mul nsw <16 x i32> %sextA, %sextB
 call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v16i32(<4 x i32> poison, <16 x i32> %mul.0)

 ; udot
 %zextA = zext <16 x i8> poison to <16 x i32>
 %zextB = zext <16 x i8> poison to <16 x i32>
 %mul.1 = mul nsw <16 x i32> %zextA, %zextB
 call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v16i32(<4 x i32> poison, <16 x i32> %mul.1)

 ret void
}
