; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -aarch64-predicate-as-counter-loop-rewrites -instcombine -mtriple=aarch64-linux-gnu < %s | FileCheck %s

target triple = "aarch64-unknown-linux-gnu"

declare <vscale x 8 x i1> @llvm.get.active.lane.mask.nxv8i1.i64(i64, i64)
declare <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64, i64)
declare <vscale x 8 x i64> @llvm.masked.load.nxv8i64(ptr, i32 immarg, <vscale x 8 x i1>, <vscale x 8 x i64>)
declare void @llvm.masked.store.nxv8i64(<vscale x 8 x i64>, ptr, i32 immarg, <vscale x 8 x i1>)
declare <vscale x 8 x i32> @llvm.masked.load.nxv8i32(ptr, i32 immarg, <vscale x 8 x i1>, <vscale x 8 x i32>)
declare void @llvm.masked.store.nxv8i32(<vscale x 8 x i32>, ptr, i32 immarg, <vscale x 8 x i1>)
declare <vscale x 4 x i64> @llvm.masked.load.nxv4i64(ptr, i32 immarg, <vscale x 4 x i1>, <vscale x 4 x i64>)
declare void @llvm.masked.store.nxv4i64(<vscale x 4 x i64>, ptr, i32 immarg, <vscale x 4 x i1>)
declare i64 @llvm.vscale.i64()
declare void @use_nxv8i64(<vscale x 8 x i64>)
declare void @use_nxv8i32(<vscale x 8 x i32>)

define void @simple_add_multi_vec_vl4(ptr %x, i64 %n) #0 {
; CHECK-LABEL: define void @simple_add_multi_vec_vl4(
; CHECK-SAME: ptr [[X:%.*]], i64 [[N:%.*]]) #[[ATTR1:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[PREHEADER:.*]]
; CHECK:       [[PREHEADER]]:
; CHECK-NEXT:    [[PAC_MASK:%.*]] = call target("aarch64.svcount") @llvm.aarch64.sve.whilelt.c64(i64 0, i64 [[N]], i32 4)
; CHECK-NEXT:    [[VSCALE:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[STEP:%.*]] = shl i64 [[VSCALE]], 3
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[BASE:%.*]] = phi i64 [ 0, %[[PREHEADER]] ], [ [[NEXT_BASE:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[UPDATE_MASK_PN:%.*]] = phi target("aarch64.svcount") [ [[PAC_MASK]], %[[PREHEADER]] ], [ [[PAC_MASK1:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[PTR0:%.*]] = getelementptr [8 x i8], ptr [[X]], i64 [[BASE]]
; CHECK-NEXT:    [[PAC_LD1:%.*]] = call { <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64> } @llvm.aarch64.sve.ld1.pn.x4.nxv2i64.p0(target("aarch64.svcount") [[UPDATE_MASK_PN]], ptr align 8 [[PTR0]])
; CHECK-NEXT:    [[PAC_DATA5:%.*]] = extractvalue { <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64> } [[PAC_LD1]], 0
; CHECK-NEXT:    [[PAC_VEC:%.*]] = call <vscale x 8 x i64> @llvm.vector.insert.nxv8i64.nxv2i64(<vscale x 8 x i64> poison, <vscale x 2 x i64> [[PAC_DATA5]], i64 0)
; CHECK-NEXT:    [[PAC_DATA6:%.*]] = extractvalue { <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64> } [[PAC_LD1]], 1
; CHECK-NEXT:    [[PAC_VEC7:%.*]] = call <vscale x 8 x i64> @llvm.vector.insert.nxv8i64.nxv2i64(<vscale x 8 x i64> [[PAC_VEC]], <vscale x 2 x i64> [[PAC_DATA6]], i64 2)
; CHECK-NEXT:    [[PAC_DATA8:%.*]] = extractvalue { <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64> } [[PAC_LD1]], 2
; CHECK-NEXT:    [[PAC_VEC9:%.*]] = call <vscale x 8 x i64> @llvm.vector.insert.nxv8i64.nxv2i64(<vscale x 8 x i64> [[PAC_VEC7]], <vscale x 2 x i64> [[PAC_DATA8]], i64 4)
; CHECK-NEXT:    [[PAC_DATA10:%.*]] = extractvalue { <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64> } [[PAC_LD1]], 3
; CHECK-NEXT:    [[V:%.*]] = call <vscale x 8 x i64> @llvm.vector.insert.nxv8i64.nxv2i64(<vscale x 8 x i64> [[PAC_VEC9]], <vscale x 2 x i64> [[PAC_DATA10]], i64 6)
; CHECK-NEXT:    [[ADD:%.*]] = add <vscale x 8 x i64> [[V]], splat (i64 1)
; CHECK-NEXT:    [[PAC_DATA:%.*]] = call <vscale x 2 x i64> @llvm.vector.extract.nxv2i64.nxv8i64(<vscale x 8 x i64> [[ADD]], i64 0)
; CHECK-NEXT:    [[PAC_DATA2:%.*]] = call <vscale x 2 x i64> @llvm.vector.extract.nxv2i64.nxv8i64(<vscale x 8 x i64> [[ADD]], i64 2)
; CHECK-NEXT:    [[PAC_DATA3:%.*]] = call <vscale x 2 x i64> @llvm.vector.extract.nxv2i64.nxv8i64(<vscale x 8 x i64> [[ADD]], i64 4)
; CHECK-NEXT:    [[PAC_DATA4:%.*]] = call <vscale x 2 x i64> @llvm.vector.extract.nxv2i64.nxv8i64(<vscale x 8 x i64> [[ADD]], i64 6)
; CHECK-NEXT:    call void @llvm.aarch64.sve.st1.pn.x4.nxv2i64.p0(<vscale x 2 x i64> [[PAC_DATA]], <vscale x 2 x i64> [[PAC_DATA2]], <vscale x 2 x i64> [[PAC_DATA3]], <vscale x 2 x i64> [[PAC_DATA4]], target("aarch64.svcount") [[UPDATE_MASK_PN]], ptr align 8 [[PTR0]])
; CHECK-NEXT:    [[NEXT_BASE]] = add i64 [[BASE]], [[STEP]]
; CHECK-NEXT:    [[PAC_MASK1]] = call target("aarch64.svcount") @llvm.aarch64.sve.whilelt.c64(i64 [[NEXT_BASE]], i64 [[N]], i32 4)
; CHECK-NEXT:    [[PAC_PEXT17:%.*]] = call <vscale x 2 x i1> @llvm.aarch64.sve.pext.nxv2i1(target("aarch64.svcount") [[PAC_MASK1]], i32 3)
; CHECK-NEXT:    [[PAC_MASK18:%.*]] = call <vscale x 8 x i1> @llvm.vector.insert.nxv8i1.nxv2i1(<vscale x 8 x i1> poison, <vscale x 2 x i1> [[PAC_PEXT17]], i64 6)
; CHECK-NEXT:    [[PAC_PEXT19:%.*]] = call <vscale x 2 x i1> @llvm.aarch64.sve.pext.nxv2i1(target("aarch64.svcount") [[PAC_MASK1]], i32 2)
; CHECK-NEXT:    [[PAC_MASK20:%.*]] = call <vscale x 8 x i1> @llvm.vector.insert.nxv8i1.nxv2i1(<vscale x 8 x i1> [[PAC_MASK18]], <vscale x 2 x i1> [[PAC_PEXT19]], i64 4)
; CHECK-NEXT:    [[PAC_PEXT21:%.*]] = call <vscale x 2 x i1> @llvm.aarch64.sve.pext.nxv2i1(target("aarch64.svcount") [[PAC_MASK1]], i32 1)
; CHECK-NEXT:    [[PAC_MASK22:%.*]] = call <vscale x 8 x i1> @llvm.vector.insert.nxv8i1.nxv2i1(<vscale x 8 x i1> [[PAC_MASK20]], <vscale x 2 x i1> [[PAC_PEXT21]], i64 2)
; CHECK-NEXT:    [[PAC_PEXT23:%.*]] = call <vscale x 2 x i1> @llvm.aarch64.sve.pext.nxv2i1(target("aarch64.svcount") [[PAC_MASK1]], i32 0)
; CHECK-NEXT:    [[PAC_MASK24:%.*]] = call <vscale x 8 x i1> @llvm.vector.insert.nxv8i1.nxv2i1(<vscale x 8 x i1> [[PAC_MASK22]], <vscale x 2 x i1> [[PAC_PEXT23]], i64 0)
; CHECK-NEXT:    [[MORE:%.*]] = extractelement <vscale x 8 x i1> [[PAC_MASK24]], i64 0
; CHECK-NEXT:    br i1 [[MORE]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %start.mask = call <vscale x 8 x i1> @llvm.get.active.lane.mask.nxv8i1.i64(i64 0, i64 %n)
  br label %preheader

preheader:
  %vscale = call i64 @llvm.vscale.i64()
  %step = shl i64 %vscale, 3
  br label %loop

loop:
  %base = phi i64 [ 0, %preheader ], [ %next.base, %loop ]
  %update.mask = phi <vscale x 8 x i1> [ %start.mask, %preheader ], [ %new.mask, %loop ]
  %ptr0 = getelementptr i64, ptr %x, i64 %base
  %v = call <vscale x 8 x i64> @llvm.masked.load.nxv8i64(ptr %ptr0, i32 8, <vscale x 8 x i1> %update.mask, <vscale x 8 x i64> poison)
  %add = add <vscale x 8 x i64> %v, splat (i64 1)
  call void @llvm.masked.store.nxv8i64(<vscale x 8 x i64> %add, ptr %ptr0, i32 8, <vscale x 8 x i1> %update.mask)
  %next.base = add i64 %base, %step
  %new.mask = call <vscale x 8 x i1> @llvm.get.active.lane.mask.nxv8i1.i64(i64 %next.base, i64 %n)
  %more = extractelement <vscale x 8 x i1> %new.mask, i64 0
  br i1 %more, label %loop, label %exit

exit:
  ret void
}

define void @simple_add_multi_vec_vl2(ptr %x, i64 %n) #0 {
; CHECK-LABEL: define void @simple_add_multi_vec_vl2(
; CHECK-SAME: ptr [[X:%.*]], i64 [[N:%.*]]) #[[ATTR1]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[PREHEADER:.*]]
; CHECK:       [[PREHEADER]]:
; CHECK-NEXT:    [[PAC_MASK:%.*]] = call target("aarch64.svcount") @llvm.aarch64.sve.whilelt.c64(i64 0, i64 [[N]], i32 2)
; CHECK-NEXT:    [[VSCALE:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[STEP:%.*]] = shl i64 [[VSCALE]], 3
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[BASE:%.*]] = phi i64 [ 0, %[[PREHEADER]] ], [ [[NEXT_BASE:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[UPDATE_MASK_PN:%.*]] = phi target("aarch64.svcount") [ [[PAC_MASK]], %[[PREHEADER]] ], [ [[PAC_MASK1:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[PTR0:%.*]] = getelementptr [8 x i8], ptr [[X]], i64 [[BASE]]
; CHECK-NEXT:    [[PAC_LD1:%.*]] = call { <vscale x 2 x i64>, <vscale x 2 x i64> } @llvm.aarch64.sve.ld1.pn.x2.nxv2i64.p0(target("aarch64.svcount") [[UPDATE_MASK_PN]], ptr align 8 [[PTR0]])
; CHECK-NEXT:    [[PAC_DATA3:%.*]] = extractvalue { <vscale x 2 x i64>, <vscale x 2 x i64> } [[PAC_LD1]], 0
; CHECK-NEXT:    [[PAC_VEC:%.*]] = call <vscale x 4 x i64> @llvm.vector.insert.nxv4i64.nxv2i64(<vscale x 4 x i64> poison, <vscale x 2 x i64> [[PAC_DATA3]], i64 0)
; CHECK-NEXT:    [[PAC_DATA4:%.*]] = extractvalue { <vscale x 2 x i64>, <vscale x 2 x i64> } [[PAC_LD1]], 1
; CHECK-NEXT:    [[V:%.*]] = call <vscale x 4 x i64> @llvm.vector.insert.nxv4i64.nxv2i64(<vscale x 4 x i64> [[PAC_VEC]], <vscale x 2 x i64> [[PAC_DATA4]], i64 2)
; CHECK-NEXT:    [[ADD:%.*]] = add <vscale x 4 x i64> [[V]], splat (i64 1)
; CHECK-NEXT:    [[PAC_DATA:%.*]] = call <vscale x 2 x i64> @llvm.vector.extract.nxv2i64.nxv4i64(<vscale x 4 x i64> [[ADD]], i64 0)
; CHECK-NEXT:    [[PAC_DATA2:%.*]] = call <vscale x 2 x i64> @llvm.vector.extract.nxv2i64.nxv4i64(<vscale x 4 x i64> [[ADD]], i64 2)
; CHECK-NEXT:    call void @llvm.aarch64.sve.st1.pn.x2.nxv2i64.p0(<vscale x 2 x i64> [[PAC_DATA]], <vscale x 2 x i64> [[PAC_DATA2]], target("aarch64.svcount") [[UPDATE_MASK_PN]], ptr align 8 [[PTR0]])
; CHECK-NEXT:    [[NEXT_BASE]] = add i64 [[BASE]], [[STEP]]
; CHECK-NEXT:    [[PAC_MASK1]] = call target("aarch64.svcount") @llvm.aarch64.sve.whilelt.c64(i64 [[NEXT_BASE]], i64 [[N]], i32 2)
; CHECK-NEXT:    [[PAC_PEXT9:%.*]] = call <vscale x 2 x i1> @llvm.aarch64.sve.pext.nxv2i1(target("aarch64.svcount") [[PAC_MASK1]], i32 1)
; CHECK-NEXT:    [[PAC_MASK10:%.*]] = call <vscale x 4 x i1> @llvm.vector.insert.nxv4i1.nxv2i1(<vscale x 4 x i1> poison, <vscale x 2 x i1> [[PAC_PEXT9]], i64 2)
; CHECK-NEXT:    [[PAC_PEXT11:%.*]] = call <vscale x 2 x i1> @llvm.aarch64.sve.pext.nxv2i1(target("aarch64.svcount") [[PAC_MASK1]], i32 0)
; CHECK-NEXT:    [[PAC_MASK12:%.*]] = call <vscale x 4 x i1> @llvm.vector.insert.nxv4i1.nxv2i1(<vscale x 4 x i1> [[PAC_MASK10]], <vscale x 2 x i1> [[PAC_PEXT11]], i64 0)
; CHECK-NEXT:    [[MORE:%.*]] = extractelement <vscale x 4 x i1> [[PAC_MASK12]], i64 0
; CHECK-NEXT:    br i1 [[MORE]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %start.mask = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 0, i64 %n)
  br label %preheader

preheader:
  %vscale = call i64 @llvm.vscale.i64()
  %step = shl i64 %vscale, 3
  br label %loop

loop:
  %base = phi i64 [ 0, %preheader ], [ %next.base, %loop ]
  %update.mask = phi <vscale x 4 x i1> [ %start.mask, %preheader ], [ %new.mask, %loop ]
  %ptr0 = getelementptr i64, ptr %x, i64 %base
  %v = call <vscale x 4 x i64> @llvm.masked.load.nxv4i64(ptr %ptr0, i32 8, <vscale x 4 x i1> %update.mask, <vscale x 4 x i64> poison)
  %add = add <vscale x 4 x i64> %v, splat (i64 1)
  call void @llvm.masked.store.nxv4i64(<vscale x 4 x i64> %add, ptr %ptr0, i32 8, <vscale x 4 x i1> %update.mask)
  %next.base = add i64 %base, %step
  %new.mask = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 %next.base, i64 %n)
  %more = extractelement <vscale x 4 x i1> %new.mask, i64 0
  br i1 %more, label %loop, label %exit

exit:
  ret void
}

define void @simple_add_multi_vec_i32(ptr %x, i64 %n) #0 {
; CHECK-LABEL: define void @simple_add_multi_vec_i32(
; CHECK-SAME: ptr [[X:%.*]], i64 [[N:%.*]]) #[[ATTR1]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[PREHEADER:.*]]
; CHECK:       [[PREHEADER]]:
; CHECK-NEXT:    [[PAC_START:%.*]] = call target("aarch64.svcount") @llvm.aarch64.sve.whilelt.c32(i64 0, i64 [[N]], i32 2)
; CHECK-NEXT:    [[VSCALE:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[STEP:%.*]] = shl i64 [[VSCALE]], 3
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[BASE:%.*]] = phi i64 [ 0, %[[PREHEADER]] ], [ [[NEXT_BASE:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[UPDATE_MASK_PN:%.*]] = phi target("aarch64.svcount") [ [[PAC_START]], %[[PREHEADER]] ], [ [[PAC_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[PTR0:%.*]] = getelementptr [4 x i8], ptr [[X]], i64 [[BASE]]
; CHECK-NEXT:    [[PAC_LD1:%.*]] = call { <vscale x 4 x i32>, <vscale x 4 x i32> } @llvm.aarch64.sve.ld1.pn.x2.nxv4i32.p0(target("aarch64.svcount") [[UPDATE_MASK_PN]], ptr align 4 [[PTR0]])
; CHECK-NEXT:    [[PAC_DATA3:%.*]] = extractvalue { <vscale x 4 x i32>, <vscale x 4 x i32> } [[PAC_LD1]], 0
; CHECK-NEXT:    [[PAC_VEC:%.*]] = call <vscale x 8 x i32> @llvm.vector.insert.nxv8i32.nxv4i32(<vscale x 8 x i32> poison, <vscale x 4 x i32> [[PAC_DATA3]], i64 0)
; CHECK-NEXT:    [[PAC_DATA4:%.*]] = extractvalue { <vscale x 4 x i32>, <vscale x 4 x i32> } [[PAC_LD1]], 1
; CHECK-NEXT:    [[V:%.*]] = call <vscale x 8 x i32> @llvm.vector.insert.nxv8i32.nxv4i32(<vscale x 8 x i32> [[PAC_VEC]], <vscale x 4 x i32> [[PAC_DATA4]], i64 4)
; CHECK-NEXT:    [[ADD:%.*]] = add <vscale x 8 x i32> [[V]], splat (i32 1)
; CHECK-NEXT:    [[PAC_DATA:%.*]] = call <vscale x 4 x i32> @llvm.vector.extract.nxv4i32.nxv8i32(<vscale x 8 x i32> [[ADD]], i64 0)
; CHECK-NEXT:    [[PAC_DATA2:%.*]] = call <vscale x 4 x i32> @llvm.vector.extract.nxv4i32.nxv8i32(<vscale x 8 x i32> [[ADD]], i64 4)
; CHECK-NEXT:    call void @llvm.aarch64.sve.st1.pn.x2.nxv4i32.p0(<vscale x 4 x i32> [[PAC_DATA]], <vscale x 4 x i32> [[PAC_DATA2]], target("aarch64.svcount") [[UPDATE_MASK_PN]], ptr align 4 [[PTR0]])
; CHECK-NEXT:    [[NEXT_BASE]] = add i64 [[BASE]], [[STEP]]
; CHECK-NEXT:    [[PAC_NEXT]] = call target("aarch64.svcount") @llvm.aarch64.sve.whilelt.c32(i64 [[NEXT_BASE]], i64 [[N]], i32 2)
; CHECK-NEXT:    [[NEXT_PEXT1:%.*]] = call <vscale x 4 x i1> @llvm.aarch64.sve.pext.nxv4i1(target("aarch64.svcount") [[PAC_NEXT]], i32 1)
; CHECK-NEXT:    [[NEXT_MASK1:%.*]] = call <vscale x 8 x i1> @llvm.vector.insert.nxv8i1.nxv4i1(<vscale x 8 x i1> poison, <vscale x 4 x i1> [[NEXT_PEXT1]], i64 4)
; CHECK-NEXT:    [[NEXT_PEXT0:%.*]] = call <vscale x 4 x i1> @llvm.aarch64.sve.pext.nxv4i1(target("aarch64.svcount") [[PAC_NEXT]], i32 0)
; CHECK-NEXT:    [[NEXT_MASK:%.*]] = call <vscale x 8 x i1> @llvm.vector.insert.nxv8i1.nxv4i1(<vscale x 8 x i1> [[NEXT_MASK1]], <vscale x 4 x i1> [[NEXT_PEXT0]], i64 0)
; CHECK-NEXT:    [[MORE:%.*]] = extractelement <vscale x 8 x i1> [[NEXT_MASK]], i64 0
; CHECK-NEXT:    br i1 [[MORE]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %start.mask = call <vscale x 8 x i1> @llvm.get.active.lane.mask.nxv8i1.i64(i64 0, i64 %n)
  br label %preheader

preheader:
  %vscale = call i64 @llvm.vscale.i64()
  %step = shl i64 %vscale, 3
  br label %loop

loop:
  %base = phi i64 [ 0, %preheader ], [ %next.base, %loop ]
  %update.mask = phi <vscale x 8 x i1> [ %start.mask, %preheader ], [ %new.mask, %loop ]
  %ptr0 = getelementptr i32, ptr %x, i64 %base
  %v = call <vscale x 8 x i32> @llvm.masked.load.nxv8i32(ptr %ptr0, i32 4, <vscale x 8 x i1> %update.mask, <vscale x 8 x i32> poison)
  %add = add <vscale x 8 x i32> %v, splat (i32 1)
  call void @llvm.masked.store.nxv8i32(<vscale x 8 x i32> %add, ptr %ptr0, i32 4, <vscale x 8 x i1> %update.mask)
  %next.base = add i64 %base, %step
  %new.mask = call <vscale x 8 x i1> @llvm.get.active.lane.mask.nxv8i1.i64(i64 %next.base, i64 %n)
  %more = extractelement <vscale x 8 x i1> %new.mask, i64 0
  br i1 %more, label %loop, label %exit

exit:
  ret void
}

define void @mixed_data_vector_types(ptr %x, ptr %y, i64 %n) #0 {
; CHECK-LABEL: define void @mixed_data_vector_types(
; CHECK-SAME: ptr [[X:%.*]], ptr [[Y:%.*]], i64 [[N:%.*]]) #[[ATTR1]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[PREHEADER:.*]]
; CHECK:       [[PREHEADER]]:
; CHECK-NEXT:    [[START_MASK:%.*]] = call <vscale x 8 x i1> @llvm.get.active.lane.mask.nxv8i1.i64(i64 0, i64 [[N]])
; CHECK-NEXT:    [[VSCALE:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[STEP:%.*]] = shl i64 [[VSCALE]], 3
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[BASE:%.*]] = phi i64 [ 0, %[[PREHEADER]] ], [ [[NEXT_BASE:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[UPDATE_MASK:%.*]] = phi <vscale x 8 x i1> [ [[START_MASK]], %[[PREHEADER]] ], [ [[NEW_MASK:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[PTR64:%.*]] = getelementptr [8 x i8], ptr [[X]], i64 [[BASE]]
; CHECK-NEXT:    [[PTR32:%.*]] = getelementptr [4 x i8], ptr [[Y]], i64 [[BASE]]
; CHECK-NEXT:    [[V64:%.*]] = call <vscale x 8 x i64> @llvm.masked.load.nxv8i64.p0(ptr align 8 [[PTR64]], <vscale x 8 x i1> [[UPDATE_MASK]], <vscale x 8 x i64> poison)
; CHECK-NEXT:    [[V32:%.*]] = call <vscale x 8 x i32> @llvm.masked.load.nxv8i32.p0(ptr align 4 [[PTR32]], <vscale x 8 x i1> [[UPDATE_MASK]], <vscale x 8 x i32> poison)
; CHECK-NEXT:    call void @use_nxv8i64(<vscale x 8 x i64> [[V64]])
; CHECK-NEXT:    call void @use_nxv8i32(<vscale x 8 x i32> [[V32]])
; CHECK-NEXT:    [[NEXT_BASE]] = add i64 [[BASE]], [[STEP]]
; CHECK-NEXT:    [[NEW_MASK]] = call <vscale x 8 x i1> @llvm.get.active.lane.mask.nxv8i1.i64(i64 [[NEXT_BASE]], i64 [[N]])
; CHECK-NEXT:    [[MORE:%.*]] = extractelement <vscale x 8 x i1> [[NEW_MASK]], i64 0
; CHECK-NEXT:    br i1 [[MORE]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %start.mask = call <vscale x 8 x i1> @llvm.get.active.lane.mask.nxv8i1.i64(i64 0, i64 %n)
  br label %preheader

preheader:
  %vscale = call i64 @llvm.vscale.i64()
  %step = shl i64 %vscale, 3
  br label %loop

loop:
  %base = phi i64 [ 0, %preheader ], [ %next.base, %loop ]
  %update.mask = phi <vscale x 8 x i1> [ %start.mask, %preheader ], [ %new.mask, %loop ]
  %ptr64 = getelementptr i64, ptr %x, i64 %base
  %ptr32 = getelementptr i32, ptr %y, i64 %base
  %v64 = call <vscale x 8 x i64> @llvm.masked.load.nxv8i64(ptr %ptr64, i32 8, <vscale x 8 x i1> %update.mask, <vscale x 8 x i64> poison)
  %v32 = call <vscale x 8 x i32> @llvm.masked.load.nxv8i32(ptr %ptr32, i32 4, <vscale x 8 x i1> %update.mask, <vscale x 8 x i32> poison)
  call void @use_nxv8i64(<vscale x 8 x i64> %v64)
  call void @use_nxv8i32(<vscale x 8 x i32> %v32)
  %next.base = add i64 %base, %step
  %new.mask = call <vscale x 8 x i1> @llvm.get.active.lane.mask.nxv8i1.i64(i64 %next.base, i64 %n)
  %more = extractelement <vscale x 8 x i1> %new.mask, i64 0
  br i1 %more, label %loop, label %exit

exit:
  ret void
}

attributes #0 = { "target-features"="+sve2p1" }
