; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -aarch64-predicate-as-counter-loop-rewrites -mtriple=aarch64-linux-gnu -mattr=+sve2p1 < %s | FileCheck %s

target triple = "aarch64-unknown-linux-gnu"

define void @rewrite_extractelement_lane0_i64(i64 %n) #0 {
; CHECK-LABEL: define void @rewrite_extractelement_lane0_i64(
; CHECK-SAME: i64 [[N:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[PREHEADER:.*]]
; CHECK:       [[PREHEADER]]:
; CHECK-NEXT:    [[PAC_MASK:%.*]] = call target("aarch64.svcount") @llvm.aarch64.sve.whilelo.c64(i64 0, i64 [[N]], i32 4)
; CHECK-NEXT:    [[VSCALE:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[STEP:%.*]] = shl i64 [[VSCALE]], 3
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[BASE:%.*]] = phi i64 [ 0, %[[PREHEADER]] ], [ [[NEXT_BASE:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[UPDATE_MASK_PN:%.*]] = phi target("aarch64.svcount") [ [[PAC_MASK]], %[[PREHEADER]] ], [ [[PAC_MASK1:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[PAC_PEXT_PAIR:%.*]] = call { <vscale x 2 x i1>, <vscale x 2 x i1> } @llvm.aarch64.sve.pext.x2.nxv2i1(target("aarch64.svcount") [[UPDATE_MASK_PN]], i32 0)
; CHECK-NEXT:    [[PAC_PEXT1:%.*]] = extractvalue { <vscale x 2 x i1>, <vscale x 2 x i1> } [[PAC_PEXT_PAIR]], 0
; CHECK-NEXT:    [[PAC_MASK4:%.*]] = call <vscale x 8 x i1> @llvm.vector.insert.nxv8i1.nxv2i1(<vscale x 8 x i1> poison, <vscale x 2 x i1> [[PAC_PEXT1]], i64 0)
; CHECK-NEXT:    [[PAC_PEXT5:%.*]] = extractvalue { <vscale x 2 x i1>, <vscale x 2 x i1> } [[PAC_PEXT_PAIR]], 1
; CHECK-NEXT:    [[PAC_MASK6:%.*]] = call <vscale x 8 x i1> @llvm.vector.insert.nxv8i1.nxv2i1(<vscale x 8 x i1> [[PAC_MASK4]], <vscale x 2 x i1> [[PAC_PEXT5]], i64 2)
; CHECK-NEXT:    [[PAC_PEXT_PAIR5:%.*]] = call { <vscale x 2 x i1>, <vscale x 2 x i1> } @llvm.aarch64.sve.pext.x2.nxv2i1(target("aarch64.svcount") [[UPDATE_MASK_PN]], i32 1)
; CHECK-NEXT:    [[PAC_PEXT6:%.*]] = extractvalue { <vscale x 2 x i1>, <vscale x 2 x i1> } [[PAC_PEXT_PAIR5]], 0
; CHECK-NEXT:    [[PAC_MASK7:%.*]] = call <vscale x 8 x i1> @llvm.vector.insert.nxv8i1.nxv2i1(<vscale x 8 x i1> [[PAC_MASK6]], <vscale x 2 x i1> [[PAC_PEXT6]], i64 4)
; CHECK-NEXT:    [[PAC_PEXT8:%.*]] = extractvalue { <vscale x 2 x i1>, <vscale x 2 x i1> } [[PAC_PEXT_PAIR5]], 1
; CHECK-NEXT:    [[PAC_MASK8:%.*]] = call <vscale x 8 x i1> @llvm.vector.insert.nxv8i1.nxv2i1(<vscale x 8 x i1> [[PAC_MASK7]], <vscale x 2 x i1> [[PAC_PEXT8]], i64 6)
; CHECK-NEXT:    call void (...) @llvm.fake.use(<vscale x 8 x i1> [[PAC_MASK8]])
; CHECK-NEXT:    [[NEXT_BASE]] = add i64 [[BASE]], [[STEP]]
; CHECK-NEXT:    [[PAC_MASK1]] = call target("aarch64.svcount") @llvm.aarch64.sve.whilelo.c64(i64 [[NEXT_BASE]], i64 [[N]], i32 4)
; CHECK-NEXT:    [[PAC_PEXT:%.*]] = call <vscale x 2 x i1> @llvm.aarch64.sve.pext.nxv2i1(target("aarch64.svcount") [[PAC_MASK1]], i32 0)
; CHECK-NEXT:    [[MORE:%.*]] = extractelement <vscale x 2 x i1> [[PAC_PEXT]], i64 0
; CHECK-NEXT:    br i1 [[MORE]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %preheader

preheader:
  %start.mask = call <vscale x 8 x i1> @llvm.get.active.lane.mask.for.type.nxv8i1.i64(i64 0, i64 %n, i64 8)
  %vscale = call i64 @llvm.vscale.i64()
  %step = shl i64 %vscale, 3
  br label %loop

loop:
  %base = phi i64 [ 0, %preheader ], [ %next.base, %loop ]
  %update.mask = phi <vscale x 8 x i1> [ %start.mask, %preheader ], [ %new.mask, %loop ]
  call void (...) @llvm.fake.use(<vscale x 8 x i1> %update.mask)
  %next.base = add i64 %base, %step
  %new.mask = call <vscale x 8 x i1> @llvm.get.active.lane.mask.for.type.nxv8i1.i64(i64 %next.base, i64 %n, i64 8)
  %more = extractelement <vscale x 8 x i1> %new.mask, i64 0
  br i1 %more, label %loop, label %exit

exit:
  ret void
}

define void @rewrite_extractelement_lane3_i32(i64 %n) #0 {
; CHECK-LABEL: define void @rewrite_extractelement_lane3_i32(
; CHECK-SAME: i64 [[N:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[PREHEADER:.*]]
; CHECK:       [[PREHEADER]]:
; CHECK-NEXT:    [[PAC_MASK:%.*]] = call target("aarch64.svcount") @llvm.aarch64.sve.whilelo.c32(i64 0, i64 [[N]], i32 2)
; CHECK-NEXT:    [[VSCALE:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[STEP:%.*]] = shl i64 [[VSCALE]], 3
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[BASE:%.*]] = phi i64 [ 0, %[[PREHEADER]] ], [ [[NEXT_BASE:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[UPDATE_MASK_PN:%.*]] = phi target("aarch64.svcount") [ [[PAC_MASK]], %[[PREHEADER]] ], [ [[PAC_MASK1:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[PAC_PEXT_PAIR:%.*]] = call { <vscale x 4 x i1>, <vscale x 4 x i1> } @llvm.aarch64.sve.pext.x2.nxv4i1(target("aarch64.svcount") [[UPDATE_MASK_PN]], i32 0)
; CHECK-NEXT:    [[PAC_PEXT1:%.*]] = extractvalue { <vscale x 4 x i1>, <vscale x 4 x i1> } [[PAC_PEXT_PAIR]], 0
; CHECK-NEXT:    [[PAC_MASK2:%.*]] = call <vscale x 8 x i1> @llvm.vector.insert.nxv8i1.nxv4i1(<vscale x 8 x i1> poison, <vscale x 4 x i1> [[PAC_PEXT1]], i64 0)
; CHECK-NEXT:    [[PAC_PEXT3:%.*]] = extractvalue { <vscale x 4 x i1>, <vscale x 4 x i1> } [[PAC_PEXT_PAIR]], 1
; CHECK-NEXT:    [[PAC_MASK4:%.*]] = call <vscale x 8 x i1> @llvm.vector.insert.nxv8i1.nxv4i1(<vscale x 8 x i1> [[PAC_MASK2]], <vscale x 4 x i1> [[PAC_PEXT3]], i64 4)
; CHECK-NEXT:    call void (...) @llvm.fake.use(<vscale x 8 x i1> [[PAC_MASK4]])
; CHECK-NEXT:    [[NEXT_BASE]] = add i64 [[BASE]], [[STEP]]
; CHECK-NEXT:    [[PAC_MASK1]] = call target("aarch64.svcount") @llvm.aarch64.sve.whilelo.c32(i64 [[NEXT_BASE]], i64 [[N]], i32 2)
; CHECK-NEXT:    [[PAC_PEXT:%.*]] = call <vscale x 4 x i1> @llvm.aarch64.sve.pext.nxv4i1(target("aarch64.svcount") [[PAC_MASK1]], i32 0)
; CHECK-NEXT:    [[MORE:%.*]] = extractelement <vscale x 4 x i1> [[PAC_PEXT]], i64 3
; CHECK-NEXT:    br i1 [[MORE]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %preheader

preheader:
  %start.mask = call <vscale x 8 x i1> @llvm.get.active.lane.mask.for.type.nxv8i1.i64(i64 0, i64 %n, i64 4)
  %vscale = call i64 @llvm.vscale.i64()
  %step = shl i64 %vscale, 3
  br label %loop

loop:
  %base = phi i64 [ 0, %preheader ], [ %next.base, %loop ]
  %update.mask = phi <vscale x 8 x i1> [ %start.mask, %preheader ], [ %new.mask, %loop ]
  call void (...) @llvm.fake.use(<vscale x 8 x i1> %update.mask)
  %next.base = add i64 %base, %step
  %new.mask = call <vscale x 8 x i1> @llvm.get.active.lane.mask.for.type.nxv8i1.i64(i64 %next.base, i64 %n, i64 4)
  %more = extractelement <vscale x 8 x i1> %new.mask, i64 3
  br i1 %more, label %loop, label %exit

exit:
  ret void
}

attributes #0 = { "target-features"="+sve2p1" }
