; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --filter-out-after "^scalar.ph:" --version 4
; RUN: opt -S -mtriple=aarch64-unknown-linux-gnu -mattr=+sve2 -passes=loop-vectorize -enable-partial-aliasing-vectorization %s | FileCheck %s
; RUN: opt -S -mtriple=aarch64-unknown-linux-gnu -mattr=+sve2 -passes=loop-vectorize -enable-partial-aliasing-vectorization -prefer-predicate-over-epilogue=predicate-dont-vectorize %s | FileCheck %s --check-prefix=CHECK-TF

define void @alias_mask(ptr noalias %a, ptr %b, ptr %c, i64 %n) {
; CHECK-LABEL: define void @alias_mask(
; CHECK-SAME: ptr noalias [[A:%.*]], ptr [[B:%.*]], ptr [[C:%.*]], i64 [[N:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[B3:%.*]] = ptrtoint ptr [[B]] to i64
; CHECK-NEXT:    [[C2:%.*]] = ptrtoint ptr [[C]] to i64
; CHECK-NEXT:    [[CMP11:%.*]] = icmp sgt i64 [[N]], 0
; CHECK-NEXT:    br i1 [[CMP11]], label [[FOR_BODY_PREHEADER:%.*]], label [[FOR_COND_CLEANUP:%.*]]
; CHECK:       for.body.preheader:
; CHECK-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[TMP1:%.*]] = shl nuw i64 [[TMP0]], 4
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 [[N]], [[TMP1]]
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label [[SCALAR_PH:%.*]], label [[VECTOR_PH1:%.*]]
; CHECK:       vector.min.vf.check:
; CHECK-NEXT:    [[TMP12:%.*]] = inttoptr i64 [[B3]] to ptr
; CHECK-NEXT:    [[TMP9:%.*]] = inttoptr i64 [[C2]] to ptr
; CHECK-NEXT:    [[ALIAS_LANE_MASK7:%.*]] = call <vscale x 16 x i1> @llvm.loop.dependence.war.mask.nxv16i1(ptr [[TMP12]], ptr [[TMP9]], i64 1)
; CHECK-NEXT:    [[TMP8:%.*]] = zext <vscale x 16 x i1> [[ALIAS_LANE_MASK7]] to <vscale x 16 x i32>
; CHECK-NEXT:    [[TMP11:%.*]] = call i32 @llvm.vector.reduce.add.nxv16i32(<vscale x 16 x i32> [[TMP8]])
; CHECK-NEXT:    [[TMP10:%.*]] = zext i32 [[TMP11]] to i64
; CHECK-NEXT:    [[CMP_VF:%.*]] = icmp ult i64 [[TMP10]], 2
; CHECK-NEXT:    br i1 [[CMP_VF]], label [[SCALAR_PH]], label [[VECTOR_PH:%.*]]
; CHECK:       vector.ph:
; CHECK-NEXT:    [[TMP14:%.*]] = urem i64 [[N]], [[TMP10]]
; CHECK-NEXT:    [[TMP15:%.*]] = sub i64 [[N]], [[TMP14]]
; CHECK-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK:       vector.body:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP16:%.*]] = getelementptr inbounds i8, ptr [[A]], i64 [[INDEX]]
; CHECK-NEXT:    [[WIDE_MASKED_LOAD:%.*]] = call <vscale x 16 x i8> @llvm.masked.load.nxv16i8.p0(ptr align 1 [[TMP16]], <vscale x 16 x i1> [[ALIAS_LANE_MASK7]], <vscale x 16 x i8> poison)
; CHECK-NEXT:    [[TMP18:%.*]] = getelementptr inbounds i8, ptr [[B]], i64 [[INDEX]]
; CHECK-NEXT:    [[WIDE_MASKED_LOAD5:%.*]] = call <vscale x 16 x i8> @llvm.masked.load.nxv16i8.p0(ptr align 1 [[TMP18]], <vscale x 16 x i1> [[ALIAS_LANE_MASK7]], <vscale x 16 x i8> poison)
; CHECK-NEXT:    [[TMP13:%.*]] = select <vscale x 16 x i1> [[ALIAS_LANE_MASK7]], <vscale x 16 x i8> [[WIDE_MASKED_LOAD]], <vscale x 16 x i8> splat (i8 1)
; CHECK-NEXT:    [[TMP20:%.*]] = sdiv <vscale x 16 x i8> [[WIDE_MASKED_LOAD5]], [[TMP13]]
; CHECK-NEXT:    [[TMP21:%.*]] = getelementptr inbounds i8, ptr [[C]], i64 [[INDEX]]
; CHECK-NEXT:    call void @llvm.masked.store.nxv16i8.p0(<vscale x 16 x i8> [[TMP20]], ptr align 1 [[TMP21]], <vscale x 16 x i1> [[ALIAS_LANE_MASK7]])
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP10]]
; CHECK-NEXT:    [[TMP17:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[TMP15]]
; CHECK-NEXT:    br i1 [[TMP17]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       middle.block:
; CHECK-NEXT:    [[CMP_N15:%.*]] = icmp eq i64 [[N]], [[TMP15]]
; CHECK-NEXT:    br i1 [[CMP_N15]], label [[EXIT_LOOPEXIT:%.*]], label [[SCALAR_PH]]
; CHECK:       scalar.ph:
;
; CHECK-TF-LABEL: define void @alias_mask(
; CHECK-TF-SAME: ptr noalias [[A:%.*]], ptr [[B:%.*]], ptr [[C:%.*]], i64 [[N:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-TF-NEXT:  entry:
; CHECK-TF-NEXT:    [[B2:%.*]] = ptrtoint ptr [[B]] to i64
; CHECK-TF-NEXT:    [[C1:%.*]] = ptrtoint ptr [[C]] to i64
; CHECK-TF-NEXT:    [[CMP11:%.*]] = icmp sgt i64 [[N]], 0
; CHECK-TF-NEXT:    br i1 [[CMP11]], label [[FOR_BODY_PREHEADER:%.*]], label [[EXIT:%.*]]
; CHECK-TF:       for.body.preheader:
; CHECK-TF-NEXT:    br label [[VECTOR_MEMCHECK:%.*]]
; CHECK-TF:       vector.min.vf.check:
; CHECK-TF-NEXT:    [[TMP1:%.*]] = inttoptr i64 [[B2]] to ptr
; CHECK-TF-NEXT:    [[TMP2:%.*]] = inttoptr i64 [[C1]] to ptr
; CHECK-TF-NEXT:    [[TMP3:%.*]] = call <vscale x 16 x i1> @llvm.loop.dependence.war.mask.nxv16i1(ptr [[TMP1]], ptr [[TMP2]], i64 1)
; CHECK-TF-NEXT:    [[TMP4:%.*]] = zext <vscale x 16 x i1> [[TMP3]] to <vscale x 16 x i32>
; CHECK-TF-NEXT:    [[TMP5:%.*]] = call i32 @llvm.vector.reduce.add.nxv16i32(<vscale x 16 x i32> [[TMP4]])
; CHECK-TF-NEXT:    [[TMP6:%.*]] = zext i32 [[TMP5]] to i64
; CHECK-TF-NEXT:    [[CMP_VF:%.*]] = icmp ult i64 [[TMP6]], 2
; CHECK-TF-NEXT:    br i1 [[CMP_VF]], label [[SCALAR_PH:%.*]], label [[VECTOR_PH:%.*]]
; CHECK-TF:       vector.ph:
; CHECK-TF-NEXT:    [[TMP7:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-TF-NEXT:    [[TMP8:%.*]] = shl nuw i64 [[TMP7]], 4
; CHECK-TF-NEXT:    [[TMP9:%.*]] = sub i64 [[N]], [[TMP8]]
; CHECK-TF-NEXT:    [[TMP10:%.*]] = icmp ugt i64 [[N]], [[TMP8]]
; CHECK-TF-NEXT:    [[TMP11:%.*]] = select i1 [[TMP10]], i64 [[TMP9]], i64 0
; CHECK-TF-NEXT:    [[ACTIVE_LANE_MASK_ENTRY:%.*]] = call <vscale x 16 x i1> @llvm.get.active.lane.mask.nxv16i1.i64(i64 0, i64 [[N]])
; CHECK-TF-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK-TF:       vector.body:
; CHECK-TF-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], [[VECTOR_BODY]] ]
; CHECK-TF-NEXT:    [[ACTIVE_LANE_MASK:%.*]] = phi <vscale x 16 x i1> [ [[ACTIVE_LANE_MASK_ENTRY]], [[VECTOR_PH]] ], [ [[ACTIVE_LANE_MASK_NEXT:%.*]], [[VECTOR_BODY]] ]
; CHECK-TF-NEXT:    [[TMP12:%.*]] = and <vscale x 16 x i1> [[ACTIVE_LANE_MASK]], [[TMP3]]
; CHECK-TF-NEXT:    [[TMP13:%.*]] = getelementptr inbounds i8, ptr [[A]], i64 [[INDEX]]
; CHECK-TF-NEXT:    [[WIDE_MASKED_LOAD:%.*]] = call <vscale x 16 x i8> @llvm.masked.load.nxv16i8.p0(ptr align 1 [[TMP13]], <vscale x 16 x i1> [[TMP12]], <vscale x 16 x i8> poison)
; CHECK-TF-NEXT:    [[TMP14:%.*]] = getelementptr inbounds i8, ptr [[B]], i64 [[INDEX]]
; CHECK-TF-NEXT:    [[WIDE_MASKED_LOAD5:%.*]] = call <vscale x 16 x i8> @llvm.masked.load.nxv16i8.p0(ptr align 1 [[TMP14]], <vscale x 16 x i1> [[TMP12]], <vscale x 16 x i8> poison)
; CHECK-TF-NEXT:    [[TMP19:%.*]] = select <vscale x 16 x i1> [[TMP12]], <vscale x 16 x i8> [[WIDE_MASKED_LOAD]], <vscale x 16 x i8> splat (i8 1)
; CHECK-TF-NEXT:    [[TMP15:%.*]] = sdiv <vscale x 16 x i8> [[WIDE_MASKED_LOAD5]], [[TMP19]]
; CHECK-TF-NEXT:    [[TMP16:%.*]] = getelementptr inbounds i8, ptr [[C]], i64 [[INDEX]]
; CHECK-TF-NEXT:    call void @llvm.masked.store.nxv16i8.p0(<vscale x 16 x i8> [[TMP15]], ptr align 1 [[TMP16]], <vscale x 16 x i1> [[TMP12]])
; CHECK-TF-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], [[TMP6]]
; CHECK-TF-NEXT:    [[ACTIVE_LANE_MASK_NEXT]] = call <vscale x 16 x i1> @llvm.get.active.lane.mask.nxv16i1.i64(i64 [[INDEX]], i64 [[TMP11]])
; CHECK-TF-NEXT:    [[TMP17:%.*]] = extractelement <vscale x 16 x i1> [[ACTIVE_LANE_MASK_NEXT]], i32 0
; CHECK-TF-NEXT:    [[TMP18:%.*]] = xor i1 [[TMP17]], true
; CHECK-TF-NEXT:    br i1 [[TMP18]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK-TF:       middle.block:
; CHECK-TF-NEXT:    br label [[EXIT_LOOPEXIT:%.*]]
; CHECK-TF:       scalar.ph:
;
entry:
  %cmp11 = icmp sgt i64 %n, 0
  br i1 %cmp11, label %for.body, label %exit

for.body:                                         ; preds = %for.body.preheader, %for.body
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %for.body ]
  %gep.a = getelementptr inbounds i8, ptr %a, i64 %iv
  %load.a = load i8, ptr %gep.a, align 1
  %gep.b = getelementptr inbounds i8, ptr %b, i64 %iv
  %load.b = load i8, ptr %gep.b, align 1
  %div = sdiv i8 %load.b, %load.a
  %gep.c = getelementptr inbounds i8, ptr %c, i64 %iv
  store i8 %div, ptr %gep.c, align 1
  %iv.next = add nuw nsw i64 %iv, 1
  %exitcond.not = icmp eq i64 %iv.next, %n
  br i1 %exitcond.not, label %exit, label %for.body

exit:                                 ; preds = %for.body, %entry
  ret void
}

define i32 @alias_mask_read_after_write(ptr noalias %a, ptr %b, ptr %c, i64 %n) {
; CHECK-LABEL: define i32 @alias_mask_read_after_write(
; CHECK-SAME: ptr noalias [[A:%.*]], ptr [[B:%.*]], ptr [[C:%.*]], i64 [[N:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[C2:%.*]] = ptrtoint ptr [[C]] to i64
; CHECK-NEXT:    [[B1:%.*]] = ptrtoint ptr [[B]] to i64
; CHECK-NEXT:    [[CMP19:%.*]] = icmp sgt i64 [[N]], 0
; CHECK-NEXT:    br i1 [[CMP19]], label [[FOR_BODY_PREHEADER:%.*]], label [[FOR_COND_CLEANUP:%.*]]
; CHECK:       for.body.preheader:
; CHECK-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[TMP1:%.*]] = shl nuw i64 [[TMP0]], 2
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 [[N]], [[TMP1]]
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label [[SCALAR_PH:%.*]], label [[VECTOR_PH:%.*]]
; CHECK:       vector.min.vf.check:
; CHECK-NEXT:    [[TMP9:%.*]] = inttoptr i64 [[C2]] to ptr
; CHECK-NEXT:    [[TMP4:%.*]] = inttoptr i64 [[B1]] to ptr
; CHECK-NEXT:    [[TMP5:%.*]] = call <vscale x 4 x i1> @llvm.loop.dependence.war.mask.nxv4i1(ptr [[TMP9]], ptr [[TMP4]], i64 4)
; CHECK-NEXT:    [[TMP6:%.*]] = zext <vscale x 4 x i1> [[TMP5]] to <vscale x 4 x i32>
; CHECK-NEXT:    [[TMP7:%.*]] = call i32 @llvm.vector.reduce.add.nxv4i32(<vscale x 4 x i32> [[TMP6]])
; CHECK-NEXT:    [[TMP8:%.*]] = zext i32 [[TMP7]] to i64
; CHECK-NEXT:    [[CMP_VF:%.*]] = icmp ult i64 [[TMP8]], 2
; CHECK-NEXT:    br i1 [[CMP_VF]], label [[SCALAR_PH]], label [[VECTOR_PH1:%.*]]
; CHECK:       vector.ph:
; CHECK-NEXT:    [[TMP18:%.*]] = urem i64 [[N]], [[TMP8]]
; CHECK-NEXT:    [[TMP15:%.*]] = sub i64 [[N]], [[TMP18]]
; CHECK-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK:       vector.body:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH1]] ], [ [[INDEX_NEXT:%.*]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[VEC_PHI:%.*]] = phi <vscale x 4 x i32> [ zeroinitializer, [[VECTOR_PH1]] ], [ [[TMP25:%.*]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP17:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[INDEX]]
; CHECK-NEXT:    [[WIDE_MASKED_LOAD:%.*]] = call <vscale x 4 x i32> @llvm.masked.load.nxv4i32.p0(ptr align 2 [[TMP17]], <vscale x 4 x i1> [[TMP5]], <vscale x 4 x i32> poison)
; CHECK-NEXT:    [[TMP19:%.*]] = getelementptr inbounds i32, ptr [[C]], i64 [[INDEX]]
; CHECK-NEXT:    call void @llvm.masked.store.nxv4i32.p0(<vscale x 4 x i32> [[WIDE_MASKED_LOAD]], ptr align 2 [[TMP19]], <vscale x 4 x i1> [[TMP5]])
; CHECK-NEXT:    [[TMP21:%.*]] = getelementptr inbounds i32, ptr [[B]], i64 [[INDEX]]
; CHECK-NEXT:    [[WIDE_MASKED_LOAD5:%.*]] = call <vscale x 4 x i32> @llvm.masked.load.nxv4i32.p0(ptr align 2 [[TMP21]], <vscale x 4 x i1> [[TMP5]], <vscale x 4 x i32> poison)
; CHECK-NEXT:    [[TMP23:%.*]] = add <vscale x 4 x i32> [[WIDE_MASKED_LOAD]], [[VEC_PHI]]
; CHECK-NEXT:    [[TMP25]] = add <vscale x 4 x i32> [[TMP23]], [[WIDE_MASKED_LOAD5]]
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP8]]
; CHECK-NEXT:    [[TMP14:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[TMP15]]
; CHECK-NEXT:    br i1 [[TMP14]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP4:![0-9]+]]
; CHECK:       middle.block:
; CHECK-NEXT:    [[TMP16:%.*]] = call i32 @llvm.vector.reduce.add.nxv4i32(<vscale x 4 x i32> [[TMP25]])
; CHECK-NEXT:    [[CMP_N:%.*]] = icmp eq i64 [[N]], [[TMP15]]
; CHECK-NEXT:    br i1 [[CMP_N]], label [[EXIT_LOOPEXIT:%.*]], label [[SCALAR_PH]]
; CHECK:       scalar.ph:
;
; CHECK-TF-LABEL: define i32 @alias_mask_read_after_write(
; CHECK-TF-SAME: ptr noalias [[A:%.*]], ptr [[B:%.*]], ptr [[C:%.*]], i64 [[N:%.*]]) #[[ATTR0]] {
; CHECK-TF-NEXT:  entry:
; CHECK-TF-NEXT:    [[C2:%.*]] = ptrtoint ptr [[C]] to i64
; CHECK-TF-NEXT:    [[B1:%.*]] = ptrtoint ptr [[B]] to i64
; CHECK-TF-NEXT:    [[CMP19:%.*]] = icmp sgt i64 [[N]], 0
; CHECK-TF-NEXT:    br i1 [[CMP19]], label [[FOR_BODY_PREHEADER:%.*]], label [[EXIT:%.*]]
; CHECK-TF:       for.body.preheader:
; CHECK-TF-NEXT:    br label [[VECTOR_MEMCHECK:%.*]]
; CHECK-TF:       vector.min.vf.check:
; CHECK-TF-NEXT:    [[TMP1:%.*]] = inttoptr i64 [[C2]] to ptr
; CHECK-TF-NEXT:    [[TMP2:%.*]] = inttoptr i64 [[B1]] to ptr
; CHECK-TF-NEXT:    [[TMP3:%.*]] = call <vscale x 4 x i1> @llvm.loop.dependence.war.mask.nxv4i1(ptr [[TMP1]], ptr [[TMP2]], i64 4)
; CHECK-TF-NEXT:    [[TMP4:%.*]] = zext <vscale x 4 x i1> [[TMP3]] to <vscale x 4 x i32>
; CHECK-TF-NEXT:    [[TMP5:%.*]] = call i32 @llvm.vector.reduce.add.nxv4i32(<vscale x 4 x i32> [[TMP4]])
; CHECK-TF-NEXT:    [[TMP6:%.*]] = zext i32 [[TMP5]] to i64
; CHECK-TF-NEXT:    [[CMP_VF:%.*]] = icmp ult i64 [[TMP6]], 2
; CHECK-TF-NEXT:    br i1 [[CMP_VF]], label [[SCALAR_PH:%.*]], label [[VECTOR_PH:%.*]]
; CHECK-TF:       vector.ph:
; CHECK-TF-NEXT:    [[TMP7:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-TF-NEXT:    [[TMP8:%.*]] = shl nuw i64 [[TMP7]], 2
; CHECK-TF-NEXT:    [[TMP9:%.*]] = sub i64 [[N]], [[TMP8]]
; CHECK-TF-NEXT:    [[TMP10:%.*]] = icmp ugt i64 [[N]], [[TMP8]]
; CHECK-TF-NEXT:    [[TMP11:%.*]] = select i1 [[TMP10]], i64 [[TMP9]], i64 0
; CHECK-TF-NEXT:    [[ACTIVE_LANE_MASK_ENTRY:%.*]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 0, i64 [[N]])
; CHECK-TF-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK-TF:       vector.body:
; CHECK-TF-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], [[VECTOR_BODY]] ]
; CHECK-TF-NEXT:    [[ACTIVE_LANE_MASK:%.*]] = phi <vscale x 4 x i1> [ [[ACTIVE_LANE_MASK_ENTRY]], [[VECTOR_PH]] ], [ [[ACTIVE_LANE_MASK_NEXT:%.*]], [[VECTOR_BODY]] ]
; CHECK-TF-NEXT:    [[VEC_PHI:%.*]] = phi <vscale x 4 x i32> [ zeroinitializer, [[VECTOR_PH]] ], [ [[TMP18:%.*]], [[VECTOR_BODY]] ]
; CHECK-TF-NEXT:    [[TMP12:%.*]] = and <vscale x 4 x i1> [[ACTIVE_LANE_MASK]], [[TMP3]]
; CHECK-TF-NEXT:    [[TMP13:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[INDEX]]
; CHECK-TF-NEXT:    [[WIDE_MASKED_LOAD:%.*]] = call <vscale x 4 x i32> @llvm.masked.load.nxv4i32.p0(ptr align 2 [[TMP13]], <vscale x 4 x i1> [[TMP12]], <vscale x 4 x i32> poison)
; CHECK-TF-NEXT:    [[TMP14:%.*]] = getelementptr inbounds i32, ptr [[C]], i64 [[INDEX]]
; CHECK-TF-NEXT:    call void @llvm.masked.store.nxv4i32.p0(<vscale x 4 x i32> [[WIDE_MASKED_LOAD]], ptr align 2 [[TMP14]], <vscale x 4 x i1> [[TMP12]])
; CHECK-TF-NEXT:    [[TMP15:%.*]] = getelementptr inbounds i32, ptr [[B]], i64 [[INDEX]]
; CHECK-TF-NEXT:    [[WIDE_MASKED_LOAD5:%.*]] = call <vscale x 4 x i32> @llvm.masked.load.nxv4i32.p0(ptr align 2 [[TMP15]], <vscale x 4 x i1> [[TMP12]], <vscale x 4 x i32> poison)
; CHECK-TF-NEXT:    [[TMP16:%.*]] = add <vscale x 4 x i32> [[WIDE_MASKED_LOAD]], [[VEC_PHI]]
; CHECK-TF-NEXT:    [[TMP17:%.*]] = add <vscale x 4 x i32> [[TMP16]], [[WIDE_MASKED_LOAD5]]
; CHECK-TF-NEXT:    [[TMP18]] = select <vscale x 4 x i1> [[TMP12]], <vscale x 4 x i32> [[TMP17]], <vscale x 4 x i32> [[VEC_PHI]]
; CHECK-TF-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], [[TMP6]]
; CHECK-TF-NEXT:    [[ACTIVE_LANE_MASK_NEXT]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 [[INDEX]], i64 [[TMP11]])
; CHECK-TF-NEXT:    [[TMP19:%.*]] = extractelement <vscale x 4 x i1> [[ACTIVE_LANE_MASK_NEXT]], i32 0
; CHECK-TF-NEXT:    [[TMP20:%.*]] = xor i1 [[TMP19]], true
; CHECK-TF-NEXT:    br i1 [[TMP20]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP4:![0-9]+]]
; CHECK-TF:       middle.block:
; CHECK-TF-NEXT:    [[TMP21:%.*]] = call i32 @llvm.vector.reduce.add.nxv4i32(<vscale x 4 x i32> [[TMP18]])
; CHECK-TF-NEXT:    br label [[EXIT_LOOPEXIT:%.*]]
; CHECK-TF:       scalar.ph:
;
entry:
  %cmp19 = icmp sgt i64 %n, 0
  br i1 %cmp19, label %for.body, label %exit

for.body:                                         ; preds = %entry, %for.body
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %for.body ]
  %accum = phi i32 [ 0, %entry ], [ %add2, %for.body ]
  %gep.a = getelementptr inbounds i32, ptr %a, i64 %iv
  %load.a = load i32, ptr %gep.a, align 2
  %gep.c = getelementptr inbounds i32, ptr %c, i64 %iv
  store i32 %load.a, ptr %gep.c, align 2
  %gep.b = getelementptr inbounds i32, ptr %b, i64 %iv
  %load.b = load i32, ptr %gep.b, align 2
  %add = add i32 %load.a, %accum
  %add2 = add i32 %add, %load.b
  %iv.next = add nuw nsw i64 %iv, 1
  %exitcond.not = icmp eq i64 %iv.next, %n
  br i1 %exitcond.not, label %exit, label %for.body

exit:                        ; preds = %entry, %for.body
  %result = phi i32 [ 0, %entry ], [ %add2, %for.body ]
  ret i32 %result
}

define void @alias_mask_multiple(ptr %a, ptr %b, ptr %c, i64 %n) {
; CHECK-LABEL: define void @alias_mask_multiple(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]], ptr [[C:%.*]], i64 [[N:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[A6:%.*]] = ptrtoint ptr [[A]] to i64
; CHECK-NEXT:    [[B3:%.*]] = ptrtoint ptr [[B]] to i64
; CHECK-NEXT:    [[C1:%.*]] = ptrtoint ptr [[C]] to i64
; CHECK-NEXT:    [[CMP11:%.*]] = icmp sgt i64 [[N]], 0
; CHECK-NEXT:    br i1 [[CMP11]], label [[FOR_BODY_PREHEADER:%.*]], label [[EXIT:%.*]]
; CHECK:       for.body.preheader:
; CHECK-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[TMP1:%.*]] = shl nuw i64 [[TMP0]], 4
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 [[N]], [[TMP1]]
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label [[SCALAR_PH:%.*]], label [[VECTOR_PH1:%.*]]
; CHECK:       vector.min.vf.check:
; CHECK-NEXT:    [[TMP9:%.*]] = inttoptr i64 [[A6]] to ptr
; CHECK-NEXT:    [[TMP10:%.*]] = inttoptr i64 [[C1]] to ptr
; CHECK-NEXT:    [[ALIAS_LANE_MASK12:%.*]] = call <vscale x 16 x i1> @llvm.loop.dependence.war.mask.nxv16i1(ptr [[TMP9]], ptr [[TMP10]], i64 1)
; CHECK-NEXT:    [[TMP13:%.*]] = inttoptr i64 [[B3]] to ptr
; CHECK-NEXT:    [[TMP14:%.*]] = inttoptr i64 [[C1]] to ptr
; CHECK-NEXT:    [[ALIAS_LANE_MASK13:%.*]] = call <vscale x 16 x i1> @llvm.loop.dependence.war.mask.nxv16i1(ptr [[TMP13]], ptr [[TMP14]], i64 1)
; CHECK-NEXT:    [[TMP15:%.*]] = and <vscale x 16 x i1> [[ALIAS_LANE_MASK12]], [[ALIAS_LANE_MASK13]]
; CHECK-NEXT:    [[TMP16:%.*]] = zext <vscale x 16 x i1> [[TMP15]] to <vscale x 16 x i32>
; CHECK-NEXT:    [[TMP17:%.*]] = call i32 @llvm.vector.reduce.add.nxv16i32(<vscale x 16 x i32> [[TMP16]])
; CHECK-NEXT:    [[TMP18:%.*]] = zext i32 [[TMP17]] to i64
; CHECK-NEXT:    [[CMP_VF:%.*]] = icmp ult i64 [[TMP18]], 2
; CHECK-NEXT:    br i1 [[CMP_VF]], label [[SCALAR_PH]], label [[VECTOR_PH:%.*]]
; CHECK:       vector.ph:
; CHECK-NEXT:    [[TMP20:%.*]] = urem i64 [[N]], [[TMP18]]
; CHECK-NEXT:    [[TMP21:%.*]] = sub i64 [[N]], [[TMP20]]
; CHECK-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK:       vector.body:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP25:%.*]] = getelementptr inbounds i8, ptr [[A]], i64 [[INDEX]]
; CHECK-NEXT:    [[WIDE_MASKED_LOAD:%.*]] = call <vscale x 16 x i8> @llvm.masked.load.nxv16i8.p0(ptr align 1 [[TMP25]], <vscale x 16 x i1> [[TMP15]], <vscale x 16 x i8> poison)
; CHECK-NEXT:    [[TMP26:%.*]] = getelementptr inbounds i8, ptr [[B]], i64 [[INDEX]]
; CHECK-NEXT:    [[WIDE_MASKED_LOAD14:%.*]] = call <vscale x 16 x i8> @llvm.masked.load.nxv16i8.p0(ptr align 1 [[TMP26]], <vscale x 16 x i1> [[TMP15]], <vscale x 16 x i8> poison)
; CHECK-NEXT:    [[TMP27:%.*]] = add <vscale x 16 x i8> [[WIDE_MASKED_LOAD14]], [[WIDE_MASKED_LOAD]]
; CHECK-NEXT:    [[TMP28:%.*]] = getelementptr inbounds i8, ptr [[C]], i64 [[INDEX]]
; CHECK-NEXT:    call void @llvm.masked.store.nxv16i8.p0(<vscale x 16 x i8> [[TMP27]], ptr align 1 [[TMP28]], <vscale x 16 x i1> [[TMP15]])
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP18]]
; CHECK-NEXT:    [[TMP22:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[TMP21]]
; CHECK-NEXT:    br i1 [[TMP22]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP6:![0-9]+]]
; CHECK:       middle.block:
; CHECK-NEXT:    [[CMP_N19:%.*]] = icmp eq i64 [[N]], [[TMP21]]
; CHECK-NEXT:    br i1 [[CMP_N19]], label [[EXIT_LOOPEXIT:%.*]], label [[SCALAR_PH]]
; CHECK:       scalar.ph:
;
; CHECK-TF-LABEL: define void @alias_mask_multiple(
; CHECK-TF-SAME: ptr [[A:%.*]], ptr [[B:%.*]], ptr [[C:%.*]], i64 [[N:%.*]]) #[[ATTR0]] {
; CHECK-TF-NEXT:  entry:
; CHECK-TF-NEXT:    [[A7:%.*]] = ptrtoint ptr [[A]] to i64
; CHECK-TF-NEXT:    [[B3:%.*]] = ptrtoint ptr [[B]] to i64
; CHECK-TF-NEXT:    [[C1:%.*]] = ptrtoint ptr [[C]] to i64
; CHECK-TF-NEXT:    [[CMP11:%.*]] = icmp sgt i64 [[N]], 0
; CHECK-TF-NEXT:    br i1 [[CMP11]], label [[FOR_BODY_PREHEADER:%.*]], label [[EXIT:%.*]]
; CHECK-TF:       for.body.preheader:
; CHECK-TF-NEXT:    br label [[VECTOR_MEMCHECK:%.*]]
; CHECK-TF:       vector.min.vf.check:
; CHECK-TF-NEXT:    [[TMP2:%.*]] = inttoptr i64 [[A7]] to ptr
; CHECK-TF-NEXT:    [[TMP3:%.*]] = inttoptr i64 [[C1]] to ptr
; CHECK-TF-NEXT:    [[TMP4:%.*]] = call <vscale x 16 x i1> @llvm.loop.dependence.war.mask.nxv16i1(ptr [[TMP2]], ptr [[TMP3]], i64 1)
; CHECK-TF-NEXT:    [[TMP5:%.*]] = inttoptr i64 [[B3]] to ptr
; CHECK-TF-NEXT:    [[TMP6:%.*]] = inttoptr i64 [[C1]] to ptr
; CHECK-TF-NEXT:    [[TMP7:%.*]] = call <vscale x 16 x i1> @llvm.loop.dependence.war.mask.nxv16i1(ptr [[TMP5]], ptr [[TMP6]], i64 1)
; CHECK-TF-NEXT:    [[TMP8:%.*]] = and <vscale x 16 x i1> [[TMP4]], [[TMP7]]
; CHECK-TF-NEXT:    [[TMP9:%.*]] = zext <vscale x 16 x i1> [[TMP8]] to <vscale x 16 x i32>
; CHECK-TF-NEXT:    [[TMP10:%.*]] = call i32 @llvm.vector.reduce.add.nxv16i32(<vscale x 16 x i32> [[TMP9]])
; CHECK-TF-NEXT:    [[TMP11:%.*]] = zext i32 [[TMP10]] to i64
; CHECK-TF-NEXT:    [[CMP_VF:%.*]] = icmp ult i64 [[TMP11]], 2
; CHECK-TF-NEXT:    br i1 [[CMP_VF]], label [[SCALAR_PH:%.*]], label [[VECTOR_PH:%.*]]
; CHECK-TF:       vector.ph:
; CHECK-TF-NEXT:    [[TMP12:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-TF-NEXT:    [[TMP13:%.*]] = shl nuw i64 [[TMP12]], 4
; CHECK-TF-NEXT:    [[TMP14:%.*]] = sub i64 [[N]], [[TMP13]]
; CHECK-TF-NEXT:    [[TMP15:%.*]] = icmp ugt i64 [[N]], [[TMP13]]
; CHECK-TF-NEXT:    [[TMP16:%.*]] = select i1 [[TMP15]], i64 [[TMP14]], i64 0
; CHECK-TF-NEXT:    [[ACTIVE_LANE_MASK_ENTRY:%.*]] = call <vscale x 16 x i1> @llvm.get.active.lane.mask.nxv16i1.i64(i64 0, i64 [[N]])
; CHECK-TF-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK-TF:       vector.body:
; CHECK-TF-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], [[VECTOR_BODY]] ]
; CHECK-TF-NEXT:    [[ACTIVE_LANE_MASK:%.*]] = phi <vscale x 16 x i1> [ [[ACTIVE_LANE_MASK_ENTRY]], [[VECTOR_PH]] ], [ [[ACTIVE_LANE_MASK_NEXT:%.*]], [[VECTOR_BODY]] ]
; CHECK-TF-NEXT:    [[TMP17:%.*]] = and <vscale x 16 x i1> [[ACTIVE_LANE_MASK]], [[TMP8]]
; CHECK-TF-NEXT:    [[TMP18:%.*]] = getelementptr inbounds i8, ptr [[A]], i64 [[INDEX]]
; CHECK-TF-NEXT:    [[WIDE_MASKED_LOAD:%.*]] = call <vscale x 16 x i8> @llvm.masked.load.nxv16i8.p0(ptr align 1 [[TMP18]], <vscale x 16 x i1> [[TMP17]], <vscale x 16 x i8> poison)
; CHECK-TF-NEXT:    [[TMP19:%.*]] = getelementptr inbounds i8, ptr [[B]], i64 [[INDEX]]
; CHECK-TF-NEXT:    [[WIDE_MASKED_LOAD8:%.*]] = call <vscale x 16 x i8> @llvm.masked.load.nxv16i8.p0(ptr align 1 [[TMP19]], <vscale x 16 x i1> [[TMP17]], <vscale x 16 x i8> poison)
; CHECK-TF-NEXT:    [[TMP20:%.*]] = add <vscale x 16 x i8> [[WIDE_MASKED_LOAD8]], [[WIDE_MASKED_LOAD]]
; CHECK-TF-NEXT:    [[TMP21:%.*]] = getelementptr inbounds i8, ptr [[C]], i64 [[INDEX]]
; CHECK-TF-NEXT:    call void @llvm.masked.store.nxv16i8.p0(<vscale x 16 x i8> [[TMP20]], ptr align 1 [[TMP21]], <vscale x 16 x i1> [[TMP17]])
; CHECK-TF-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], [[TMP11]]
; CHECK-TF-NEXT:    [[ACTIVE_LANE_MASK_NEXT]] = call <vscale x 16 x i1> @llvm.get.active.lane.mask.nxv16i1.i64(i64 [[INDEX]], i64 [[TMP16]])
; CHECK-TF-NEXT:    [[TMP22:%.*]] = extractelement <vscale x 16 x i1> [[ACTIVE_LANE_MASK_NEXT]], i32 0
; CHECK-TF-NEXT:    [[TMP23:%.*]] = xor i1 [[TMP22]], true
; CHECK-TF-NEXT:    br i1 [[TMP23]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP6:![0-9]+]]
; CHECK-TF:       middle.block:
; CHECK-TF-NEXT:    br label [[EXIT_LOOPEXIT:%.*]]
; CHECK-TF:       scalar.ph:
;
entry:
  %cmp11 = icmp sgt i64 %n, 0
  br i1 %cmp11, label %for.body, label %exit

for.body:                                         ; preds = %for.body.preheader, %for.body
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %for.body ]
  %gep.a = getelementptr inbounds i8, ptr %a, i64 %iv
  %load.a = load i8, ptr %gep.a, align 1
  %gep.b = getelementptr inbounds i8, ptr %b, i64 %iv
  %load.b = load i8, ptr %gep.b, align 1
  %add = add i8 %load.b, %load.a
  %gep.c = getelementptr inbounds i8, ptr %c, i64 %iv
  store i8 %add, ptr %gep.c, align 1
  %iv.next = add nuw nsw i64 %iv, 1
  %exitcond.not = icmp eq i64 %iv.next, %n
  br i1 %exitcond.not, label %exit, label %for.body

exit:                                 ; preds = %for.body, %entry
  ret void
}

define i32 @alias_mask_multiple_read_after_write(ptr %a, ptr %b, ptr %c, i64 %n) {
; CHECK-LABEL: define i32 @alias_mask_multiple_read_after_write(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]], ptr [[C:%.*]], i64 [[N:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP19:%.*]] = icmp sgt i64 [[N]], 0
; CHECK-NEXT:    br i1 [[CMP19]], label [[FOR_BODY_PREHEADER:%.*]], label [[EXIT:%.*]]
; CHECK:       for.body.preheader:
; CHECK-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK:       for.body:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ [[IV_NEXT:%.*]], [[VECTOR_BODY]] ], [ 0, [[FOR_BODY_PREHEADER]] ]
; CHECK-NEXT:    [[ACCUM:%.*]] = phi i32 [ [[SDIV:%.*]], [[VECTOR_BODY]] ], [ 0, [[FOR_BODY_PREHEADER]] ]
; CHECK-NEXT:    [[TMP25:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[INDEX]]
; CHECK-NEXT:    [[LOAD_A:%.*]] = load i32, ptr [[TMP25]], align 2
; CHECK-NEXT:    [[TMP26:%.*]] = getelementptr inbounds i32, ptr [[C]], i64 [[INDEX]]
; CHECK-NEXT:    store i32 [[LOAD_A]], ptr [[TMP26]], align 2
; CHECK-NEXT:    [[TMP27:%.*]] = getelementptr inbounds i32, ptr [[B]], i64 [[INDEX]]
; CHECK-NEXT:    [[LOAD_B:%.*]] = load i32, ptr [[TMP27]], align 2
; CHECK-NEXT:    [[ADD:%.*]] = add i32 [[LOAD_A]], [[ACCUM]]
; CHECK-NEXT:    [[SDIV]] = sdiv i32 [[ADD]], [[LOAD_B]]
; CHECK-NEXT:    [[IV_NEXT]] = add nuw nsw i64 [[INDEX]], 1
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[IV_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label [[EXIT_LOOPEXIT:%.*]], label [[VECTOR_BODY]]
; CHECK:       exit.loopexit:
; CHECK-NEXT:    [[SDIV_LCSSA:%.*]] = phi i32 [ [[SDIV]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    br label [[EXIT]]
; CHECK:       exit:
; CHECK-NEXT:    [[RESULT:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[SDIV_LCSSA]], [[EXIT_LOOPEXIT]] ]
; CHECK-NEXT:    ret i32 [[RESULT]]
;
; CHECK-TF-LABEL: define i32 @alias_mask_multiple_read_after_write(
; CHECK-TF-SAME: ptr [[A:%.*]], ptr [[B:%.*]], ptr [[C:%.*]], i64 [[N:%.*]]) #[[ATTR0]] {
; CHECK-TF-NEXT:  entry:
; CHECK-TF-NEXT:    [[CMP19:%.*]] = icmp sgt i64 [[N]], 0
; CHECK-TF-NEXT:    br i1 [[CMP19]], label [[FOR_BODY_PREHEADER:%.*]], label [[EXIT:%.*]]
; CHECK-TF:       for.body.preheader:
; CHECK-TF-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK-TF:       for.body:
; CHECK-TF-NEXT:    [[INDEX:%.*]] = phi i64 [ [[IV_NEXT:%.*]], [[VECTOR_BODY]] ], [ 0, [[FOR_BODY_PREHEADER]] ]
; CHECK-TF-NEXT:    [[ACCUM:%.*]] = phi i32 [ [[SDIV:%.*]], [[VECTOR_BODY]] ], [ 0, [[FOR_BODY_PREHEADER]] ]
; CHECK-TF-NEXT:    [[TMP18:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[INDEX]]
; CHECK-TF-NEXT:    [[LOAD_A:%.*]] = load i32, ptr [[TMP18]], align 2
; CHECK-TF-NEXT:    [[TMP19:%.*]] = getelementptr inbounds i32, ptr [[C]], i64 [[INDEX]]
; CHECK-TF-NEXT:    store i32 [[LOAD_A]], ptr [[TMP19]], align 2
; CHECK-TF-NEXT:    [[TMP20:%.*]] = getelementptr inbounds i32, ptr [[B]], i64 [[INDEX]]
; CHECK-TF-NEXT:    [[LOAD_B:%.*]] = load i32, ptr [[TMP20]], align 2
; CHECK-TF-NEXT:    [[ADD:%.*]] = add i32 [[LOAD_A]], [[ACCUM]]
; CHECK-TF-NEXT:    [[SDIV]] = sdiv i32 [[ADD]], [[LOAD_B]]
; CHECK-TF-NEXT:    [[IV_NEXT]] = add nuw nsw i64 [[INDEX]], 1
; CHECK-TF-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[IV_NEXT]], [[N]]
; CHECK-TF-NEXT:    br i1 [[EXITCOND_NOT]], label [[EXIT_LOOPEXIT:%.*]], label [[VECTOR_BODY]]
; CHECK-TF:       exit.loopexit:
; CHECK-TF-NEXT:    [[SDIV_LCSSA:%.*]] = phi i32 [ [[SDIV]], [[VECTOR_BODY]] ]
; CHECK-TF-NEXT:    br label [[EXIT]]
; CHECK-TF:       exit:
; CHECK-TF-NEXT:    [[RESULT:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[SDIV_LCSSA]], [[EXIT_LOOPEXIT]] ]
; CHECK-TF-NEXT:    ret i32 [[RESULT]]
;
entry:
  %cmp19 = icmp sgt i64 %n, 0
  br i1 %cmp19, label %for.body, label %exit

for.body:                                         ; preds = %entry, %for.body
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %for.body ]
  %accum = phi i32 [ 0, %entry ], [ %sdiv, %for.body ]
  %gep.a = getelementptr inbounds i32, ptr %a, i64 %iv
  %load.a = load i32, ptr %gep.a, align 2
  %gep.c = getelementptr inbounds i32, ptr %c, i64 %iv
  store i32 %load.a, ptr %gep.c, align 2
  %gep.b = getelementptr inbounds i32, ptr %b, i64 %iv
  %load.b = load i32, ptr %gep.b, align 2
  %add = add i32 %load.a, %accum
  %sdiv = sdiv i32 %add, %load.b
  %iv.next = add nuw nsw i64 %iv, 1
  %exitcond.not = icmp eq i64 %iv.next, %n
  br i1 %exitcond.not, label %exit, label %for.body

exit:                        ; preds = %entry, %for.body
  %result = phi i32 [ 0, %entry ], [ %sdiv, %for.body ]
  ret i32 %result
}
;.
; CHECK: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]], [[META2:![0-9]+]]}
; CHECK: [[META1]] = !{!"llvm.loop.isvectorized", i32 1}
; CHECK: [[META2]] = !{!"llvm.loop.unroll.runtime.disable"}
; CHECK: [[LOOP4]] = distinct !{[[LOOP4]], [[META1]], [[META2]]}
; CHECK: [[LOOP6]] = distinct !{[[LOOP6]], [[META1]], [[META2]]}
;.
; CHECK-TF: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]], [[META2:![0-9]+]]}
; CHECK-TF: [[META1]] = !{!"llvm.loop.isvectorized", i32 1}
; CHECK-TF: [[META2]] = !{!"llvm.loop.unroll.runtime.disable"}
; CHECK-TF: [[LOOP4]] = distinct !{[[LOOP4]], [[META1]], [[META2]]}
; CHECK-TF: [[LOOP6]] = distinct !{[[LOOP6]], [[META1]], [[META2]]}
;.
