; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals none --filter-out-after "^middle.block:" --version 6
; RUN: opt -S -passes=loop-vectorize -mtriple=aarch64-linux-gnu -mattr=+sve2p1 -force-vector-interleave=2 -tail-folding-policy=must-fold-tail -force-wide-mem-ops %s | FileCheck %s --check-prefix=MASKED-SVE2P1
; RUN: opt -S -passes=loop-vectorize -mtriple=aarch64-linux-gnu -mattr=+sve -force-vector-interleave=2 -tail-folding-policy=must-fold-tail -force-wide-mem-ops %s | FileCheck %s --check-prefix=MASKED-SVE
; RUN: opt -S -passes=loop-vectorize -mtriple=aarch64-linux-gnu -mattr=+sve2p1 -force-vector-interleave=2 -sve-tail-folding=disabled -force-wide-mem-ops %s | FileCheck %s --check-prefix=UNMASKED-SVE2P1
; RUN: opt -S -passes=loop-vectorize -mtriple=aarch64-linux-gnu -mattr=+sve -force-vector-interleave=2 -sve-tail-folding=disabled -force-wide-mem-ops %s | FileCheck %s --check-prefix=UNMASKED-SVE

target triple = "aarch64-unknown-linux-gnu"

; Equal-count i64/i32 accesses. Under the masked RUN lines, the scalable path
; must pick the larger access size when the access sizes tie.
; Under the UNMASKED RUN lines, both the i32 and i64 accesses can be scaled.
define void @mixed_i64_i32_tiebreak_prefers_larger_access(
; MASKED-SVE2P1-LABEL: define void @mixed_i64_i32_tiebreak_prefers_larger_access(
; MASKED-SVE2P1-SAME: ptr noalias [[X:%.*]], ptr noalias [[Y:%.*]], i64 [[N:%.*]]) #[[ATTR0:[0-9]+]] {
; MASKED-SVE2P1-NEXT:  [[ENTRY:.*:]]
; MASKED-SVE2P1-NEXT:    [[UMAX:%.*]] = call i64 @llvm.umax.i64(i64 [[N]], i64 1)
; MASKED-SVE2P1-NEXT:    br label %[[VECTOR_PH:.*]]
; MASKED-SVE2P1:       [[VECTOR_PH]]:
; MASKED-SVE2P1-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; MASKED-SVE2P1-NEXT:    [[TMP1:%.*]] = shl nuw i64 [[TMP0]], 2
; MASKED-SVE2P1-NEXT:    [[TMP2:%.*]] = shl nuw i64 [[TMP1]], 1
; MASKED-SVE2P1-NEXT:    [[ACTIVE_LANE_MASK_ENTRY:%.*]] = call <vscale x 8 x i1> @llvm.get.active.lane.mask.for.type.nxv8i1.i64(i64 0, i64 [[UMAX]], i64 8)
; MASKED-SVE2P1-NEXT:    br label %[[VECTOR_BODY:.*]]
; MASKED-SVE2P1:       [[VECTOR_BODY]]:
; MASKED-SVE2P1-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; MASKED-SVE2P1-NEXT:    [[ACTIVE_LANE_MASK:%.*]] = phi <vscale x 8 x i1> [ [[ACTIVE_LANE_MASK_ENTRY]], %[[VECTOR_PH]] ], [ [[ACTIVE_LANE_MASK_NEXT:%.*]], %[[VECTOR_BODY]] ]
; MASKED-SVE2P1-NEXT:    [[TMP3:%.*]] = call <vscale x 4 x i1> @llvm.vector.extract.nxv4i1.nxv8i1(<vscale x 8 x i1> [[ACTIVE_LANE_MASK]], i64 0)
; MASKED-SVE2P1-NEXT:    [[TMP4:%.*]] = call <vscale x 4 x i1> @llvm.vector.extract.nxv4i1.nxv8i1(<vscale x 8 x i1> [[ACTIVE_LANE_MASK]], i64 4)
; MASKED-SVE2P1-NEXT:    [[TMP5:%.*]] = getelementptr inbounds i64, ptr [[X]], i64 [[INDEX]]
; MASKED-SVE2P1-NEXT:    [[WIDE_MASKED_LOAD:%.*]] = call <vscale x 8 x i64> @llvm.masked.load.nxv8i64.p0(ptr align 8 [[TMP5]], <vscale x 8 x i1> [[ACTIVE_LANE_MASK]], <vscale x 8 x i64> poison)
; MASKED-SVE2P1-NEXT:    [[TMP6:%.*]] = call <vscale x 4 x i64> @llvm.vector.extract.nxv4i64.nxv8i64(<vscale x 8 x i64> [[WIDE_MASKED_LOAD]], i64 0)
; MASKED-SVE2P1-NEXT:    [[TMP7:%.*]] = call <vscale x 4 x i64> @llvm.vector.extract.nxv4i64.nxv8i64(<vscale x 8 x i64> [[WIDE_MASKED_LOAD]], i64 4)
; MASKED-SVE2P1-NEXT:    [[TMP8:%.*]] = add <vscale x 4 x i64> [[TMP6]], splat (i64 1)
; MASKED-SVE2P1-NEXT:    [[TMP9:%.*]] = add <vscale x 4 x i64> [[TMP7]], splat (i64 1)
; MASKED-SVE2P1-NEXT:    [[TMP10:%.*]] = call <vscale x 8 x i64> @llvm.vector.insert.nxv8i64.nxv4i64(<vscale x 8 x i64> poison, <vscale x 4 x i64> [[TMP8]], i64 0)
; MASKED-SVE2P1-NEXT:    [[TMP11:%.*]] = call <vscale x 8 x i64> @llvm.vector.insert.nxv8i64.nxv4i64(<vscale x 8 x i64> [[TMP10]], <vscale x 4 x i64> [[TMP9]], i64 4)
; MASKED-SVE2P1-NEXT:    call void @llvm.masked.store.nxv8i64.p0(<vscale x 8 x i64> [[TMP11]], ptr align 8 [[TMP5]], <vscale x 8 x i1> [[ACTIVE_LANE_MASK]])
; MASKED-SVE2P1-NEXT:    [[TMP12:%.*]] = getelementptr inbounds i32, ptr [[Y]], i64 [[INDEX]]
; MASKED-SVE2P1-NEXT:    [[TMP13:%.*]] = getelementptr inbounds i32, ptr [[TMP12]], i64 [[TMP1]]
; MASKED-SVE2P1-NEXT:    [[WIDE_MASKED_LOAD1:%.*]] = call <vscale x 4 x i32> @llvm.masked.load.nxv4i32.p0(ptr align 4 [[TMP12]], <vscale x 4 x i1> [[TMP3]], <vscale x 4 x i32> poison)
; MASKED-SVE2P1-NEXT:    [[WIDE_MASKED_LOAD2:%.*]] = call <vscale x 4 x i32> @llvm.masked.load.nxv4i32.p0(ptr align 4 [[TMP13]], <vscale x 4 x i1> [[TMP4]], <vscale x 4 x i32> poison)
; MASKED-SVE2P1-NEXT:    [[TMP14:%.*]] = add <vscale x 4 x i32> [[WIDE_MASKED_LOAD1]], splat (i32 1)
; MASKED-SVE2P1-NEXT:    [[TMP15:%.*]] = add <vscale x 4 x i32> [[WIDE_MASKED_LOAD2]], splat (i32 1)
; MASKED-SVE2P1-NEXT:    call void @llvm.masked.store.nxv4i32.p0(<vscale x 4 x i32> [[TMP14]], ptr align 4 [[TMP12]], <vscale x 4 x i1> [[TMP3]])
; MASKED-SVE2P1-NEXT:    call void @llvm.masked.store.nxv4i32.p0(<vscale x 4 x i32> [[TMP15]], ptr align 4 [[TMP13]], <vscale x 4 x i1> [[TMP4]])
; MASKED-SVE2P1-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], [[TMP2]]
; MASKED-SVE2P1-NEXT:    [[ACTIVE_LANE_MASK_NEXT]] = call <vscale x 8 x i1> @llvm.get.active.lane.mask.for.type.nxv8i1.i64(i64 [[INDEX_NEXT]], i64 [[UMAX]], i64 8)
; MASKED-SVE2P1-NEXT:    [[TMP16:%.*]] = extractelement <vscale x 8 x i1> [[ACTIVE_LANE_MASK_NEXT]], i64 0
; MASKED-SVE2P1-NEXT:    [[TMP17:%.*]] = xor i1 [[TMP16]], true
; MASKED-SVE2P1-NEXT:    br i1 [[TMP17]], label %[[EXIT:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; MASKED-SVE2P1:       [[EXIT]]:
;
; MASKED-SVE-LABEL: define void @mixed_i64_i32_tiebreak_prefers_larger_access(
; MASKED-SVE-SAME: ptr noalias [[X:%.*]], ptr noalias [[Y:%.*]], i64 [[N:%.*]]) #[[ATTR0:[0-9]+]] {
; MASKED-SVE-NEXT:  [[ENTRY:.*:]]
; MASKED-SVE-NEXT:    [[UMAX:%.*]] = call i64 @llvm.umax.i64(i64 [[N]], i64 1)
; MASKED-SVE-NEXT:    br label %[[VECTOR_PH:.*]]
; MASKED-SVE:       [[VECTOR_PH]]:
; MASKED-SVE-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; MASKED-SVE-NEXT:    [[TMP1:%.*]] = shl nuw i64 [[TMP0]], 2
; MASKED-SVE-NEXT:    [[TMP2:%.*]] = shl nuw i64 [[TMP1]], 1
; MASKED-SVE-NEXT:    [[ACTIVE_LANE_MASK_ENTRY:%.*]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 0, i64 [[UMAX]])
; MASKED-SVE-NEXT:    [[ACTIVE_LANE_MASK_ENTRY1:%.*]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 [[TMP1]], i64 [[UMAX]])
; MASKED-SVE-NEXT:    br label %[[VECTOR_BODY:.*]]
; MASKED-SVE:       [[VECTOR_BODY]]:
; MASKED-SVE-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; MASKED-SVE-NEXT:    [[ACTIVE_LANE_MASK:%.*]] = phi <vscale x 4 x i1> [ [[ACTIVE_LANE_MASK_ENTRY]], %[[VECTOR_PH]] ], [ [[ACTIVE_LANE_MASK_NEXT:%.*]], %[[VECTOR_BODY]] ]
; MASKED-SVE-NEXT:    [[ACTIVE_LANE_MASK2:%.*]] = phi <vscale x 4 x i1> [ [[ACTIVE_LANE_MASK_ENTRY1]], %[[VECTOR_PH]] ], [ [[ACTIVE_LANE_MASK_NEXT6:%.*]], %[[VECTOR_BODY]] ]
; MASKED-SVE-NEXT:    [[TMP3:%.*]] = getelementptr inbounds i64, ptr [[X]], i64 [[INDEX]]
; MASKED-SVE-NEXT:    [[TMP4:%.*]] = getelementptr inbounds i64, ptr [[TMP3]], i64 [[TMP1]]
; MASKED-SVE-NEXT:    [[WIDE_MASKED_LOAD:%.*]] = call <vscale x 4 x i64> @llvm.masked.load.nxv4i64.p0(ptr align 8 [[TMP3]], <vscale x 4 x i1> [[ACTIVE_LANE_MASK]], <vscale x 4 x i64> poison)
; MASKED-SVE-NEXT:    [[WIDE_MASKED_LOAD3:%.*]] = call <vscale x 4 x i64> @llvm.masked.load.nxv4i64.p0(ptr align 8 [[TMP4]], <vscale x 4 x i1> [[ACTIVE_LANE_MASK2]], <vscale x 4 x i64> poison)
; MASKED-SVE-NEXT:    [[TMP5:%.*]] = add <vscale x 4 x i64> [[WIDE_MASKED_LOAD]], splat (i64 1)
; MASKED-SVE-NEXT:    [[TMP6:%.*]] = add <vscale x 4 x i64> [[WIDE_MASKED_LOAD3]], splat (i64 1)
; MASKED-SVE-NEXT:    call void @llvm.masked.store.nxv4i64.p0(<vscale x 4 x i64> [[TMP5]], ptr align 8 [[TMP3]], <vscale x 4 x i1> [[ACTIVE_LANE_MASK]])
; MASKED-SVE-NEXT:    call void @llvm.masked.store.nxv4i64.p0(<vscale x 4 x i64> [[TMP6]], ptr align 8 [[TMP4]], <vscale x 4 x i1> [[ACTIVE_LANE_MASK2]])
; MASKED-SVE-NEXT:    [[TMP7:%.*]] = getelementptr inbounds i32, ptr [[Y]], i64 [[INDEX]]
; MASKED-SVE-NEXT:    [[TMP8:%.*]] = getelementptr inbounds i32, ptr [[TMP7]], i64 [[TMP1]]
; MASKED-SVE-NEXT:    [[WIDE_MASKED_LOAD4:%.*]] = call <vscale x 4 x i32> @llvm.masked.load.nxv4i32.p0(ptr align 4 [[TMP7]], <vscale x 4 x i1> [[ACTIVE_LANE_MASK]], <vscale x 4 x i32> poison)
; MASKED-SVE-NEXT:    [[WIDE_MASKED_LOAD5:%.*]] = call <vscale x 4 x i32> @llvm.masked.load.nxv4i32.p0(ptr align 4 [[TMP8]], <vscale x 4 x i1> [[ACTIVE_LANE_MASK2]], <vscale x 4 x i32> poison)
; MASKED-SVE-NEXT:    [[TMP9:%.*]] = add <vscale x 4 x i32> [[WIDE_MASKED_LOAD4]], splat (i32 1)
; MASKED-SVE-NEXT:    [[TMP10:%.*]] = add <vscale x 4 x i32> [[WIDE_MASKED_LOAD5]], splat (i32 1)
; MASKED-SVE-NEXT:    call void @llvm.masked.store.nxv4i32.p0(<vscale x 4 x i32> [[TMP9]], ptr align 4 [[TMP7]], <vscale x 4 x i1> [[ACTIVE_LANE_MASK]])
; MASKED-SVE-NEXT:    call void @llvm.masked.store.nxv4i32.p0(<vscale x 4 x i32> [[TMP10]], ptr align 4 [[TMP8]], <vscale x 4 x i1> [[ACTIVE_LANE_MASK2]])
; MASKED-SVE-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], [[TMP2]]
; MASKED-SVE-NEXT:    [[TMP11:%.*]] = add i64 [[INDEX_NEXT]], [[TMP1]]
; MASKED-SVE-NEXT:    [[ACTIVE_LANE_MASK_NEXT]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 [[INDEX_NEXT]], i64 [[UMAX]])
; MASKED-SVE-NEXT:    [[ACTIVE_LANE_MASK_NEXT6]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 [[TMP11]], i64 [[UMAX]])
; MASKED-SVE-NEXT:    [[TMP12:%.*]] = extractelement <vscale x 4 x i1> [[ACTIVE_LANE_MASK_NEXT]], i64 0
; MASKED-SVE-NEXT:    [[TMP13:%.*]] = xor i1 [[TMP12]], true
; MASKED-SVE-NEXT:    br i1 [[TMP13]], label %[[EXIT:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; MASKED-SVE:       [[EXIT]]:
;
; UNMASKED-SVE2P1-LABEL: define void @mixed_i64_i32_tiebreak_prefers_larger_access(
; UNMASKED-SVE2P1-SAME: ptr noalias [[X:%.*]], ptr noalias [[Y:%.*]], i64 [[N:%.*]]) #[[ATTR0:[0-9]+]] {
; UNMASKED-SVE2P1-NEXT:  [[ENTRY:.*:]]
; UNMASKED-SVE2P1-NEXT:    [[UMAX:%.*]] = call i64 @llvm.umax.i64(i64 [[N]], i64 1)
; UNMASKED-SVE2P1-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; UNMASKED-SVE2P1-NEXT:    [[TMP1:%.*]] = shl nuw i64 [[TMP0]], 3
; UNMASKED-SVE2P1-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 [[UMAX]], [[TMP1]]
; UNMASKED-SVE2P1-NEXT:    br i1 [[MIN_ITERS_CHECK]], [[SCALAR_PH:label %.*]], label %[[VECTOR_PH:.*]]
; UNMASKED-SVE2P1:       [[VECTOR_PH]]:
; UNMASKED-SVE2P1-NEXT:    [[TMP2:%.*]] = shl nuw i64 [[TMP0]], 2
; UNMASKED-SVE2P1-NEXT:    [[TMP3:%.*]] = shl nuw i64 [[TMP2]], 1
; UNMASKED-SVE2P1-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[UMAX]], [[TMP3]]
; UNMASKED-SVE2P1-NEXT:    [[N_VEC:%.*]] = sub i64 [[UMAX]], [[N_MOD_VF]]
; UNMASKED-SVE2P1-NEXT:    br label %[[VECTOR_BODY:.*]]
; UNMASKED-SVE2P1:       [[VECTOR_BODY]]:
; UNMASKED-SVE2P1-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; UNMASKED-SVE2P1-NEXT:    [[TMP4:%.*]] = getelementptr inbounds i64, ptr [[X]], i64 [[INDEX]]
; UNMASKED-SVE2P1-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 8 x i64>, ptr [[TMP4]], align 8
; UNMASKED-SVE2P1-NEXT:    [[TMP5:%.*]] = call <vscale x 4 x i64> @llvm.vector.extract.nxv4i64.nxv8i64(<vscale x 8 x i64> [[WIDE_LOAD]], i64 0)
; UNMASKED-SVE2P1-NEXT:    [[TMP6:%.*]] = call <vscale x 4 x i64> @llvm.vector.extract.nxv4i64.nxv8i64(<vscale x 8 x i64> [[WIDE_LOAD]], i64 4)
; UNMASKED-SVE2P1-NEXT:    [[TMP7:%.*]] = add <vscale x 4 x i64> [[TMP5]], splat (i64 1)
; UNMASKED-SVE2P1-NEXT:    [[TMP8:%.*]] = add <vscale x 4 x i64> [[TMP6]], splat (i64 1)
; UNMASKED-SVE2P1-NEXT:    [[TMP9:%.*]] = getelementptr inbounds i64, ptr [[TMP4]], i64 [[TMP2]]
; UNMASKED-SVE2P1-NEXT:    store <vscale x 4 x i64> [[TMP7]], ptr [[TMP4]], align 8
; UNMASKED-SVE2P1-NEXT:    store <vscale x 4 x i64> [[TMP8]], ptr [[TMP9]], align 8
; UNMASKED-SVE2P1-NEXT:    [[TMP10:%.*]] = getelementptr inbounds i32, ptr [[Y]], i64 [[INDEX]]
; UNMASKED-SVE2P1-NEXT:    [[WIDE_LOAD1:%.*]] = load <vscale x 8 x i32>, ptr [[TMP10]], align 4
; UNMASKED-SVE2P1-NEXT:    [[TMP11:%.*]] = call <vscale x 4 x i32> @llvm.vector.extract.nxv4i32.nxv8i32(<vscale x 8 x i32> [[WIDE_LOAD1]], i64 0)
; UNMASKED-SVE2P1-NEXT:    [[TMP12:%.*]] = call <vscale x 4 x i32> @llvm.vector.extract.nxv4i32.nxv8i32(<vscale x 8 x i32> [[WIDE_LOAD1]], i64 4)
; UNMASKED-SVE2P1-NEXT:    [[TMP13:%.*]] = add <vscale x 4 x i32> [[TMP11]], splat (i32 1)
; UNMASKED-SVE2P1-NEXT:    [[TMP14:%.*]] = add <vscale x 4 x i32> [[TMP12]], splat (i32 1)
; UNMASKED-SVE2P1-NEXT:    [[TMP15:%.*]] = getelementptr inbounds i32, ptr [[TMP10]], i64 [[TMP2]]
; UNMASKED-SVE2P1-NEXT:    store <vscale x 4 x i32> [[TMP13]], ptr [[TMP10]], align 4
; UNMASKED-SVE2P1-NEXT:    store <vscale x 4 x i32> [[TMP14]], ptr [[TMP15]], align 4
; UNMASKED-SVE2P1-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP3]]
; UNMASKED-SVE2P1-NEXT:    [[TMP16:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; UNMASKED-SVE2P1-NEXT:    br i1 [[TMP16]], label %[[EXIT:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; UNMASKED-SVE2P1:       [[EXIT]]:
;
; UNMASKED-SVE-LABEL: define void @mixed_i64_i32_tiebreak_prefers_larger_access(
; UNMASKED-SVE-SAME: ptr noalias [[X:%.*]], ptr noalias [[Y:%.*]], i64 [[N:%.*]]) #[[ATTR0:[0-9]+]] {
; UNMASKED-SVE-NEXT:  [[ENTRY:.*:]]
; UNMASKED-SVE-NEXT:    [[UMAX:%.*]] = call i64 @llvm.umax.i64(i64 [[N]], i64 1)
; UNMASKED-SVE-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; UNMASKED-SVE-NEXT:    [[TMP1:%.*]] = shl nuw i64 [[TMP0]], 3
; UNMASKED-SVE-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 [[UMAX]], [[TMP1]]
; UNMASKED-SVE-NEXT:    br i1 [[MIN_ITERS_CHECK]], [[SCALAR_PH:label %.*]], label %[[VECTOR_PH:.*]]
; UNMASKED-SVE:       [[VECTOR_PH]]:
; UNMASKED-SVE-NEXT:    [[TMP2:%.*]] = shl nuw i64 [[TMP0]], 2
; UNMASKED-SVE-NEXT:    [[TMP3:%.*]] = shl nuw i64 [[TMP2]], 1
; UNMASKED-SVE-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[UMAX]], [[TMP3]]
; UNMASKED-SVE-NEXT:    [[N_VEC:%.*]] = sub i64 [[UMAX]], [[N_MOD_VF]]
; UNMASKED-SVE-NEXT:    br label %[[VECTOR_BODY:.*]]
; UNMASKED-SVE:       [[VECTOR_BODY]]:
; UNMASKED-SVE-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; UNMASKED-SVE-NEXT:    [[TMP4:%.*]] = getelementptr inbounds i64, ptr [[X]], i64 [[INDEX]]
; UNMASKED-SVE-NEXT:    [[TMP5:%.*]] = getelementptr inbounds i64, ptr [[TMP4]], i64 [[TMP2]]
; UNMASKED-SVE-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 4 x i64>, ptr [[TMP4]], align 8
; UNMASKED-SVE-NEXT:    [[WIDE_LOAD1:%.*]] = load <vscale x 4 x i64>, ptr [[TMP5]], align 8
; UNMASKED-SVE-NEXT:    [[TMP6:%.*]] = add <vscale x 4 x i64> [[WIDE_LOAD]], splat (i64 1)
; UNMASKED-SVE-NEXT:    [[TMP7:%.*]] = add <vscale x 4 x i64> [[WIDE_LOAD1]], splat (i64 1)
; UNMASKED-SVE-NEXT:    store <vscale x 4 x i64> [[TMP6]], ptr [[TMP4]], align 8
; UNMASKED-SVE-NEXT:    store <vscale x 4 x i64> [[TMP7]], ptr [[TMP5]], align 8
; UNMASKED-SVE-NEXT:    [[TMP8:%.*]] = getelementptr inbounds i32, ptr [[Y]], i64 [[INDEX]]
; UNMASKED-SVE-NEXT:    [[TMP9:%.*]] = getelementptr inbounds i32, ptr [[TMP8]], i64 [[TMP2]]
; UNMASKED-SVE-NEXT:    [[WIDE_LOAD2:%.*]] = load <vscale x 4 x i32>, ptr [[TMP8]], align 4
; UNMASKED-SVE-NEXT:    [[WIDE_LOAD3:%.*]] = load <vscale x 4 x i32>, ptr [[TMP9]], align 4
; UNMASKED-SVE-NEXT:    [[TMP10:%.*]] = add <vscale x 4 x i32> [[WIDE_LOAD2]], splat (i32 1)
; UNMASKED-SVE-NEXT:    [[TMP11:%.*]] = add <vscale x 4 x i32> [[WIDE_LOAD3]], splat (i32 1)
; UNMASKED-SVE-NEXT:    store <vscale x 4 x i32> [[TMP10]], ptr [[TMP8]], align 4
; UNMASKED-SVE-NEXT:    store <vscale x 4 x i32> [[TMP11]], ptr [[TMP9]], align 4
; UNMASKED-SVE-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP3]]
; UNMASKED-SVE-NEXT:    [[TMP12:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; UNMASKED-SVE-NEXT:    br i1 [[TMP12]], label %[[EXIT:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; UNMASKED-SVE:       [[EXIT]]:
;
  ptr noalias %x, ptr noalias %y, i64 %n) {
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %next, %loop ]
  %px = getelementptr inbounds i64, ptr %x, i64 %iv
  %vx = load i64, ptr %px, align 8
  %ax = add i64 %vx, 1
  store i64 %ax, ptr %px, align 8
  %py = getelementptr inbounds i32, ptr %y, i64 %iv
  %vy = load i32, ptr %py, align 4
  %ay = add i32 %vy, 1
  store i32 %ay, ptr %py, align 4
  %next = add nuw i64 %iv, 1
  %cmp = icmp ult i64 %next, %n
  br i1 %cmp, label %loop, label %exit, !llvm.loop !0

exit:
  ret void
}

; There are more i32 accesses than i64 accesses, so the masked scalable path
; should choose to mask the i32 accesses.
define void @mixed_i32_more_frequent_than_i64(
; MASKED-SVE2P1-LABEL: define void @mixed_i32_more_frequent_than_i64(
; MASKED-SVE2P1-SAME: ptr noalias [[X:%.*]], ptr noalias [[Y:%.*]], ptr noalias [[Z:%.*]], i64 [[N:%.*]]) #[[ATTR0]] {
; MASKED-SVE2P1-NEXT:  [[ENTRY:.*:]]
; MASKED-SVE2P1-NEXT:    [[UMAX:%.*]] = call i64 @llvm.umax.i64(i64 [[N]], i64 1)
; MASKED-SVE2P1-NEXT:    br label %[[VECTOR_PH:.*]]
; MASKED-SVE2P1:       [[VECTOR_PH]]:
; MASKED-SVE2P1-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; MASKED-SVE2P1-NEXT:    [[TMP1:%.*]] = shl nuw i64 [[TMP0]], 2
; MASKED-SVE2P1-NEXT:    [[TMP2:%.*]] = shl nuw i64 [[TMP1]], 1
; MASKED-SVE2P1-NEXT:    [[ACTIVE_LANE_MASK_ENTRY:%.*]] = call <vscale x 8 x i1> @llvm.get.active.lane.mask.for.type.nxv8i1.i64(i64 0, i64 [[UMAX]], i64 4)
; MASKED-SVE2P1-NEXT:    br label %[[VECTOR_BODY:.*]]
; MASKED-SVE2P1:       [[VECTOR_BODY]]:
; MASKED-SVE2P1-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; MASKED-SVE2P1-NEXT:    [[ACTIVE_LANE_MASK:%.*]] = phi <vscale x 8 x i1> [ [[ACTIVE_LANE_MASK_ENTRY]], %[[VECTOR_PH]] ], [ [[ACTIVE_LANE_MASK_NEXT:%.*]], %[[VECTOR_BODY]] ]
; MASKED-SVE2P1-NEXT:    [[TMP3:%.*]] = call <vscale x 4 x i1> @llvm.vector.extract.nxv4i1.nxv8i1(<vscale x 8 x i1> [[ACTIVE_LANE_MASK]], i64 0)
; MASKED-SVE2P1-NEXT:    [[TMP4:%.*]] = call <vscale x 4 x i1> @llvm.vector.extract.nxv4i1.nxv8i1(<vscale x 8 x i1> [[ACTIVE_LANE_MASK]], i64 4)
; MASKED-SVE2P1-NEXT:    [[TMP5:%.*]] = getelementptr inbounds i64, ptr [[X]], i64 [[INDEX]]
; MASKED-SVE2P1-NEXT:    [[TMP6:%.*]] = getelementptr inbounds i64, ptr [[TMP5]], i64 [[TMP1]]
; MASKED-SVE2P1-NEXT:    [[WIDE_MASKED_LOAD:%.*]] = call <vscale x 4 x i64> @llvm.masked.load.nxv4i64.p0(ptr align 8 [[TMP5]], <vscale x 4 x i1> [[TMP3]], <vscale x 4 x i64> poison)
; MASKED-SVE2P1-NEXT:    [[WIDE_MASKED_LOAD1:%.*]] = call <vscale x 4 x i64> @llvm.masked.load.nxv4i64.p0(ptr align 8 [[TMP6]], <vscale x 4 x i1> [[TMP4]], <vscale x 4 x i64> poison)
; MASKED-SVE2P1-NEXT:    [[TMP7:%.*]] = add <vscale x 4 x i64> [[WIDE_MASKED_LOAD]], splat (i64 1)
; MASKED-SVE2P1-NEXT:    [[TMP8:%.*]] = add <vscale x 4 x i64> [[WIDE_MASKED_LOAD1]], splat (i64 1)
; MASKED-SVE2P1-NEXT:    call void @llvm.masked.store.nxv4i64.p0(<vscale x 4 x i64> [[TMP7]], ptr align 8 [[TMP5]], <vscale x 4 x i1> [[TMP3]])
; MASKED-SVE2P1-NEXT:    call void @llvm.masked.store.nxv4i64.p0(<vscale x 4 x i64> [[TMP8]], ptr align 8 [[TMP6]], <vscale x 4 x i1> [[TMP4]])
; MASKED-SVE2P1-NEXT:    [[TMP9:%.*]] = getelementptr inbounds i32, ptr [[Y]], i64 [[INDEX]]
; MASKED-SVE2P1-NEXT:    [[WIDE_MASKED_LOAD2:%.*]] = call <vscale x 8 x i32> @llvm.masked.load.nxv8i32.p0(ptr align 4 [[TMP9]], <vscale x 8 x i1> [[ACTIVE_LANE_MASK]], <vscale x 8 x i32> poison)
; MASKED-SVE2P1-NEXT:    [[TMP10:%.*]] = call <vscale x 4 x i32> @llvm.vector.extract.nxv4i32.nxv8i32(<vscale x 8 x i32> [[WIDE_MASKED_LOAD2]], i64 0)
; MASKED-SVE2P1-NEXT:    [[TMP11:%.*]] = call <vscale x 4 x i32> @llvm.vector.extract.nxv4i32.nxv8i32(<vscale x 8 x i32> [[WIDE_MASKED_LOAD2]], i64 4)
; MASKED-SVE2P1-NEXT:    [[TMP12:%.*]] = add <vscale x 4 x i32> [[TMP10]], splat (i32 1)
; MASKED-SVE2P1-NEXT:    [[TMP13:%.*]] = add <vscale x 4 x i32> [[TMP11]], splat (i32 1)
; MASKED-SVE2P1-NEXT:    [[TMP14:%.*]] = call <vscale x 8 x i32> @llvm.vector.insert.nxv8i32.nxv4i32(<vscale x 8 x i32> poison, <vscale x 4 x i32> [[TMP12]], i64 0)
; MASKED-SVE2P1-NEXT:    [[TMP15:%.*]] = call <vscale x 8 x i32> @llvm.vector.insert.nxv8i32.nxv4i32(<vscale x 8 x i32> [[TMP14]], <vscale x 4 x i32> [[TMP13]], i64 4)
; MASKED-SVE2P1-NEXT:    call void @llvm.masked.store.nxv8i32.p0(<vscale x 8 x i32> [[TMP15]], ptr align 4 [[TMP9]], <vscale x 8 x i1> [[ACTIVE_LANE_MASK]])
; MASKED-SVE2P1-NEXT:    [[TMP16:%.*]] = getelementptr inbounds i32, ptr [[Z]], i64 [[INDEX]]
; MASKED-SVE2P1-NEXT:    [[WIDE_MASKED_LOAD3:%.*]] = call <vscale x 8 x i32> @llvm.masked.load.nxv8i32.p0(ptr align 4 [[TMP16]], <vscale x 8 x i1> [[ACTIVE_LANE_MASK]], <vscale x 8 x i32> poison)
; MASKED-SVE2P1-NEXT:    [[TMP17:%.*]] = call <vscale x 4 x i32> @llvm.vector.extract.nxv4i32.nxv8i32(<vscale x 8 x i32> [[WIDE_MASKED_LOAD3]], i64 0)
; MASKED-SVE2P1-NEXT:    [[TMP18:%.*]] = call <vscale x 4 x i32> @llvm.vector.extract.nxv4i32.nxv8i32(<vscale x 8 x i32> [[WIDE_MASKED_LOAD3]], i64 4)
; MASKED-SVE2P1-NEXT:    [[TMP19:%.*]] = add <vscale x 4 x i32> [[TMP17]], splat (i32 2)
; MASKED-SVE2P1-NEXT:    [[TMP20:%.*]] = add <vscale x 4 x i32> [[TMP18]], splat (i32 2)
; MASKED-SVE2P1-NEXT:    [[TMP21:%.*]] = call <vscale x 8 x i32> @llvm.vector.insert.nxv8i32.nxv4i32(<vscale x 8 x i32> poison, <vscale x 4 x i32> [[TMP19]], i64 0)
; MASKED-SVE2P1-NEXT:    [[TMP22:%.*]] = call <vscale x 8 x i32> @llvm.vector.insert.nxv8i32.nxv4i32(<vscale x 8 x i32> [[TMP21]], <vscale x 4 x i32> [[TMP20]], i64 4)
; MASKED-SVE2P1-NEXT:    call void @llvm.masked.store.nxv8i32.p0(<vscale x 8 x i32> [[TMP22]], ptr align 4 [[TMP16]], <vscale x 8 x i1> [[ACTIVE_LANE_MASK]])
; MASKED-SVE2P1-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], [[TMP2]]
; MASKED-SVE2P1-NEXT:    [[ACTIVE_LANE_MASK_NEXT]] = call <vscale x 8 x i1> @llvm.get.active.lane.mask.for.type.nxv8i1.i64(i64 [[INDEX_NEXT]], i64 [[UMAX]], i64 4)
; MASKED-SVE2P1-NEXT:    [[TMP23:%.*]] = extractelement <vscale x 8 x i1> [[ACTIVE_LANE_MASK_NEXT]], i64 0
; MASKED-SVE2P1-NEXT:    [[TMP24:%.*]] = xor i1 [[TMP23]], true
; MASKED-SVE2P1-NEXT:    br i1 [[TMP24]], label %[[EXIT:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP3:![0-9]+]]
; MASKED-SVE2P1:       [[EXIT]]:
;
; MASKED-SVE-LABEL: define void @mixed_i32_more_frequent_than_i64(
; MASKED-SVE-SAME: ptr noalias [[X:%.*]], ptr noalias [[Y:%.*]], ptr noalias [[Z:%.*]], i64 [[N:%.*]]) #[[ATTR0]] {
; MASKED-SVE-NEXT:  [[ENTRY:.*:]]
; MASKED-SVE-NEXT:    [[UMAX:%.*]] = call i64 @llvm.umax.i64(i64 [[N]], i64 1)
; MASKED-SVE-NEXT:    br label %[[VECTOR_PH:.*]]
; MASKED-SVE:       [[VECTOR_PH]]:
; MASKED-SVE-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; MASKED-SVE-NEXT:    [[TMP1:%.*]] = shl nuw i64 [[TMP0]], 2
; MASKED-SVE-NEXT:    [[TMP2:%.*]] = shl nuw i64 [[TMP1]], 1
; MASKED-SVE-NEXT:    [[ACTIVE_LANE_MASK_ENTRY:%.*]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 0, i64 [[UMAX]])
; MASKED-SVE-NEXT:    [[ACTIVE_LANE_MASK_ENTRY1:%.*]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 [[TMP1]], i64 [[UMAX]])
; MASKED-SVE-NEXT:    br label %[[VECTOR_BODY:.*]]
; MASKED-SVE:       [[VECTOR_BODY]]:
; MASKED-SVE-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; MASKED-SVE-NEXT:    [[ACTIVE_LANE_MASK:%.*]] = phi <vscale x 4 x i1> [ [[ACTIVE_LANE_MASK_ENTRY]], %[[VECTOR_PH]] ], [ [[ACTIVE_LANE_MASK_NEXT:%.*]], %[[VECTOR_BODY]] ]
; MASKED-SVE-NEXT:    [[ACTIVE_LANE_MASK2:%.*]] = phi <vscale x 4 x i1> [ [[ACTIVE_LANE_MASK_ENTRY1]], %[[VECTOR_PH]] ], [ [[ACTIVE_LANE_MASK_NEXT8:%.*]], %[[VECTOR_BODY]] ]
; MASKED-SVE-NEXT:    [[TMP3:%.*]] = getelementptr inbounds i64, ptr [[X]], i64 [[INDEX]]
; MASKED-SVE-NEXT:    [[TMP4:%.*]] = getelementptr inbounds i64, ptr [[TMP3]], i64 [[TMP1]]
; MASKED-SVE-NEXT:    [[WIDE_MASKED_LOAD:%.*]] = call <vscale x 4 x i64> @llvm.masked.load.nxv4i64.p0(ptr align 8 [[TMP3]], <vscale x 4 x i1> [[ACTIVE_LANE_MASK]], <vscale x 4 x i64> poison)
; MASKED-SVE-NEXT:    [[WIDE_MASKED_LOAD3:%.*]] = call <vscale x 4 x i64> @llvm.masked.load.nxv4i64.p0(ptr align 8 [[TMP4]], <vscale x 4 x i1> [[ACTIVE_LANE_MASK2]], <vscale x 4 x i64> poison)
; MASKED-SVE-NEXT:    [[TMP5:%.*]] = add <vscale x 4 x i64> [[WIDE_MASKED_LOAD]], splat (i64 1)
; MASKED-SVE-NEXT:    [[TMP6:%.*]] = add <vscale x 4 x i64> [[WIDE_MASKED_LOAD3]], splat (i64 1)
; MASKED-SVE-NEXT:    call void @llvm.masked.store.nxv4i64.p0(<vscale x 4 x i64> [[TMP5]], ptr align 8 [[TMP3]], <vscale x 4 x i1> [[ACTIVE_LANE_MASK]])
; MASKED-SVE-NEXT:    call void @llvm.masked.store.nxv4i64.p0(<vscale x 4 x i64> [[TMP6]], ptr align 8 [[TMP4]], <vscale x 4 x i1> [[ACTIVE_LANE_MASK2]])
; MASKED-SVE-NEXT:    [[TMP7:%.*]] = getelementptr inbounds i32, ptr [[Y]], i64 [[INDEX]]
; MASKED-SVE-NEXT:    [[TMP8:%.*]] = getelementptr inbounds i32, ptr [[TMP7]], i64 [[TMP1]]
; MASKED-SVE-NEXT:    [[WIDE_MASKED_LOAD4:%.*]] = call <vscale x 4 x i32> @llvm.masked.load.nxv4i32.p0(ptr align 4 [[TMP7]], <vscale x 4 x i1> [[ACTIVE_LANE_MASK]], <vscale x 4 x i32> poison)
; MASKED-SVE-NEXT:    [[WIDE_MASKED_LOAD5:%.*]] = call <vscale x 4 x i32> @llvm.masked.load.nxv4i32.p0(ptr align 4 [[TMP8]], <vscale x 4 x i1> [[ACTIVE_LANE_MASK2]], <vscale x 4 x i32> poison)
; MASKED-SVE-NEXT:    [[TMP9:%.*]] = add <vscale x 4 x i32> [[WIDE_MASKED_LOAD4]], splat (i32 1)
; MASKED-SVE-NEXT:    [[TMP10:%.*]] = add <vscale x 4 x i32> [[WIDE_MASKED_LOAD5]], splat (i32 1)
; MASKED-SVE-NEXT:    call void @llvm.masked.store.nxv4i32.p0(<vscale x 4 x i32> [[TMP9]], ptr align 4 [[TMP7]], <vscale x 4 x i1> [[ACTIVE_LANE_MASK]])
; MASKED-SVE-NEXT:    call void @llvm.masked.store.nxv4i32.p0(<vscale x 4 x i32> [[TMP10]], ptr align 4 [[TMP8]], <vscale x 4 x i1> [[ACTIVE_LANE_MASK2]])
; MASKED-SVE-NEXT:    [[TMP11:%.*]] = getelementptr inbounds i32, ptr [[Z]], i64 [[INDEX]]
; MASKED-SVE-NEXT:    [[TMP12:%.*]] = getelementptr inbounds i32, ptr [[TMP11]], i64 [[TMP1]]
; MASKED-SVE-NEXT:    [[WIDE_MASKED_LOAD6:%.*]] = call <vscale x 4 x i32> @llvm.masked.load.nxv4i32.p0(ptr align 4 [[TMP11]], <vscale x 4 x i1> [[ACTIVE_LANE_MASK]], <vscale x 4 x i32> poison)
; MASKED-SVE-NEXT:    [[WIDE_MASKED_LOAD7:%.*]] = call <vscale x 4 x i32> @llvm.masked.load.nxv4i32.p0(ptr align 4 [[TMP12]], <vscale x 4 x i1> [[ACTIVE_LANE_MASK2]], <vscale x 4 x i32> poison)
; MASKED-SVE-NEXT:    [[TMP13:%.*]] = add <vscale x 4 x i32> [[WIDE_MASKED_LOAD6]], splat (i32 2)
; MASKED-SVE-NEXT:    [[TMP14:%.*]] = add <vscale x 4 x i32> [[WIDE_MASKED_LOAD7]], splat (i32 2)
; MASKED-SVE-NEXT:    call void @llvm.masked.store.nxv4i32.p0(<vscale x 4 x i32> [[TMP13]], ptr align 4 [[TMP11]], <vscale x 4 x i1> [[ACTIVE_LANE_MASK]])
; MASKED-SVE-NEXT:    call void @llvm.masked.store.nxv4i32.p0(<vscale x 4 x i32> [[TMP14]], ptr align 4 [[TMP12]], <vscale x 4 x i1> [[ACTIVE_LANE_MASK2]])
; MASKED-SVE-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], [[TMP2]]
; MASKED-SVE-NEXT:    [[TMP15:%.*]] = add i64 [[INDEX_NEXT]], [[TMP1]]
; MASKED-SVE-NEXT:    [[ACTIVE_LANE_MASK_NEXT]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 [[INDEX_NEXT]], i64 [[UMAX]])
; MASKED-SVE-NEXT:    [[ACTIVE_LANE_MASK_NEXT8]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 [[TMP15]], i64 [[UMAX]])
; MASKED-SVE-NEXT:    [[TMP16:%.*]] = extractelement <vscale x 4 x i1> [[ACTIVE_LANE_MASK_NEXT]], i64 0
; MASKED-SVE-NEXT:    [[TMP17:%.*]] = xor i1 [[TMP16]], true
; MASKED-SVE-NEXT:    br i1 [[TMP17]], label %[[EXIT:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP3:![0-9]+]]
; MASKED-SVE:       [[EXIT]]:
;
; UNMASKED-SVE2P1-LABEL: define void @mixed_i32_more_frequent_than_i64(
; UNMASKED-SVE2P1-SAME: ptr noalias [[X:%.*]], ptr noalias [[Y:%.*]], ptr noalias [[Z:%.*]], i64 [[N:%.*]]) #[[ATTR0]] {
; UNMASKED-SVE2P1-NEXT:  [[ENTRY:.*:]]
; UNMASKED-SVE2P1-NEXT:    [[UMAX:%.*]] = call i64 @llvm.umax.i64(i64 [[N]], i64 1)
; UNMASKED-SVE2P1-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; UNMASKED-SVE2P1-NEXT:    [[TMP1:%.*]] = shl nuw i64 [[TMP0]], 3
; UNMASKED-SVE2P1-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 [[UMAX]], [[TMP1]]
; UNMASKED-SVE2P1-NEXT:    br i1 [[MIN_ITERS_CHECK]], [[SCALAR_PH:label %.*]], label %[[VECTOR_PH:.*]]
; UNMASKED-SVE2P1:       [[VECTOR_PH]]:
; UNMASKED-SVE2P1-NEXT:    [[TMP2:%.*]] = shl nuw i64 [[TMP0]], 2
; UNMASKED-SVE2P1-NEXT:    [[TMP3:%.*]] = shl nuw i64 [[TMP2]], 1
; UNMASKED-SVE2P1-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[UMAX]], [[TMP3]]
; UNMASKED-SVE2P1-NEXT:    [[N_VEC:%.*]] = sub i64 [[UMAX]], [[N_MOD_VF]]
; UNMASKED-SVE2P1-NEXT:    br label %[[VECTOR_BODY:.*]]
; UNMASKED-SVE2P1:       [[VECTOR_BODY]]:
; UNMASKED-SVE2P1-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; UNMASKED-SVE2P1-NEXT:    [[TMP4:%.*]] = getelementptr inbounds i64, ptr [[X]], i64 [[INDEX]]
; UNMASKED-SVE2P1-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 8 x i64>, ptr [[TMP4]], align 8
; UNMASKED-SVE2P1-NEXT:    [[TMP5:%.*]] = call <vscale x 4 x i64> @llvm.vector.extract.nxv4i64.nxv8i64(<vscale x 8 x i64> [[WIDE_LOAD]], i64 0)
; UNMASKED-SVE2P1-NEXT:    [[TMP6:%.*]] = call <vscale x 4 x i64> @llvm.vector.extract.nxv4i64.nxv8i64(<vscale x 8 x i64> [[WIDE_LOAD]], i64 4)
; UNMASKED-SVE2P1-NEXT:    [[TMP7:%.*]] = add <vscale x 4 x i64> [[TMP5]], splat (i64 1)
; UNMASKED-SVE2P1-NEXT:    [[TMP8:%.*]] = add <vscale x 4 x i64> [[TMP6]], splat (i64 1)
; UNMASKED-SVE2P1-NEXT:    [[TMP9:%.*]] = getelementptr inbounds i64, ptr [[TMP4]], i64 [[TMP2]]
; UNMASKED-SVE2P1-NEXT:    store <vscale x 4 x i64> [[TMP7]], ptr [[TMP4]], align 8
; UNMASKED-SVE2P1-NEXT:    store <vscale x 4 x i64> [[TMP8]], ptr [[TMP9]], align 8
; UNMASKED-SVE2P1-NEXT:    [[TMP10:%.*]] = getelementptr inbounds i32, ptr [[Y]], i64 [[INDEX]]
; UNMASKED-SVE2P1-NEXT:    [[WIDE_LOAD1:%.*]] = load <vscale x 8 x i32>, ptr [[TMP10]], align 4
; UNMASKED-SVE2P1-NEXT:    [[TMP11:%.*]] = call <vscale x 4 x i32> @llvm.vector.extract.nxv4i32.nxv8i32(<vscale x 8 x i32> [[WIDE_LOAD1]], i64 0)
; UNMASKED-SVE2P1-NEXT:    [[TMP12:%.*]] = call <vscale x 4 x i32> @llvm.vector.extract.nxv4i32.nxv8i32(<vscale x 8 x i32> [[WIDE_LOAD1]], i64 4)
; UNMASKED-SVE2P1-NEXT:    [[TMP13:%.*]] = add <vscale x 4 x i32> [[TMP11]], splat (i32 1)
; UNMASKED-SVE2P1-NEXT:    [[TMP14:%.*]] = add <vscale x 4 x i32> [[TMP12]], splat (i32 1)
; UNMASKED-SVE2P1-NEXT:    [[TMP15:%.*]] = getelementptr inbounds i32, ptr [[TMP10]], i64 [[TMP2]]
; UNMASKED-SVE2P1-NEXT:    store <vscale x 4 x i32> [[TMP13]], ptr [[TMP10]], align 4
; UNMASKED-SVE2P1-NEXT:    store <vscale x 4 x i32> [[TMP14]], ptr [[TMP15]], align 4
; UNMASKED-SVE2P1-NEXT:    [[TMP16:%.*]] = getelementptr inbounds i32, ptr [[Z]], i64 [[INDEX]]
; UNMASKED-SVE2P1-NEXT:    [[WIDE_LOAD2:%.*]] = load <vscale x 8 x i32>, ptr [[TMP16]], align 4
; UNMASKED-SVE2P1-NEXT:    [[TMP17:%.*]] = call <vscale x 4 x i32> @llvm.vector.extract.nxv4i32.nxv8i32(<vscale x 8 x i32> [[WIDE_LOAD2]], i64 0)
; UNMASKED-SVE2P1-NEXT:    [[TMP18:%.*]] = call <vscale x 4 x i32> @llvm.vector.extract.nxv4i32.nxv8i32(<vscale x 8 x i32> [[WIDE_LOAD2]], i64 4)
; UNMASKED-SVE2P1-NEXT:    [[TMP19:%.*]] = add <vscale x 4 x i32> [[TMP17]], splat (i32 2)
; UNMASKED-SVE2P1-NEXT:    [[TMP20:%.*]] = add <vscale x 4 x i32> [[TMP18]], splat (i32 2)
; UNMASKED-SVE2P1-NEXT:    [[TMP21:%.*]] = getelementptr inbounds i32, ptr [[TMP16]], i64 [[TMP2]]
; UNMASKED-SVE2P1-NEXT:    store <vscale x 4 x i32> [[TMP19]], ptr [[TMP16]], align 4
; UNMASKED-SVE2P1-NEXT:    store <vscale x 4 x i32> [[TMP20]], ptr [[TMP21]], align 4
; UNMASKED-SVE2P1-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP3]]
; UNMASKED-SVE2P1-NEXT:    [[TMP22:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; UNMASKED-SVE2P1-NEXT:    br i1 [[TMP22]], label %[[EXIT:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP4:![0-9]+]]
; UNMASKED-SVE2P1:       [[EXIT]]:
;
; UNMASKED-SVE-LABEL: define void @mixed_i32_more_frequent_than_i64(
; UNMASKED-SVE-SAME: ptr noalias [[X:%.*]], ptr noalias [[Y:%.*]], ptr noalias [[Z:%.*]], i64 [[N:%.*]]) #[[ATTR0]] {
; UNMASKED-SVE-NEXT:  [[ENTRY:.*:]]
; UNMASKED-SVE-NEXT:    [[UMAX:%.*]] = call i64 @llvm.umax.i64(i64 [[N]], i64 1)
; UNMASKED-SVE-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; UNMASKED-SVE-NEXT:    [[TMP1:%.*]] = shl nuw i64 [[TMP0]], 3
; UNMASKED-SVE-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 [[UMAX]], [[TMP1]]
; UNMASKED-SVE-NEXT:    br i1 [[MIN_ITERS_CHECK]], [[SCALAR_PH:label %.*]], label %[[VECTOR_PH:.*]]
; UNMASKED-SVE:       [[VECTOR_PH]]:
; UNMASKED-SVE-NEXT:    [[TMP2:%.*]] = shl nuw i64 [[TMP0]], 2
; UNMASKED-SVE-NEXT:    [[TMP3:%.*]] = shl nuw i64 [[TMP2]], 1
; UNMASKED-SVE-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[UMAX]], [[TMP3]]
; UNMASKED-SVE-NEXT:    [[N_VEC:%.*]] = sub i64 [[UMAX]], [[N_MOD_VF]]
; UNMASKED-SVE-NEXT:    br label %[[VECTOR_BODY:.*]]
; UNMASKED-SVE:       [[VECTOR_BODY]]:
; UNMASKED-SVE-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; UNMASKED-SVE-NEXT:    [[TMP4:%.*]] = getelementptr inbounds i64, ptr [[X]], i64 [[INDEX]]
; UNMASKED-SVE-NEXT:    [[TMP5:%.*]] = getelementptr inbounds i64, ptr [[TMP4]], i64 [[TMP2]]
; UNMASKED-SVE-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 4 x i64>, ptr [[TMP4]], align 8
; UNMASKED-SVE-NEXT:    [[WIDE_LOAD1:%.*]] = load <vscale x 4 x i64>, ptr [[TMP5]], align 8
; UNMASKED-SVE-NEXT:    [[TMP6:%.*]] = add <vscale x 4 x i64> [[WIDE_LOAD]], splat (i64 1)
; UNMASKED-SVE-NEXT:    [[TMP7:%.*]] = add <vscale x 4 x i64> [[WIDE_LOAD1]], splat (i64 1)
; UNMASKED-SVE-NEXT:    store <vscale x 4 x i64> [[TMP6]], ptr [[TMP4]], align 8
; UNMASKED-SVE-NEXT:    store <vscale x 4 x i64> [[TMP7]], ptr [[TMP5]], align 8
; UNMASKED-SVE-NEXT:    [[TMP8:%.*]] = getelementptr inbounds i32, ptr [[Y]], i64 [[INDEX]]
; UNMASKED-SVE-NEXT:    [[TMP9:%.*]] = getelementptr inbounds i32, ptr [[TMP8]], i64 [[TMP2]]
; UNMASKED-SVE-NEXT:    [[WIDE_LOAD2:%.*]] = load <vscale x 4 x i32>, ptr [[TMP8]], align 4
; UNMASKED-SVE-NEXT:    [[WIDE_LOAD3:%.*]] = load <vscale x 4 x i32>, ptr [[TMP9]], align 4
; UNMASKED-SVE-NEXT:    [[TMP10:%.*]] = add <vscale x 4 x i32> [[WIDE_LOAD2]], splat (i32 1)
; UNMASKED-SVE-NEXT:    [[TMP11:%.*]] = add <vscale x 4 x i32> [[WIDE_LOAD3]], splat (i32 1)
; UNMASKED-SVE-NEXT:    store <vscale x 4 x i32> [[TMP10]], ptr [[TMP8]], align 4
; UNMASKED-SVE-NEXT:    store <vscale x 4 x i32> [[TMP11]], ptr [[TMP9]], align 4
; UNMASKED-SVE-NEXT:    [[TMP12:%.*]] = getelementptr inbounds i32, ptr [[Z]], i64 [[INDEX]]
; UNMASKED-SVE-NEXT:    [[TMP13:%.*]] = getelementptr inbounds i32, ptr [[TMP12]], i64 [[TMP2]]
; UNMASKED-SVE-NEXT:    [[WIDE_LOAD4:%.*]] = load <vscale x 4 x i32>, ptr [[TMP12]], align 4
; UNMASKED-SVE-NEXT:    [[WIDE_LOAD5:%.*]] = load <vscale x 4 x i32>, ptr [[TMP13]], align 4
; UNMASKED-SVE-NEXT:    [[TMP14:%.*]] = add <vscale x 4 x i32> [[WIDE_LOAD4]], splat (i32 2)
; UNMASKED-SVE-NEXT:    [[TMP15:%.*]] = add <vscale x 4 x i32> [[WIDE_LOAD5]], splat (i32 2)
; UNMASKED-SVE-NEXT:    store <vscale x 4 x i32> [[TMP14]], ptr [[TMP12]], align 4
; UNMASKED-SVE-NEXT:    store <vscale x 4 x i32> [[TMP15]], ptr [[TMP13]], align 4
; UNMASKED-SVE-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP3]]
; UNMASKED-SVE-NEXT:    [[TMP16:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; UNMASKED-SVE-NEXT:    br i1 [[TMP16]], label %[[EXIT:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP4:![0-9]+]]
; UNMASKED-SVE:       [[EXIT]]:
;
  ptr noalias %x, ptr noalias %y, ptr noalias %z, i64 %n) {
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %next, %loop ]
  %px = getelementptr inbounds i64, ptr %x, i64 %iv
  %vx = load i64, ptr %px, align 8
  %ax = add i64 %vx, 1
  store i64 %ax, ptr %px, align 8
  %py = getelementptr inbounds i32, ptr %y, i64 %iv
  %vy = load i32, ptr %py, align 4
  %ay = add i32 %vy, 1
  store i32 %ay, ptr %py, align 4
  %pz = getelementptr inbounds i32, ptr %z, i64 %iv
  %vz = load i32, ptr %pz, align 4
  %az = add i32 %vz, 2
  store i32 %az, ptr %pz, align 4
  %next = add nuw i64 %iv, 1
  %cmp = icmp ult i64 %next, %n
  br i1 %cmp, label %loop, label %exit, !llvm.loop !5

exit:
  ret void
}

; First-order recurrence with contiguous i64 loads and stores. This should
; still compose with force-wide-mem-ops.
define void @first_order_recurrence_i64_scaled_load_and_store(
; MASKED-SVE2P1-LABEL: define void @first_order_recurrence_i64_scaled_load_and_store(
; MASKED-SVE2P1-SAME: ptr noalias [[SRC:%.*]], ptr noalias [[DST:%.*]]) #[[ATTR0]] {
; MASKED-SVE2P1-NEXT:  [[ENTRY:.*:]]
; MASKED-SVE2P1-NEXT:    [[FIRST:%.*]] = load i64, ptr [[SRC]], align 8
; MASKED-SVE2P1-NEXT:    br label %[[VECTOR_PH:.*]]
; MASKED-SVE2P1:       [[VECTOR_PH]]:
; MASKED-SVE2P1-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; MASKED-SVE2P1-NEXT:    [[TMP1:%.*]] = shl nuw i64 [[TMP0]], 2
; MASKED-SVE2P1-NEXT:    [[ACTIVE_LANE_MASK_ENTRY:%.*]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.for.type.nxv4i1.i64(i64 0, i64 1024, i64 8)
; MASKED-SVE2P1-NEXT:    [[TMP2:%.*]] = call i32 @llvm.vscale.i32()
; MASKED-SVE2P1-NEXT:    [[TMP3:%.*]] = mul nuw i32 [[TMP2]], 2
; MASKED-SVE2P1-NEXT:    [[TMP4:%.*]] = sub i32 [[TMP3]], 1
; MASKED-SVE2P1-NEXT:    [[VECTOR_RECUR_INIT:%.*]] = insertelement <vscale x 2 x i64> poison, i64 [[FIRST]], i32 [[TMP4]]
; MASKED-SVE2P1-NEXT:    br label %[[VECTOR_BODY:.*]]
; MASKED-SVE2P1:       [[VECTOR_BODY]]:
; MASKED-SVE2P1-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; MASKED-SVE2P1-NEXT:    [[ACTIVE_LANE_MASK:%.*]] = phi <vscale x 4 x i1> [ [[ACTIVE_LANE_MASK_ENTRY]], %[[VECTOR_PH]] ], [ [[ACTIVE_LANE_MASK_NEXT:%.*]], %[[VECTOR_BODY]] ]
; MASKED-SVE2P1-NEXT:    [[VECTOR_RECUR:%.*]] = phi <vscale x 2 x i64> [ [[VECTOR_RECUR_INIT]], %[[VECTOR_PH]] ], [ [[TMP8:%.*]], %[[VECTOR_BODY]] ]
; MASKED-SVE2P1-NEXT:    [[TMP5:%.*]] = add i64 1, [[INDEX]]
; MASKED-SVE2P1-NEXT:    [[TMP6:%.*]] = getelementptr inbounds i64, ptr [[SRC]], i64 [[TMP5]]
; MASKED-SVE2P1-NEXT:    [[WIDE_MASKED_LOAD:%.*]] = call <vscale x 4 x i64> @llvm.masked.load.nxv4i64.p0(ptr align 8 [[TMP6]], <vscale x 4 x i1> [[ACTIVE_LANE_MASK]], <vscale x 4 x i64> poison)
; MASKED-SVE2P1-NEXT:    [[TMP7:%.*]] = call <vscale x 2 x i64> @llvm.vector.extract.nxv2i64.nxv4i64(<vscale x 4 x i64> [[WIDE_MASKED_LOAD]], i64 0)
; MASKED-SVE2P1-NEXT:    [[TMP8]] = call <vscale x 2 x i64> @llvm.vector.extract.nxv2i64.nxv4i64(<vscale x 4 x i64> [[WIDE_MASKED_LOAD]], i64 2)
; MASKED-SVE2P1-NEXT:    [[TMP9:%.*]] = call <vscale x 2 x i64> @llvm.vector.splice.right.nxv2i64(<vscale x 2 x i64> [[VECTOR_RECUR]], <vscale x 2 x i64> [[TMP7]], i32 1)
; MASKED-SVE2P1-NEXT:    [[TMP10:%.*]] = call <vscale x 2 x i64> @llvm.vector.splice.right.nxv2i64(<vscale x 2 x i64> [[TMP7]], <vscale x 2 x i64> [[TMP8]], i32 1)
; MASKED-SVE2P1-NEXT:    [[TMP11:%.*]] = add <vscale x 2 x i64> [[TMP9]], [[TMP7]]
; MASKED-SVE2P1-NEXT:    [[TMP12:%.*]] = add <vscale x 2 x i64> [[TMP10]], [[TMP8]]
; MASKED-SVE2P1-NEXT:    [[TMP13:%.*]] = getelementptr inbounds i64, ptr [[DST]], i64 [[TMP5]]
; MASKED-SVE2P1-NEXT:    [[TMP14:%.*]] = call <vscale x 4 x i64> @llvm.vector.insert.nxv4i64.nxv2i64(<vscale x 4 x i64> poison, <vscale x 2 x i64> [[TMP11]], i64 0)
; MASKED-SVE2P1-NEXT:    [[TMP15:%.*]] = call <vscale x 4 x i64> @llvm.vector.insert.nxv4i64.nxv2i64(<vscale x 4 x i64> [[TMP14]], <vscale x 2 x i64> [[TMP12]], i64 2)
; MASKED-SVE2P1-NEXT:    call void @llvm.masked.store.nxv4i64.p0(<vscale x 4 x i64> [[TMP15]], ptr align 8 [[TMP13]], <vscale x 4 x i1> [[ACTIVE_LANE_MASK]])
; MASKED-SVE2P1-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], [[TMP1]]
; MASKED-SVE2P1-NEXT:    [[ACTIVE_LANE_MASK_NEXT]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.for.type.nxv4i1.i64(i64 [[INDEX_NEXT]], i64 1024, i64 8)
; MASKED-SVE2P1-NEXT:    [[TMP16:%.*]] = extractelement <vscale x 4 x i1> [[ACTIVE_LANE_MASK_NEXT]], i64 0
; MASKED-SVE2P1-NEXT:    [[TMP17:%.*]] = xor i1 [[TMP16]], true
; MASKED-SVE2P1-NEXT:    br i1 [[TMP17]], label %[[EXIT:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP4:![0-9]+]]
; MASKED-SVE2P1:       [[EXIT]]:
;
; MASKED-SVE-LABEL: define void @first_order_recurrence_i64_scaled_load_and_store(
; MASKED-SVE-SAME: ptr noalias [[SRC:%.*]], ptr noalias [[DST:%.*]]) #[[ATTR0]] {
; MASKED-SVE-NEXT:  [[ENTRY:.*:]]
; MASKED-SVE-NEXT:    [[FIRST:%.*]] = load i64, ptr [[SRC]], align 8
; MASKED-SVE-NEXT:    br label %[[VECTOR_PH:.*]]
; MASKED-SVE:       [[VECTOR_PH]]:
; MASKED-SVE-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; MASKED-SVE-NEXT:    [[TMP1:%.*]] = shl nuw i64 [[TMP0]], 1
; MASKED-SVE-NEXT:    [[TMP2:%.*]] = shl nuw i64 [[TMP1]], 1
; MASKED-SVE-NEXT:    [[ACTIVE_LANE_MASK_ENTRY:%.*]] = call <vscale x 2 x i1> @llvm.get.active.lane.mask.nxv2i1.i64(i64 0, i64 1024)
; MASKED-SVE-NEXT:    [[ACTIVE_LANE_MASK_ENTRY1:%.*]] = call <vscale x 2 x i1> @llvm.get.active.lane.mask.nxv2i1.i64(i64 [[TMP1]], i64 1024)
; MASKED-SVE-NEXT:    [[TMP3:%.*]] = call i32 @llvm.vscale.i32()
; MASKED-SVE-NEXT:    [[TMP4:%.*]] = mul nuw i32 [[TMP3]], 2
; MASKED-SVE-NEXT:    [[TMP5:%.*]] = sub i32 [[TMP4]], 1
; MASKED-SVE-NEXT:    [[VECTOR_RECUR_INIT:%.*]] = insertelement <vscale x 2 x i64> poison, i64 [[FIRST]], i32 [[TMP5]]
; MASKED-SVE-NEXT:    br label %[[VECTOR_BODY:.*]]
; MASKED-SVE:       [[VECTOR_BODY]]:
; MASKED-SVE-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; MASKED-SVE-NEXT:    [[ACTIVE_LANE_MASK:%.*]] = phi <vscale x 2 x i1> [ [[ACTIVE_LANE_MASK_ENTRY]], %[[VECTOR_PH]] ], [ [[ACTIVE_LANE_MASK_NEXT:%.*]], %[[VECTOR_BODY]] ]
; MASKED-SVE-NEXT:    [[ACTIVE_LANE_MASK2:%.*]] = phi <vscale x 2 x i1> [ [[ACTIVE_LANE_MASK_ENTRY1]], %[[VECTOR_PH]] ], [ [[ACTIVE_LANE_MASK_NEXT4:%.*]], %[[VECTOR_BODY]] ]
; MASKED-SVE-NEXT:    [[VECTOR_RECUR:%.*]] = phi <vscale x 2 x i64> [ [[VECTOR_RECUR_INIT]], %[[VECTOR_PH]] ], [ [[WIDE_MASKED_LOAD3:%.*]], %[[VECTOR_BODY]] ]
; MASKED-SVE-NEXT:    [[TMP6:%.*]] = add i64 1, [[INDEX]]
; MASKED-SVE-NEXT:    [[TMP7:%.*]] = getelementptr inbounds i64, ptr [[SRC]], i64 [[TMP6]]
; MASKED-SVE-NEXT:    [[TMP8:%.*]] = getelementptr inbounds i64, ptr [[TMP7]], i64 [[TMP1]]
; MASKED-SVE-NEXT:    [[WIDE_MASKED_LOAD:%.*]] = call <vscale x 2 x i64> @llvm.masked.load.nxv2i64.p0(ptr align 8 [[TMP7]], <vscale x 2 x i1> [[ACTIVE_LANE_MASK]], <vscale x 2 x i64> poison)
; MASKED-SVE-NEXT:    [[WIDE_MASKED_LOAD3]] = call <vscale x 2 x i64> @llvm.masked.load.nxv2i64.p0(ptr align 8 [[TMP8]], <vscale x 2 x i1> [[ACTIVE_LANE_MASK2]], <vscale x 2 x i64> poison)
; MASKED-SVE-NEXT:    [[TMP9:%.*]] = call <vscale x 2 x i64> @llvm.vector.splice.right.nxv2i64(<vscale x 2 x i64> [[VECTOR_RECUR]], <vscale x 2 x i64> [[WIDE_MASKED_LOAD]], i32 1)
; MASKED-SVE-NEXT:    [[TMP10:%.*]] = call <vscale x 2 x i64> @llvm.vector.splice.right.nxv2i64(<vscale x 2 x i64> [[WIDE_MASKED_LOAD]], <vscale x 2 x i64> [[WIDE_MASKED_LOAD3]], i32 1)
; MASKED-SVE-NEXT:    [[TMP11:%.*]] = add <vscale x 2 x i64> [[TMP9]], [[WIDE_MASKED_LOAD]]
; MASKED-SVE-NEXT:    [[TMP12:%.*]] = add <vscale x 2 x i64> [[TMP10]], [[WIDE_MASKED_LOAD3]]
; MASKED-SVE-NEXT:    [[TMP13:%.*]] = getelementptr inbounds i64, ptr [[DST]], i64 [[TMP6]]
; MASKED-SVE-NEXT:    [[TMP14:%.*]] = getelementptr inbounds i64, ptr [[TMP13]], i64 [[TMP1]]
; MASKED-SVE-NEXT:    call void @llvm.masked.store.nxv2i64.p0(<vscale x 2 x i64> [[TMP11]], ptr align 8 [[TMP13]], <vscale x 2 x i1> [[ACTIVE_LANE_MASK]])
; MASKED-SVE-NEXT:    call void @llvm.masked.store.nxv2i64.p0(<vscale x 2 x i64> [[TMP12]], ptr align 8 [[TMP14]], <vscale x 2 x i1> [[ACTIVE_LANE_MASK2]])
; MASKED-SVE-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], [[TMP2]]
; MASKED-SVE-NEXT:    [[TMP15:%.*]] = add i64 [[INDEX_NEXT]], [[TMP1]]
; MASKED-SVE-NEXT:    [[ACTIVE_LANE_MASK_NEXT]] = call <vscale x 2 x i1> @llvm.get.active.lane.mask.nxv2i1.i64(i64 [[INDEX_NEXT]], i64 1024)
; MASKED-SVE-NEXT:    [[ACTIVE_LANE_MASK_NEXT4]] = call <vscale x 2 x i1> @llvm.get.active.lane.mask.nxv2i1.i64(i64 [[TMP15]], i64 1024)
; MASKED-SVE-NEXT:    [[TMP16:%.*]] = extractelement <vscale x 2 x i1> [[ACTIVE_LANE_MASK_NEXT]], i64 0
; MASKED-SVE-NEXT:    [[TMP17:%.*]] = xor i1 [[TMP16]], true
; MASKED-SVE-NEXT:    br i1 [[TMP17]], label %[[EXIT:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP4:![0-9]+]]
; MASKED-SVE:       [[EXIT]]:
;
; UNMASKED-SVE2P1-LABEL: define void @first_order_recurrence_i64_scaled_load_and_store(
; UNMASKED-SVE2P1-SAME: ptr noalias [[SRC:%.*]], ptr noalias [[DST:%.*]]) #[[ATTR0]] {
; UNMASKED-SVE2P1-NEXT:  [[ENTRY:.*:]]
; UNMASKED-SVE2P1-NEXT:    [[FIRST:%.*]] = load i64, ptr [[SRC]], align 8
; UNMASKED-SVE2P1-NEXT:    br label %[[VECTOR_BODY:.*]]
; UNMASKED-SVE2P1:       [[VECTOR_BODY]]:
; UNMASKED-SVE2P1-NEXT:    [[VECTOR_RECUR_INIT:%.*]] = insertelement <2 x i64> poison, i64 [[FIRST]], i32 1
; UNMASKED-SVE2P1-NEXT:    br label %[[LOOP:.*]]
; UNMASKED-SVE2P1:       [[LOOP]]:
; UNMASKED-SVE2P1-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_BODY]] ], [ [[INDEX_NEXT:%.*]], %[[LOOP]] ]
; UNMASKED-SVE2P1-NEXT:    [[VECTOR_RECUR:%.*]] = phi <2 x i64> [ [[VECTOR_RECUR_INIT]], %[[VECTOR_BODY]] ], [ [[WIDE_LOAD1:%.*]], %[[LOOP]] ]
; UNMASKED-SVE2P1-NEXT:    [[IV:%.*]] = add i64 1, [[INDEX]]
; UNMASKED-SVE2P1-NEXT:    [[CUR_PTR:%.*]] = getelementptr inbounds i64, ptr [[SRC]], i64 [[IV]]
; UNMASKED-SVE2P1-NEXT:    [[TMP2:%.*]] = getelementptr inbounds i64, ptr [[CUR_PTR]], i64 2
; UNMASKED-SVE2P1-NEXT:    [[WIDE_LOAD:%.*]] = load <2 x i64>, ptr [[CUR_PTR]], align 8
; UNMASKED-SVE2P1-NEXT:    [[WIDE_LOAD1]] = load <2 x i64>, ptr [[TMP2]], align 8
; UNMASKED-SVE2P1-NEXT:    [[TMP3:%.*]] = shufflevector <2 x i64> [[VECTOR_RECUR]], <2 x i64> [[WIDE_LOAD]], <2 x i32> <i32 1, i32 2>
; UNMASKED-SVE2P1-NEXT:    [[TMP4:%.*]] = shufflevector <2 x i64> [[WIDE_LOAD]], <2 x i64> [[WIDE_LOAD1]], <2 x i32> <i32 1, i32 2>
; UNMASKED-SVE2P1-NEXT:    [[TMP5:%.*]] = add <2 x i64> [[TMP3]], [[WIDE_LOAD]]
; UNMASKED-SVE2P1-NEXT:    [[TMP6:%.*]] = add <2 x i64> [[TMP4]], [[WIDE_LOAD1]]
; UNMASKED-SVE2P1-NEXT:    [[DST_PTR:%.*]] = getelementptr inbounds i64, ptr [[DST]], i64 [[IV]]
; UNMASKED-SVE2P1-NEXT:    [[TMP8:%.*]] = getelementptr inbounds i64, ptr [[DST_PTR]], i64 2
; UNMASKED-SVE2P1-NEXT:    store <2 x i64> [[TMP5]], ptr [[DST_PTR]], align 8
; UNMASKED-SVE2P1-NEXT:    store <2 x i64> [[TMP6]], ptr [[TMP8]], align 8
; UNMASKED-SVE2P1-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 4
; UNMASKED-SVE2P1-NEXT:    [[TMP9:%.*]] = icmp eq i64 [[INDEX_NEXT]], 1024
; UNMASKED-SVE2P1-NEXT:    br i1 [[TMP9]], label %[[EXIT:.*]], label %[[LOOP]], !llvm.loop [[LOOP6:![0-9]+]]
; UNMASKED-SVE2P1:       [[EXIT]]:
;
; UNMASKED-SVE-LABEL: define void @first_order_recurrence_i64_scaled_load_and_store(
; UNMASKED-SVE-SAME: ptr noalias [[SRC:%.*]], ptr noalias [[DST:%.*]]) #[[ATTR0]] {
; UNMASKED-SVE-NEXT:  [[ENTRY:.*:]]
; UNMASKED-SVE-NEXT:    [[FIRST:%.*]] = load i64, ptr [[SRC]], align 8
; UNMASKED-SVE-NEXT:    br label %[[VECTOR_BODY:.*]]
; UNMASKED-SVE:       [[VECTOR_BODY]]:
; UNMASKED-SVE-NEXT:    [[VECTOR_RECUR_INIT:%.*]] = insertelement <2 x i64> poison, i64 [[FIRST]], i32 1
; UNMASKED-SVE-NEXT:    br label %[[LOOP:.*]]
; UNMASKED-SVE:       [[LOOP]]:
; UNMASKED-SVE-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_BODY]] ], [ [[INDEX_NEXT:%.*]], %[[LOOP]] ]
; UNMASKED-SVE-NEXT:    [[VECTOR_RECUR:%.*]] = phi <2 x i64> [ [[VECTOR_RECUR_INIT]], %[[VECTOR_BODY]] ], [ [[WIDE_LOAD1:%.*]], %[[LOOP]] ]
; UNMASKED-SVE-NEXT:    [[IV:%.*]] = add i64 1, [[INDEX]]
; UNMASKED-SVE-NEXT:    [[CUR_PTR:%.*]] = getelementptr inbounds i64, ptr [[SRC]], i64 [[IV]]
; UNMASKED-SVE-NEXT:    [[TMP2:%.*]] = getelementptr inbounds i64, ptr [[CUR_PTR]], i64 2
; UNMASKED-SVE-NEXT:    [[WIDE_LOAD:%.*]] = load <2 x i64>, ptr [[CUR_PTR]], align 8
; UNMASKED-SVE-NEXT:    [[WIDE_LOAD1]] = load <2 x i64>, ptr [[TMP2]], align 8
; UNMASKED-SVE-NEXT:    [[TMP3:%.*]] = shufflevector <2 x i64> [[VECTOR_RECUR]], <2 x i64> [[WIDE_LOAD]], <2 x i32> <i32 1, i32 2>
; UNMASKED-SVE-NEXT:    [[TMP4:%.*]] = shufflevector <2 x i64> [[WIDE_LOAD]], <2 x i64> [[WIDE_LOAD1]], <2 x i32> <i32 1, i32 2>
; UNMASKED-SVE-NEXT:    [[TMP5:%.*]] = add <2 x i64> [[TMP3]], [[WIDE_LOAD]]
; UNMASKED-SVE-NEXT:    [[TMP6:%.*]] = add <2 x i64> [[TMP4]], [[WIDE_LOAD1]]
; UNMASKED-SVE-NEXT:    [[DST_PTR:%.*]] = getelementptr inbounds i64, ptr [[DST]], i64 [[IV]]
; UNMASKED-SVE-NEXT:    [[TMP8:%.*]] = getelementptr inbounds i64, ptr [[DST_PTR]], i64 2
; UNMASKED-SVE-NEXT:    store <2 x i64> [[TMP5]], ptr [[DST_PTR]], align 8
; UNMASKED-SVE-NEXT:    store <2 x i64> [[TMP6]], ptr [[TMP8]], align 8
; UNMASKED-SVE-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 4
; UNMASKED-SVE-NEXT:    [[TMP9:%.*]] = icmp eq i64 [[INDEX_NEXT]], 1024
; UNMASKED-SVE-NEXT:    br i1 [[TMP9]], label %[[EXIT:.*]], label %[[LOOP]], !llvm.loop [[LOOP6:![0-9]+]]
; UNMASKED-SVE:       [[EXIT]]:
;
  ptr noalias %src, ptr noalias %dst) {
entry:
  %first = load i64, ptr %src, align 8
  br label %loop

loop:
  %iv = phi i64 [ 1, %entry ], [ %next, %loop ]
  %prev = phi i64 [ %first, %entry ], [ %cur, %loop ]
  %cur.ptr = getelementptr inbounds i64, ptr %src, i64 %iv
  %cur = load i64, ptr %cur.ptr, align 8
  %sum = add i64 %prev, %cur
  %dst.ptr = getelementptr inbounds i64, ptr %dst, i64 %iv
  store i64 %sum, ptr %dst.ptr, align 8
  %next = add nuw i64 %iv, 1
  %cmp = icmp eq i64 %next, 1025
  br i1 %cmp, label %exit, label %loop

exit:
  ret void
}

; Reduction-style loop that should use a scaled wide load feeding a partial
; reduction.
define i64 @i64_sum_reduction_scaled_partial_reduce(ptr noalias %a, i64 %n) {
; MASKED-SVE2P1-LABEL: define i64 @i64_sum_reduction_scaled_partial_reduce(
; MASKED-SVE2P1-SAME: ptr noalias [[A:%.*]], i64 [[N:%.*]]) #[[ATTR0]] {
; MASKED-SVE2P1-NEXT:  [[ENTRY:.*:]]
; MASKED-SVE2P1-NEXT:    [[UMAX:%.*]] = call i64 @llvm.umax.i64(i64 [[N]], i64 1)
; MASKED-SVE2P1-NEXT:    br label %[[VECTOR_PH:.*]]
; MASKED-SVE2P1:       [[VECTOR_PH]]:
; MASKED-SVE2P1-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; MASKED-SVE2P1-NEXT:    [[TMP1:%.*]] = shl nuw i64 [[TMP0]], 2
; MASKED-SVE2P1-NEXT:    [[ACTIVE_LANE_MASK_ENTRY:%.*]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.for.type.nxv4i1.i64(i64 0, i64 [[UMAX]], i64 8)
; MASKED-SVE2P1-NEXT:    br label %[[VECTOR_BODY:.*]]
; MASKED-SVE2P1:       [[VECTOR_BODY]]:
; MASKED-SVE2P1-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; MASKED-SVE2P1-NEXT:    [[ACTIVE_LANE_MASK:%.*]] = phi <vscale x 4 x i1> [ [[ACTIVE_LANE_MASK_ENTRY]], %[[VECTOR_PH]] ], [ [[ACTIVE_LANE_MASK_NEXT:%.*]], %[[VECTOR_BODY]] ]
; MASKED-SVE2P1-NEXT:    [[VEC_PHI:%.*]] = phi <vscale x 2 x i64> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP9:%.*]], %[[VECTOR_BODY]] ]
; MASKED-SVE2P1-NEXT:    [[VEC_PHI1:%.*]] = phi <vscale x 2 x i64> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP10:%.*]], %[[VECTOR_BODY]] ]
; MASKED-SVE2P1-NEXT:    [[TMP2:%.*]] = call <vscale x 2 x i1> @llvm.vector.extract.nxv2i1.nxv4i1(<vscale x 4 x i1> [[ACTIVE_LANE_MASK]], i64 0)
; MASKED-SVE2P1-NEXT:    [[TMP3:%.*]] = call <vscale x 2 x i1> @llvm.vector.extract.nxv2i1.nxv4i1(<vscale x 4 x i1> [[ACTIVE_LANE_MASK]], i64 2)
; MASKED-SVE2P1-NEXT:    [[TMP4:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[INDEX]]
; MASKED-SVE2P1-NEXT:    [[WIDE_MASKED_LOAD:%.*]] = call <vscale x 4 x i64> @llvm.masked.load.nxv4i64.p0(ptr align 8 [[TMP4]], <vscale x 4 x i1> [[ACTIVE_LANE_MASK]], <vscale x 4 x i64> poison)
; MASKED-SVE2P1-NEXT:    [[TMP5:%.*]] = call <vscale x 2 x i64> @llvm.vector.extract.nxv2i64.nxv4i64(<vscale x 4 x i64> [[WIDE_MASKED_LOAD]], i64 0)
; MASKED-SVE2P1-NEXT:    [[TMP6:%.*]] = call <vscale x 2 x i64> @llvm.vector.extract.nxv2i64.nxv4i64(<vscale x 4 x i64> [[WIDE_MASKED_LOAD]], i64 2)
; MASKED-SVE2P1-NEXT:    [[TMP7:%.*]] = add <vscale x 2 x i64> [[VEC_PHI]], [[TMP5]]
; MASKED-SVE2P1-NEXT:    [[TMP8:%.*]] = add <vscale x 2 x i64> [[VEC_PHI1]], [[TMP6]]
; MASKED-SVE2P1-NEXT:    [[TMP9]] = select <vscale x 2 x i1> [[TMP2]], <vscale x 2 x i64> [[TMP7]], <vscale x 2 x i64> [[VEC_PHI]]
; MASKED-SVE2P1-NEXT:    [[TMP10]] = select <vscale x 2 x i1> [[TMP3]], <vscale x 2 x i64> [[TMP8]], <vscale x 2 x i64> [[VEC_PHI1]]
; MASKED-SVE2P1-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], [[TMP1]]
; MASKED-SVE2P1-NEXT:    [[ACTIVE_LANE_MASK_NEXT]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.for.type.nxv4i1.i64(i64 [[INDEX_NEXT]], i64 [[UMAX]], i64 8)
; MASKED-SVE2P1-NEXT:    [[TMP11:%.*]] = extractelement <vscale x 4 x i1> [[ACTIVE_LANE_MASK_NEXT]], i64 0
; MASKED-SVE2P1-NEXT:    [[TMP12:%.*]] = xor i1 [[TMP11]], true
; MASKED-SVE2P1-NEXT:    br i1 [[TMP12]], label %[[EXIT:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP5:![0-9]+]]
; MASKED-SVE2P1:       [[EXIT]]:
;
; MASKED-SVE-LABEL: define i64 @i64_sum_reduction_scaled_partial_reduce(
; MASKED-SVE-SAME: ptr noalias [[A:%.*]], i64 [[N:%.*]]) #[[ATTR0]] {
; MASKED-SVE-NEXT:  [[ENTRY:.*:]]
; MASKED-SVE-NEXT:    [[UMAX:%.*]] = call i64 @llvm.umax.i64(i64 [[N]], i64 1)
; MASKED-SVE-NEXT:    br label %[[VECTOR_PH:.*]]
; MASKED-SVE:       [[VECTOR_PH]]:
; MASKED-SVE-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; MASKED-SVE-NEXT:    [[TMP1:%.*]] = shl nuw i64 [[TMP0]], 1
; MASKED-SVE-NEXT:    [[TMP2:%.*]] = shl nuw i64 [[TMP1]], 1
; MASKED-SVE-NEXT:    [[ACTIVE_LANE_MASK_ENTRY:%.*]] = call <vscale x 2 x i1> @llvm.get.active.lane.mask.nxv2i1.i64(i64 0, i64 [[UMAX]])
; MASKED-SVE-NEXT:    [[ACTIVE_LANE_MASK_ENTRY1:%.*]] = call <vscale x 2 x i1> @llvm.get.active.lane.mask.nxv2i1.i64(i64 [[TMP1]], i64 [[UMAX]])
; MASKED-SVE-NEXT:    br label %[[VECTOR_BODY:.*]]
; MASKED-SVE:       [[VECTOR_BODY]]:
; MASKED-SVE-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; MASKED-SVE-NEXT:    [[ACTIVE_LANE_MASK:%.*]] = phi <vscale x 2 x i1> [ [[ACTIVE_LANE_MASK_ENTRY]], %[[VECTOR_PH]] ], [ [[ACTIVE_LANE_MASK_NEXT:%.*]], %[[VECTOR_BODY]] ]
; MASKED-SVE-NEXT:    [[ACTIVE_LANE_MASK2:%.*]] = phi <vscale x 2 x i1> [ [[ACTIVE_LANE_MASK_ENTRY1]], %[[VECTOR_PH]] ], [ [[ACTIVE_LANE_MASK_NEXT5:%.*]], %[[VECTOR_BODY]] ]
; MASKED-SVE-NEXT:    [[VEC_PHI:%.*]] = phi <vscale x 2 x i64> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP7:%.*]], %[[VECTOR_BODY]] ]
; MASKED-SVE-NEXT:    [[VEC_PHI3:%.*]] = phi <vscale x 2 x i64> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP8:%.*]], %[[VECTOR_BODY]] ]
; MASKED-SVE-NEXT:    [[TMP3:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[INDEX]]
; MASKED-SVE-NEXT:    [[TMP4:%.*]] = getelementptr inbounds i64, ptr [[TMP3]], i64 [[TMP1]]
; MASKED-SVE-NEXT:    [[WIDE_MASKED_LOAD:%.*]] = call <vscale x 2 x i64> @llvm.masked.load.nxv2i64.p0(ptr align 8 [[TMP3]], <vscale x 2 x i1> [[ACTIVE_LANE_MASK]], <vscale x 2 x i64> poison)
; MASKED-SVE-NEXT:    [[WIDE_MASKED_LOAD4:%.*]] = call <vscale x 2 x i64> @llvm.masked.load.nxv2i64.p0(ptr align 8 [[TMP4]], <vscale x 2 x i1> [[ACTIVE_LANE_MASK2]], <vscale x 2 x i64> poison)
; MASKED-SVE-NEXT:    [[TMP5:%.*]] = add <vscale x 2 x i64> [[VEC_PHI]], [[WIDE_MASKED_LOAD]]
; MASKED-SVE-NEXT:    [[TMP6:%.*]] = add <vscale x 2 x i64> [[VEC_PHI3]], [[WIDE_MASKED_LOAD4]]
; MASKED-SVE-NEXT:    [[TMP7]] = select <vscale x 2 x i1> [[ACTIVE_LANE_MASK]], <vscale x 2 x i64> [[TMP5]], <vscale x 2 x i64> [[VEC_PHI]]
; MASKED-SVE-NEXT:    [[TMP8]] = select <vscale x 2 x i1> [[ACTIVE_LANE_MASK2]], <vscale x 2 x i64> [[TMP6]], <vscale x 2 x i64> [[VEC_PHI3]]
; MASKED-SVE-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], [[TMP2]]
; MASKED-SVE-NEXT:    [[TMP9:%.*]] = add i64 [[INDEX_NEXT]], [[TMP1]]
; MASKED-SVE-NEXT:    [[ACTIVE_LANE_MASK_NEXT]] = call <vscale x 2 x i1> @llvm.get.active.lane.mask.nxv2i1.i64(i64 [[INDEX_NEXT]], i64 [[UMAX]])
; MASKED-SVE-NEXT:    [[ACTIVE_LANE_MASK_NEXT5]] = call <vscale x 2 x i1> @llvm.get.active.lane.mask.nxv2i1.i64(i64 [[TMP9]], i64 [[UMAX]])
; MASKED-SVE-NEXT:    [[TMP10:%.*]] = extractelement <vscale x 2 x i1> [[ACTIVE_LANE_MASK_NEXT]], i64 0
; MASKED-SVE-NEXT:    [[TMP11:%.*]] = xor i1 [[TMP10]], true
; MASKED-SVE-NEXT:    br i1 [[TMP11]], label %[[EXIT:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP5:![0-9]+]]
; MASKED-SVE:       [[EXIT]]:
;
; UNMASKED-SVE2P1-LABEL: define i64 @i64_sum_reduction_scaled_partial_reduce(
; UNMASKED-SVE2P1-SAME: ptr noalias [[A:%.*]], i64 [[N:%.*]]) #[[ATTR0]] {
; UNMASKED-SVE2P1-NEXT:  [[ENTRY:.*:]]
; UNMASKED-SVE2P1-NEXT:    [[UMAX:%.*]] = call i64 @llvm.umax.i64(i64 [[N]], i64 1)
; UNMASKED-SVE2P1-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; UNMASKED-SVE2P1-NEXT:    [[TMP1:%.*]] = shl nuw i64 [[TMP0]], 2
; UNMASKED-SVE2P1-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 [[UMAX]], [[TMP1]]
; UNMASKED-SVE2P1-NEXT:    br i1 [[MIN_ITERS_CHECK]], [[SCALAR_PH:label %.*]], label %[[VECTOR_PH:.*]]
; UNMASKED-SVE2P1:       [[VECTOR_PH]]:
; UNMASKED-SVE2P1-NEXT:    [[TMP2:%.*]] = shl nuw i64 [[TMP0]], 2
; UNMASKED-SVE2P1-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[UMAX]], [[TMP2]]
; UNMASKED-SVE2P1-NEXT:    [[N_VEC:%.*]] = sub i64 [[UMAX]], [[N_MOD_VF]]
; UNMASKED-SVE2P1-NEXT:    br label %[[VECTOR_BODY:.*]]
; UNMASKED-SVE2P1:       [[VECTOR_BODY]]:
; UNMASKED-SVE2P1-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; UNMASKED-SVE2P1-NEXT:    [[VEC_PHI:%.*]] = phi <vscale x 2 x i64> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP6:%.*]], %[[VECTOR_BODY]] ]
; UNMASKED-SVE2P1-NEXT:    [[VEC_PHI1:%.*]] = phi <vscale x 2 x i64> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP7:%.*]], %[[VECTOR_BODY]] ]
; UNMASKED-SVE2P1-NEXT:    [[TMP3:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[INDEX]]
; UNMASKED-SVE2P1-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 4 x i64>, ptr [[TMP3]], align 8
; UNMASKED-SVE2P1-NEXT:    [[TMP4:%.*]] = call <vscale x 2 x i64> @llvm.vector.extract.nxv2i64.nxv4i64(<vscale x 4 x i64> [[WIDE_LOAD]], i64 0)
; UNMASKED-SVE2P1-NEXT:    [[TMP5:%.*]] = call <vscale x 2 x i64> @llvm.vector.extract.nxv2i64.nxv4i64(<vscale x 4 x i64> [[WIDE_LOAD]], i64 2)
; UNMASKED-SVE2P1-NEXT:    [[TMP6]] = add <vscale x 2 x i64> [[VEC_PHI]], [[TMP4]]
; UNMASKED-SVE2P1-NEXT:    [[TMP7]] = add <vscale x 2 x i64> [[VEC_PHI1]], [[TMP5]]
; UNMASKED-SVE2P1-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP2]]
; UNMASKED-SVE2P1-NEXT:    [[TMP8:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; UNMASKED-SVE2P1-NEXT:    br i1 [[TMP8]], label %[[EXIT:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP7:![0-9]+]]
; UNMASKED-SVE2P1:       [[EXIT]]:
;
; UNMASKED-SVE-LABEL: define i64 @i64_sum_reduction_scaled_partial_reduce(
; UNMASKED-SVE-SAME: ptr noalias [[A:%.*]], i64 [[N:%.*]]) #[[ATTR0]] {
; UNMASKED-SVE-NEXT:  [[ENTRY:.*:]]
; UNMASKED-SVE-NEXT:    [[UMAX:%.*]] = call i64 @llvm.umax.i64(i64 [[N]], i64 1)
; UNMASKED-SVE-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; UNMASKED-SVE-NEXT:    [[TMP1:%.*]] = shl nuw i64 [[TMP0]], 2
; UNMASKED-SVE-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 [[UMAX]], [[TMP1]]
; UNMASKED-SVE-NEXT:    br i1 [[MIN_ITERS_CHECK]], [[SCALAR_PH:label %.*]], label %[[VECTOR_PH:.*]]
; UNMASKED-SVE:       [[VECTOR_PH]]:
; UNMASKED-SVE-NEXT:    [[TMP2:%.*]] = shl nuw i64 [[TMP0]], 1
; UNMASKED-SVE-NEXT:    [[TMP3:%.*]] = shl nuw i64 [[TMP2]], 1
; UNMASKED-SVE-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[UMAX]], [[TMP3]]
; UNMASKED-SVE-NEXT:    [[N_VEC:%.*]] = sub i64 [[UMAX]], [[N_MOD_VF]]
; UNMASKED-SVE-NEXT:    br label %[[VECTOR_BODY:.*]]
; UNMASKED-SVE:       [[VECTOR_BODY]]:
; UNMASKED-SVE-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; UNMASKED-SVE-NEXT:    [[VEC_PHI:%.*]] = phi <vscale x 2 x i64> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP6:%.*]], %[[VECTOR_BODY]] ]
; UNMASKED-SVE-NEXT:    [[VEC_PHI1:%.*]] = phi <vscale x 2 x i64> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP7:%.*]], %[[VECTOR_BODY]] ]
; UNMASKED-SVE-NEXT:    [[TMP4:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[INDEX]]
; UNMASKED-SVE-NEXT:    [[TMP5:%.*]] = getelementptr inbounds i64, ptr [[TMP4]], i64 [[TMP2]]
; UNMASKED-SVE-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 2 x i64>, ptr [[TMP4]], align 8
; UNMASKED-SVE-NEXT:    [[WIDE_LOAD2:%.*]] = load <vscale x 2 x i64>, ptr [[TMP5]], align 8
; UNMASKED-SVE-NEXT:    [[TMP6]] = add <vscale x 2 x i64> [[VEC_PHI]], [[WIDE_LOAD]]
; UNMASKED-SVE-NEXT:    [[TMP7]] = add <vscale x 2 x i64> [[VEC_PHI1]], [[WIDE_LOAD2]]
; UNMASKED-SVE-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP3]]
; UNMASKED-SVE-NEXT:    [[TMP8:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; UNMASKED-SVE-NEXT:    br i1 [[TMP8]], label %[[EXIT:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP7:![0-9]+]]
; UNMASKED-SVE:       [[EXIT]]:
;
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %next, %loop ]
  %acc = phi i64 [ 0, %entry ], [ %sum, %loop ]
  %p = getelementptr inbounds i64, ptr %a, i64 %iv
  %ld = load i64, ptr %p, align 8
  %sum = add i64 %acc, %ld
  %next = add nuw i64 %iv, 1
  %cmp = icmp ult i64 %next, %n
  br i1 %cmp, label %loop, label %exit

exit:
  ret i64 %sum
}

; Find-last style reduction with a scalable i64 load.
define i64 @find_last_i64_scaled_load(i64 %n, ptr noalias %data, i64 %threshold) {
; MASKED-SVE2P1-LABEL: define i64 @find_last_i64_scaled_load(
; MASKED-SVE2P1-SAME: i64 [[N:%.*]], ptr noalias [[DATA:%.*]], i64 [[THRESHOLD:%.*]]) #[[ATTR0]] {
; MASKED-SVE2P1-NEXT:  [[ENTRY:.*:]]
; MASKED-SVE2P1-NEXT:    br label %[[VECTOR_PH:.*]]
; MASKED-SVE2P1:       [[VECTOR_PH]]:
; MASKED-SVE2P1-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; MASKED-SVE2P1-NEXT:    [[TMP1:%.*]] = shl nuw i64 [[TMP0]], 2
; MASKED-SVE2P1-NEXT:    [[ACTIVE_LANE_MASK_ENTRY:%.*]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.for.type.nxv4i1.i64(i64 0, i64 [[N]], i64 8)
; MASKED-SVE2P1-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <vscale x 2 x i64> poison, i64 [[THRESHOLD]], i64 0
; MASKED-SVE2P1-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <vscale x 2 x i64> [[BROADCAST_SPLATINSERT]], <vscale x 2 x i64> poison, <vscale x 2 x i32> zeroinitializer
; MASKED-SVE2P1-NEXT:    br label %[[VECTOR_BODY:.*]]
; MASKED-SVE2P1:       [[VECTOR_BODY]]:
; MASKED-SVE2P1-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; MASKED-SVE2P1-NEXT:    [[ACTIVE_LANE_MASK:%.*]] = phi <vscale x 4 x i1> [ [[ACTIVE_LANE_MASK_ENTRY]], %[[VECTOR_PH]] ], [ [[ACTIVE_LANE_MASK_NEXT:%.*]], %[[VECTOR_BODY]] ]
; MASKED-SVE2P1-NEXT:    [[VEC_PHI:%.*]] = phi <vscale x 2 x i64> [ splat (i64 -1), %[[VECTOR_PH]] ], [ [[TMP19:%.*]], %[[VECTOR_BODY]] ]
; MASKED-SVE2P1-NEXT:    [[VEC_PHI1:%.*]] = phi <vscale x 2 x i64> [ splat (i64 -1), %[[VECTOR_PH]] ], [ [[TMP20:%.*]], %[[VECTOR_BODY]] ]
; MASKED-SVE2P1-NEXT:    [[TMP2:%.*]] = phi <vscale x 2 x i1> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP17:%.*]], %[[VECTOR_BODY]] ]
; MASKED-SVE2P1-NEXT:    [[TMP3:%.*]] = phi <vscale x 2 x i1> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP18:%.*]], %[[VECTOR_BODY]] ]
; MASKED-SVE2P1-NEXT:    [[TMP4:%.*]] = call <vscale x 2 x i1> @llvm.vector.extract.nxv2i1.nxv4i1(<vscale x 4 x i1> [[ACTIVE_LANE_MASK]], i64 0)
; MASKED-SVE2P1-NEXT:    [[TMP5:%.*]] = call <vscale x 2 x i1> @llvm.vector.extract.nxv2i1.nxv4i1(<vscale x 4 x i1> [[ACTIVE_LANE_MASK]], i64 2)
; MASKED-SVE2P1-NEXT:    [[TMP6:%.*]] = getelementptr inbounds i64, ptr [[DATA]], i64 [[INDEX]]
; MASKED-SVE2P1-NEXT:    [[WIDE_MASKED_LOAD:%.*]] = call <vscale x 4 x i64> @llvm.masked.load.nxv4i64.p0(ptr align 8 [[TMP6]], <vscale x 4 x i1> [[ACTIVE_LANE_MASK]], <vscale x 4 x i64> poison)
; MASKED-SVE2P1-NEXT:    [[TMP7:%.*]] = call <vscale x 2 x i64> @llvm.vector.extract.nxv2i64.nxv4i64(<vscale x 4 x i64> [[WIDE_MASKED_LOAD]], i64 0)
; MASKED-SVE2P1-NEXT:    [[TMP8:%.*]] = call <vscale x 2 x i64> @llvm.vector.extract.nxv2i64.nxv4i64(<vscale x 4 x i64> [[WIDE_MASKED_LOAD]], i64 2)
; MASKED-SVE2P1-NEXT:    [[TMP9:%.*]] = icmp slt <vscale x 2 x i64> [[BROADCAST_SPLAT]], [[TMP7]]
; MASKED-SVE2P1-NEXT:    [[TMP10:%.*]] = icmp slt <vscale x 2 x i64> [[BROADCAST_SPLAT]], [[TMP8]]
; MASKED-SVE2P1-NEXT:    [[TMP11:%.*]] = select <vscale x 2 x i1> [[TMP4]], <vscale x 2 x i1> [[TMP9]], <vscale x 2 x i1> zeroinitializer
; MASKED-SVE2P1-NEXT:    [[TMP12:%.*]] = select <vscale x 2 x i1> [[TMP5]], <vscale x 2 x i1> [[TMP10]], <vscale x 2 x i1> zeroinitializer
; MASKED-SVE2P1-NEXT:    [[TMP13:%.*]] = freeze <vscale x 2 x i1> [[TMP11]]
; MASKED-SVE2P1-NEXT:    [[TMP14:%.*]] = freeze <vscale x 2 x i1> [[TMP12]]
; MASKED-SVE2P1-NEXT:    [[TMP15:%.*]] = or <vscale x 2 x i1> [[TMP13]], [[TMP14]]
; MASKED-SVE2P1-NEXT:    [[TMP16:%.*]] = call i1 @llvm.vector.reduce.or.nxv2i1(<vscale x 2 x i1> [[TMP15]])
; MASKED-SVE2P1-NEXT:    [[TMP17]] = select i1 [[TMP16]], <vscale x 2 x i1> [[TMP11]], <vscale x 2 x i1> [[TMP2]]
; MASKED-SVE2P1-NEXT:    [[TMP18]] = select i1 [[TMP16]], <vscale x 2 x i1> [[TMP12]], <vscale x 2 x i1> [[TMP3]]
; MASKED-SVE2P1-NEXT:    [[TMP19]] = select i1 [[TMP16]], <vscale x 2 x i64> [[TMP7]], <vscale x 2 x i64> [[VEC_PHI]]
; MASKED-SVE2P1-NEXT:    [[TMP20]] = select i1 [[TMP16]], <vscale x 2 x i64> [[TMP8]], <vscale x 2 x i64> [[VEC_PHI1]]
; MASKED-SVE2P1-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], [[TMP1]]
; MASKED-SVE2P1-NEXT:    [[ACTIVE_LANE_MASK_NEXT]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.for.type.nxv4i1.i64(i64 [[INDEX_NEXT]], i64 [[N]], i64 8)
; MASKED-SVE2P1-NEXT:    [[TMP21:%.*]] = extractelement <vscale x 4 x i1> [[ACTIVE_LANE_MASK_NEXT]], i64 0
; MASKED-SVE2P1-NEXT:    [[TMP22:%.*]] = xor i1 [[TMP21]], true
; MASKED-SVE2P1-NEXT:    br i1 [[TMP22]], label %[[EXIT:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP6:![0-9]+]]
; MASKED-SVE2P1:       [[EXIT]]:
;
; MASKED-SVE-LABEL: define i64 @find_last_i64_scaled_load(
; MASKED-SVE-SAME: i64 [[N:%.*]], ptr noalias [[DATA:%.*]], i64 [[THRESHOLD:%.*]]) #[[ATTR0]] {
; MASKED-SVE-NEXT:  [[ENTRY:.*:]]
; MASKED-SVE-NEXT:    br label %[[VECTOR_PH:.*]]
; MASKED-SVE:       [[VECTOR_PH]]:
; MASKED-SVE-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; MASKED-SVE-NEXT:    [[TMP1:%.*]] = shl nuw i64 [[TMP0]], 1
; MASKED-SVE-NEXT:    [[TMP2:%.*]] = shl nuw i64 [[TMP1]], 1
; MASKED-SVE-NEXT:    [[ACTIVE_LANE_MASK_ENTRY:%.*]] = call <vscale x 2 x i1> @llvm.get.active.lane.mask.nxv2i1.i64(i64 0, i64 [[N]])
; MASKED-SVE-NEXT:    [[ACTIVE_LANE_MASK_ENTRY1:%.*]] = call <vscale x 2 x i1> @llvm.get.active.lane.mask.nxv2i1.i64(i64 [[TMP1]], i64 [[N]])
; MASKED-SVE-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <vscale x 2 x i64> poison, i64 [[THRESHOLD]], i64 0
; MASKED-SVE-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <vscale x 2 x i64> [[BROADCAST_SPLATINSERT]], <vscale x 2 x i64> poison, <vscale x 2 x i32> zeroinitializer
; MASKED-SVE-NEXT:    br label %[[VECTOR_BODY:.*]]
; MASKED-SVE:       [[VECTOR_BODY]]:
; MASKED-SVE-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; MASKED-SVE-NEXT:    [[ACTIVE_LANE_MASK:%.*]] = phi <vscale x 2 x i1> [ [[ACTIVE_LANE_MASK_ENTRY]], %[[VECTOR_PH]] ], [ [[ACTIVE_LANE_MASK_NEXT:%.*]], %[[VECTOR_BODY]] ]
; MASKED-SVE-NEXT:    [[ACTIVE_LANE_MASK2:%.*]] = phi <vscale x 2 x i1> [ [[ACTIVE_LANE_MASK_ENTRY1]], %[[VECTOR_PH]] ], [ [[ACTIVE_LANE_MASK_NEXT5:%.*]], %[[VECTOR_BODY]] ]
; MASKED-SVE-NEXT:    [[VEC_PHI:%.*]] = phi <vscale x 2 x i64> [ splat (i64 -1), %[[VECTOR_PH]] ], [ [[TMP17:%.*]], %[[VECTOR_BODY]] ]
; MASKED-SVE-NEXT:    [[VEC_PHI3:%.*]] = phi <vscale x 2 x i64> [ splat (i64 -1), %[[VECTOR_PH]] ], [ [[TMP18:%.*]], %[[VECTOR_BODY]] ]
; MASKED-SVE-NEXT:    [[TMP3:%.*]] = phi <vscale x 2 x i1> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP15:%.*]], %[[VECTOR_BODY]] ]
; MASKED-SVE-NEXT:    [[TMP4:%.*]] = phi <vscale x 2 x i1> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP16:%.*]], %[[VECTOR_BODY]] ]
; MASKED-SVE-NEXT:    [[TMP5:%.*]] = getelementptr inbounds i64, ptr [[DATA]], i64 [[INDEX]]
; MASKED-SVE-NEXT:    [[TMP6:%.*]] = getelementptr inbounds i64, ptr [[TMP5]], i64 [[TMP1]]
; MASKED-SVE-NEXT:    [[WIDE_MASKED_LOAD:%.*]] = call <vscale x 2 x i64> @llvm.masked.load.nxv2i64.p0(ptr align 8 [[TMP5]], <vscale x 2 x i1> [[ACTIVE_LANE_MASK]], <vscale x 2 x i64> poison)
; MASKED-SVE-NEXT:    [[WIDE_MASKED_LOAD4:%.*]] = call <vscale x 2 x i64> @llvm.masked.load.nxv2i64.p0(ptr align 8 [[TMP6]], <vscale x 2 x i1> [[ACTIVE_LANE_MASK2]], <vscale x 2 x i64> poison)
; MASKED-SVE-NEXT:    [[TMP7:%.*]] = icmp slt <vscale x 2 x i64> [[BROADCAST_SPLAT]], [[WIDE_MASKED_LOAD]]
; MASKED-SVE-NEXT:    [[TMP8:%.*]] = icmp slt <vscale x 2 x i64> [[BROADCAST_SPLAT]], [[WIDE_MASKED_LOAD4]]
; MASKED-SVE-NEXT:    [[TMP9:%.*]] = select <vscale x 2 x i1> [[ACTIVE_LANE_MASK]], <vscale x 2 x i1> [[TMP7]], <vscale x 2 x i1> zeroinitializer
; MASKED-SVE-NEXT:    [[TMP10:%.*]] = select <vscale x 2 x i1> [[ACTIVE_LANE_MASK2]], <vscale x 2 x i1> [[TMP8]], <vscale x 2 x i1> zeroinitializer
; MASKED-SVE-NEXT:    [[TMP11:%.*]] = freeze <vscale x 2 x i1> [[TMP9]]
; MASKED-SVE-NEXT:    [[TMP12:%.*]] = freeze <vscale x 2 x i1> [[TMP10]]
; MASKED-SVE-NEXT:    [[TMP13:%.*]] = or <vscale x 2 x i1> [[TMP11]], [[TMP12]]
; MASKED-SVE-NEXT:    [[TMP14:%.*]] = call i1 @llvm.vector.reduce.or.nxv2i1(<vscale x 2 x i1> [[TMP13]])
; MASKED-SVE-NEXT:    [[TMP15]] = select i1 [[TMP14]], <vscale x 2 x i1> [[TMP9]], <vscale x 2 x i1> [[TMP3]]
; MASKED-SVE-NEXT:    [[TMP16]] = select i1 [[TMP14]], <vscale x 2 x i1> [[TMP10]], <vscale x 2 x i1> [[TMP4]]
; MASKED-SVE-NEXT:    [[TMP17]] = select i1 [[TMP14]], <vscale x 2 x i64> [[WIDE_MASKED_LOAD]], <vscale x 2 x i64> [[VEC_PHI]]
; MASKED-SVE-NEXT:    [[TMP18]] = select i1 [[TMP14]], <vscale x 2 x i64> [[WIDE_MASKED_LOAD4]], <vscale x 2 x i64> [[VEC_PHI3]]
; MASKED-SVE-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], [[TMP2]]
; MASKED-SVE-NEXT:    [[TMP19:%.*]] = add i64 [[INDEX_NEXT]], [[TMP1]]
; MASKED-SVE-NEXT:    [[ACTIVE_LANE_MASK_NEXT]] = call <vscale x 2 x i1> @llvm.get.active.lane.mask.nxv2i1.i64(i64 [[INDEX_NEXT]], i64 [[N]])
; MASKED-SVE-NEXT:    [[ACTIVE_LANE_MASK_NEXT5]] = call <vscale x 2 x i1> @llvm.get.active.lane.mask.nxv2i1.i64(i64 [[TMP19]], i64 [[N]])
; MASKED-SVE-NEXT:    [[TMP20:%.*]] = extractelement <vscale x 2 x i1> [[ACTIVE_LANE_MASK_NEXT]], i64 0
; MASKED-SVE-NEXT:    [[TMP21:%.*]] = xor i1 [[TMP20]], true
; MASKED-SVE-NEXT:    br i1 [[TMP21]], label %[[EXIT:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP6:![0-9]+]]
; MASKED-SVE:       [[EXIT]]:
;
; UNMASKED-SVE2P1-LABEL: define i64 @find_last_i64_scaled_load(
; UNMASKED-SVE2P1-SAME: i64 [[N:%.*]], ptr noalias [[DATA:%.*]], i64 [[THRESHOLD:%.*]]) #[[ATTR0]] {
; UNMASKED-SVE2P1-NEXT:  [[ENTRY:.*:]]
; UNMASKED-SVE2P1-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; UNMASKED-SVE2P1-NEXT:    [[TMP1:%.*]] = shl nuw i64 [[TMP0]], 2
; UNMASKED-SVE2P1-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 [[N]], [[TMP1]]
; UNMASKED-SVE2P1-NEXT:    br i1 [[MIN_ITERS_CHECK]], [[SCALAR_PH:label %.*]], label %[[VECTOR_PH:.*]]
; UNMASKED-SVE2P1:       [[VECTOR_PH]]:
; UNMASKED-SVE2P1-NEXT:    [[TMP2:%.*]] = shl nuw i64 [[TMP0]], 2
; UNMASKED-SVE2P1-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[N]], [[TMP2]]
; UNMASKED-SVE2P1-NEXT:    [[N_VEC:%.*]] = sub i64 [[N]], [[N_MOD_VF]]
; UNMASKED-SVE2P1-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <vscale x 2 x i64> poison, i64 [[THRESHOLD]], i64 0
; UNMASKED-SVE2P1-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <vscale x 2 x i64> [[BROADCAST_SPLATINSERT]], <vscale x 2 x i64> poison, <vscale x 2 x i32> zeroinitializer
; UNMASKED-SVE2P1-NEXT:    br label %[[VECTOR_BODY:.*]]
; UNMASKED-SVE2P1:       [[VECTOR_BODY]]:
; UNMASKED-SVE2P1-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; UNMASKED-SVE2P1-NEXT:    [[VEC_PHI:%.*]] = phi <vscale x 2 x i64> [ splat (i64 -1), %[[VECTOR_PH]] ], [ [[TMP16:%.*]], %[[VECTOR_BODY]] ]
; UNMASKED-SVE2P1-NEXT:    [[VEC_PHI1:%.*]] = phi <vscale x 2 x i64> [ splat (i64 -1), %[[VECTOR_PH]] ], [ [[TMP17:%.*]], %[[VECTOR_BODY]] ]
; UNMASKED-SVE2P1-NEXT:    [[TMP3:%.*]] = phi <vscale x 2 x i1> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP14:%.*]], %[[VECTOR_BODY]] ]
; UNMASKED-SVE2P1-NEXT:    [[TMP4:%.*]] = phi <vscale x 2 x i1> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP15:%.*]], %[[VECTOR_BODY]] ]
; UNMASKED-SVE2P1-NEXT:    [[TMP5:%.*]] = getelementptr inbounds i64, ptr [[DATA]], i64 [[INDEX]]
; UNMASKED-SVE2P1-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 4 x i64>, ptr [[TMP5]], align 8
; UNMASKED-SVE2P1-NEXT:    [[TMP6:%.*]] = call <vscale x 2 x i64> @llvm.vector.extract.nxv2i64.nxv4i64(<vscale x 4 x i64> [[WIDE_LOAD]], i64 0)
; UNMASKED-SVE2P1-NEXT:    [[TMP7:%.*]] = call <vscale x 2 x i64> @llvm.vector.extract.nxv2i64.nxv4i64(<vscale x 4 x i64> [[WIDE_LOAD]], i64 2)
; UNMASKED-SVE2P1-NEXT:    [[TMP8:%.*]] = icmp slt <vscale x 2 x i64> [[BROADCAST_SPLAT]], [[TMP6]]
; UNMASKED-SVE2P1-NEXT:    [[TMP9:%.*]] = icmp slt <vscale x 2 x i64> [[BROADCAST_SPLAT]], [[TMP7]]
; UNMASKED-SVE2P1-NEXT:    [[TMP10:%.*]] = freeze <vscale x 2 x i1> [[TMP8]]
; UNMASKED-SVE2P1-NEXT:    [[TMP11:%.*]] = freeze <vscale x 2 x i1> [[TMP9]]
; UNMASKED-SVE2P1-NEXT:    [[TMP12:%.*]] = or <vscale x 2 x i1> [[TMP10]], [[TMP11]]
; UNMASKED-SVE2P1-NEXT:    [[TMP13:%.*]] = call i1 @llvm.vector.reduce.or.nxv2i1(<vscale x 2 x i1> [[TMP12]])
; UNMASKED-SVE2P1-NEXT:    [[TMP14]] = select i1 [[TMP13]], <vscale x 2 x i1> [[TMP8]], <vscale x 2 x i1> [[TMP3]]
; UNMASKED-SVE2P1-NEXT:    [[TMP15]] = select i1 [[TMP13]], <vscale x 2 x i1> [[TMP9]], <vscale x 2 x i1> [[TMP4]]
; UNMASKED-SVE2P1-NEXT:    [[TMP16]] = select i1 [[TMP13]], <vscale x 2 x i64> [[TMP6]], <vscale x 2 x i64> [[VEC_PHI]]
; UNMASKED-SVE2P1-NEXT:    [[TMP17]] = select i1 [[TMP13]], <vscale x 2 x i64> [[TMP7]], <vscale x 2 x i64> [[VEC_PHI1]]
; UNMASKED-SVE2P1-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP2]]
; UNMASKED-SVE2P1-NEXT:    [[TMP18:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; UNMASKED-SVE2P1-NEXT:    br i1 [[TMP18]], label %[[EXIT:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP9:![0-9]+]]
; UNMASKED-SVE2P1:       [[EXIT]]:
;
; UNMASKED-SVE-LABEL: define i64 @find_last_i64_scaled_load(
; UNMASKED-SVE-SAME: i64 [[N:%.*]], ptr noalias [[DATA:%.*]], i64 [[THRESHOLD:%.*]]) #[[ATTR0]] {
; UNMASKED-SVE-NEXT:  [[ENTRY:.*:]]
; UNMASKED-SVE-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; UNMASKED-SVE-NEXT:    [[TMP1:%.*]] = shl nuw i64 [[TMP0]], 2
; UNMASKED-SVE-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 [[N]], [[TMP1]]
; UNMASKED-SVE-NEXT:    br i1 [[MIN_ITERS_CHECK]], [[SCALAR_PH:label %.*]], label %[[VECTOR_PH:.*]]
; UNMASKED-SVE:       [[VECTOR_PH]]:
; UNMASKED-SVE-NEXT:    [[TMP2:%.*]] = shl nuw i64 [[TMP0]], 1
; UNMASKED-SVE-NEXT:    [[TMP3:%.*]] = shl nuw i64 [[TMP2]], 1
; UNMASKED-SVE-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[N]], [[TMP3]]
; UNMASKED-SVE-NEXT:    [[N_VEC:%.*]] = sub i64 [[N]], [[N_MOD_VF]]
; UNMASKED-SVE-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <vscale x 2 x i64> poison, i64 [[THRESHOLD]], i64 0
; UNMASKED-SVE-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <vscale x 2 x i64> [[BROADCAST_SPLATINSERT]], <vscale x 2 x i64> poison, <vscale x 2 x i32> zeroinitializer
; UNMASKED-SVE-NEXT:    br label %[[VECTOR_BODY:.*]]
; UNMASKED-SVE:       [[VECTOR_BODY]]:
; UNMASKED-SVE-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; UNMASKED-SVE-NEXT:    [[VEC_PHI:%.*]] = phi <vscale x 2 x i64> [ splat (i64 -1), %[[VECTOR_PH]] ], [ [[TMP16:%.*]], %[[VECTOR_BODY]] ]
; UNMASKED-SVE-NEXT:    [[VEC_PHI1:%.*]] = phi <vscale x 2 x i64> [ splat (i64 -1), %[[VECTOR_PH]] ], [ [[TMP17:%.*]], %[[VECTOR_BODY]] ]
; UNMASKED-SVE-NEXT:    [[TMP4:%.*]] = phi <vscale x 2 x i1> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP14:%.*]], %[[VECTOR_BODY]] ]
; UNMASKED-SVE-NEXT:    [[TMP5:%.*]] = phi <vscale x 2 x i1> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP15:%.*]], %[[VECTOR_BODY]] ]
; UNMASKED-SVE-NEXT:    [[TMP6:%.*]] = getelementptr inbounds i64, ptr [[DATA]], i64 [[INDEX]]
; UNMASKED-SVE-NEXT:    [[TMP7:%.*]] = getelementptr inbounds i64, ptr [[TMP6]], i64 [[TMP2]]
; UNMASKED-SVE-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 2 x i64>, ptr [[TMP6]], align 8
; UNMASKED-SVE-NEXT:    [[WIDE_LOAD2:%.*]] = load <vscale x 2 x i64>, ptr [[TMP7]], align 8
; UNMASKED-SVE-NEXT:    [[TMP8:%.*]] = icmp slt <vscale x 2 x i64> [[BROADCAST_SPLAT]], [[WIDE_LOAD]]
; UNMASKED-SVE-NEXT:    [[TMP9:%.*]] = icmp slt <vscale x 2 x i64> [[BROADCAST_SPLAT]], [[WIDE_LOAD2]]
; UNMASKED-SVE-NEXT:    [[TMP10:%.*]] = freeze <vscale x 2 x i1> [[TMP8]]
; UNMASKED-SVE-NEXT:    [[TMP11:%.*]] = freeze <vscale x 2 x i1> [[TMP9]]
; UNMASKED-SVE-NEXT:    [[TMP12:%.*]] = or <vscale x 2 x i1> [[TMP10]], [[TMP11]]
; UNMASKED-SVE-NEXT:    [[TMP13:%.*]] = call i1 @llvm.vector.reduce.or.nxv2i1(<vscale x 2 x i1> [[TMP12]])
; UNMASKED-SVE-NEXT:    [[TMP14]] = select i1 [[TMP13]], <vscale x 2 x i1> [[TMP8]], <vscale x 2 x i1> [[TMP4]]
; UNMASKED-SVE-NEXT:    [[TMP15]] = select i1 [[TMP13]], <vscale x 2 x i1> [[TMP9]], <vscale x 2 x i1> [[TMP5]]
; UNMASKED-SVE-NEXT:    [[TMP16]] = select i1 [[TMP13]], <vscale x 2 x i64> [[WIDE_LOAD]], <vscale x 2 x i64> [[VEC_PHI]]
; UNMASKED-SVE-NEXT:    [[TMP17]] = select i1 [[TMP13]], <vscale x 2 x i64> [[WIDE_LOAD2]], <vscale x 2 x i64> [[VEC_PHI1]]
; UNMASKED-SVE-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP3]]
; UNMASKED-SVE-NEXT:    [[TMP18:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; UNMASKED-SVE-NEXT:    br i1 [[TMP18]], label %[[EXIT:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP9:![0-9]+]]
; UNMASKED-SVE:       [[EXIT]]:
;
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %next, %loop ]
  %data.phi = phi i64 [ -1, %entry ], [ %select.data, %loop ]
  %p = getelementptr inbounds i64, ptr %data, i64 %iv
  %ld = load i64, ptr %p, align 8
  %select.cmp = icmp slt i64 %threshold, %ld
  %select.data = select i1 %select.cmp, i64 %ld, i64 %data.phi
  %next = add nuw i64 %iv, 1
  %exit.cmp = icmp eq i64 %next, %n
  br i1 %exit.cmp, label %exit, label %loop

exit:
  ret i64 %select.data
}

!0 = distinct !{!0, !1, !2, !3}
!5 = distinct !{!5, !1, !2, !3}
!6 = distinct !{!6, !1, !2, !3}
!1 = !{!"llvm.loop.vectorize.enable", i1 true}
!2 = !{!"llvm.loop.vectorize.width", i32 4}
!3 = !{!"llvm.loop.vectorize.scalable.enable", i1 true}
