; NOTE: Assertions have been autogenerated by utils/update_analyze_test_checks.py UTC_ARGS: --filter-out-after "middle.block:" --version 6
; DEFINE: %{compile} = opt -passes=loop-vectorize -mtriple=aarch64-linux-gnu -mattr=+sve2p1 -force-vector-interleave=2 -tail-folding-policy=must-fold-tail -force-wide-mem-ops -disable-output -S %s
; RUN: %{compile} -vplan-print-before="scaleMemoryAccessesByUF$" 2>&1 \
; RUN:   | FileCheck --check-prefix=BEFORE-SCALE %s
; RUN: %{compile} -vplan-print-after="scaleMemoryAccessesByUF$" 2>&1 \
; RUN:   | FileCheck --check-prefix=AFTER-SCALE %s
; RUN: %{compile} -vplan-print-after="unrollByUF$" 2>&1 \
; RUN:   | FileCheck --check-prefix=AFTER-UNROLL %s

define void @masked_i64_load_store(ptr noalias %x, i64 %n) {
; BEFORE-SCALE-LABEL: VPlan for loop in 'masked_i64_load_store'
; BEFORE-SCALE:  VPlan 'Initial VPlan for VF={vscale x 4},UF>=1' {
; BEFORE-SCALE-NEXT:  Live-in vp<[[VP0:%[0-9]+]]> = VF
; BEFORE-SCALE-NEXT:  Live-in vp<[[VP1:%[0-9]+]]> = VF * UF
; BEFORE-SCALE-NEXT:  vp<[[VP4:%[0-9]+]]> = original trip-count
; BEFORE-SCALE-EMPTY:
; BEFORE-SCALE-NEXT:  ir-bb<entry>:
; BEFORE-SCALE-NEXT:    EMIT vp<[[VP4]]> = EXPAND SCEV (1 umax %n)
; BEFORE-SCALE-NEXT:    EMIT branch-on-cond ir<false>
; BEFORE-SCALE-NEXT:  Successor(s): scalar.ph, vector.ph
; BEFORE-SCALE-EMPTY:
; BEFORE-SCALE-NEXT:  vector.ph:
; BEFORE-SCALE-NEXT:    EMIT vp<%index.part.next> = VF * Part + ir<0>, vp<[[VP0]]>
; BEFORE-SCALE-NEXT:    EMIT vp<%active.lane.mask.entry> = active lane mask vp<%index.part.next>, vp<[[VP4]]>, ir<1>, ir<0>
; BEFORE-SCALE-NEXT:  Successor(s): vector loop
; BEFORE-SCALE-EMPTY:
; BEFORE-SCALE-NEXT:  <x1> vector loop: {
; BEFORE-SCALE-NEXT:  vp<[[VP6:%[0-9]+]]> = CANONICAL-IV
; BEFORE-SCALE-EMPTY:
; BEFORE-SCALE-NEXT:    vector.body:
; BEFORE-SCALE-NEXT:      ACTIVE-LANE-MASK-PHI vp<[[VP7:%[0-9]+]]> = phi vp<%active.lane.mask.entry>, vp<%active.lane.mask.next>
; BEFORE-SCALE-NEXT:      vp<[[VP8:%[0-9]+]]> = SCALAR-STEPS vp<[[VP6]]>, ir<1>, vp<[[VP0]]>
; BEFORE-SCALE-NEXT:      CLONE ir<%ptr> = getelementptr inbounds ir<%x>, vp<[[VP8]]>
; BEFORE-SCALE-NEXT:      vp<[[VP9:%[0-9]+]]> = vector-pointer inbounds ir<%ptr>, ir<1>
; BEFORE-SCALE-NEXT:      WIDEN ir<%ld> = load vp<[[VP9]]>, vp<[[VP7]]>
; BEFORE-SCALE-NEXT:      WIDEN ir<%add> = add ir<%ld>, ir<1>
; BEFORE-SCALE-NEXT:      vp<[[VP10:%[0-9]+]]> = vector-pointer inbounds ir<%ptr>, ir<1>
; BEFORE-SCALE-NEXT:      WIDEN store vp<[[VP10]]>, ir<%add>, vp<[[VP7]]>
; BEFORE-SCALE-NEXT:      EMIT vp<%index.next> = add vp<[[VP6]]>, vp<[[VP1]]>
; BEFORE-SCALE-NEXT:      EMIT vp<[[VP11:%[0-9]+]]> = VF * Part + vp<%index.next>, vp<[[VP0]]>
; BEFORE-SCALE-NEXT:      EMIT vp<%active.lane.mask.next> = active lane mask vp<[[VP11]]>, vp<[[VP4]]>, ir<1>, ir<0>
; BEFORE-SCALE-NEXT:      EMIT vp<[[VP12:%[0-9]+]]> = not vp<%active.lane.mask.next>
; BEFORE-SCALE-NEXT:      EMIT branch-on-cond vp<[[VP12]]>
; BEFORE-SCALE-NEXT:    No successors
; BEFORE-SCALE-NEXT:  }
; BEFORE-SCALE-NEXT:  Successor(s): middle.block
; BEFORE-SCALE-EMPTY:
; BEFORE-SCALE-NEXT:  middle.block:
;
; AFTER-SCALE-LABEL: VPlan for loop in 'masked_i64_load_store'
; AFTER-SCALE:  VPlan 'Initial VPlan for VF={vscale x 4},UF>=1' {
; AFTER-SCALE-NEXT:  Live-in vp<[[VP0:%[0-9]+]]> = VF
; AFTER-SCALE-NEXT:  Live-in vp<[[VP1:%[0-9]+]]> = VF * UF
; AFTER-SCALE-NEXT:  vp<[[VP4:%[0-9]+]]> = original trip-count
; AFTER-SCALE-EMPTY:
; AFTER-SCALE-NEXT:  ir-bb<entry>:
; AFTER-SCALE-NEXT:    EMIT vp<[[VP4]]> = EXPAND SCEV (1 umax %n)
; AFTER-SCALE-NEXT:    EMIT branch-on-cond ir<false>
; AFTER-SCALE-NEXT:  Successor(s): scalar.ph, vector.ph
; AFTER-SCALE-EMPTY:
; AFTER-SCALE-NEXT:  vector.ph:
; AFTER-SCALE-NEXT:    EMIT vp<%index.part.next> = VF * Part + ir<0>, vp<[[VP0]]>
; AFTER-SCALE-NEXT:    EMIT vp<%active.lane.mask.entry> = active lane mask vp<%index.part.next>, vp<[[VP4]]>, ir<2>, ir<8>
; AFTER-SCALE-NEXT:  Successor(s): vector loop
; AFTER-SCALE-EMPTY:
; AFTER-SCALE-NEXT:  <x1> vector loop: {
; AFTER-SCALE-NEXT:  vp<[[VP6:%[0-9]+]]> = CANONICAL-IV
; AFTER-SCALE-EMPTY:
; AFTER-SCALE-NEXT:    vector.body:
; AFTER-SCALE-NEXT:      ACTIVE-LANE-MASK-PHI vp<[[VP7:%[0-9]+]]> = phi vp<%active.lane.mask.entry>, vp<%active.lane.mask.next>
; AFTER-SCALE-NEXT:      EMIT vp<[[VP8:%[0-9]+]]> = extract-sub-vector-for-part vp<[[VP7]]>, ir<0>
; AFTER-SCALE-NEXT:      vp<[[VP9:%[0-9]+]]> = SCALAR-STEPS vp<[[VP6]]>, ir<1>, vp<[[VP0]]>
; AFTER-SCALE-NEXT:      CLONE ir<%ptr> = getelementptr inbounds ir<%x>, vp<[[VP9]]>
; AFTER-SCALE-NEXT:      vp<[[VP10:%[0-9]+]]> = vector-pointer inbounds ir<%ptr>, ir<1>
; AFTER-SCALE-NEXT:      WIDEN ir<%ld> = load x2 vp<[[VP10]]>, vp<[[VP7]]>
; AFTER-SCALE-NEXT:      EMIT vp<[[VP11:%[0-9]+]]> = extract-sub-vector-for-part ir<%ld>, ir<0>
; AFTER-SCALE-NEXT:      WIDEN ir<%add> = add vp<[[VP11]]>, ir<1>
; AFTER-SCALE-NEXT:      vp<[[VP12:%[0-9]+]]> = vector-pointer inbounds ir<%ptr>, ir<1>
; AFTER-SCALE-NEXT:      EMIT vp<[[VP13:%[0-9]+]]> = insert-sub-vector-for-part ir<%add>
; AFTER-SCALE-NEXT:      WIDEN store x2 vp<[[VP12]]>, vp<[[VP13]]>, vp<[[VP7]]>
; AFTER-SCALE-NEXT:      EMIT vp<%index.next> = add vp<[[VP6]]>, vp<[[VP1]]>
; AFTER-SCALE-NEXT:      EMIT vp<[[VP14:%[0-9]+]]> = VF * Part + vp<%index.next>, vp<[[VP0]]>
; AFTER-SCALE-NEXT:      EMIT vp<%active.lane.mask.next> = active lane mask vp<[[VP14]]>, vp<[[VP4]]>, ir<2>, ir<8>
; AFTER-SCALE-NEXT:      EMIT vp<[[VP15:%[0-9]+]]> = not vp<%active.lane.mask.next>
; AFTER-SCALE-NEXT:      EMIT branch-on-cond vp<[[VP15]]>
; AFTER-SCALE-NEXT:    No successors
; AFTER-SCALE-NEXT:  }
; AFTER-SCALE-NEXT:  Successor(s): middle.block
; AFTER-SCALE-EMPTY:
; AFTER-SCALE-NEXT:  middle.block:
;
; AFTER-UNROLL-LABEL: VPlan for loop in 'masked_i64_load_store'
; AFTER-UNROLL:  VPlan 'Initial VPlan for VF={vscale x 4},UF={2}' {
; AFTER-UNROLL-NEXT:  Live-in vp<[[VP0:%[0-9]+]]> = VF
; AFTER-UNROLL-NEXT:  Live-in vp<[[VP1:%[0-9]+]]> = VF * UF
; AFTER-UNROLL-NEXT:  vp<[[VP4:%[0-9]+]]> = original trip-count
; AFTER-UNROLL-EMPTY:
; AFTER-UNROLL-NEXT:  ir-bb<entry>:
; AFTER-UNROLL-NEXT:    EMIT vp<[[VP4]]> = EXPAND SCEV (1 umax %n)
; AFTER-UNROLL-NEXT:    EMIT branch-on-cond ir<false>
; AFTER-UNROLL-NEXT:  Successor(s): scalar.ph, vector.ph
; AFTER-UNROLL-EMPTY:
; AFTER-UNROLL-NEXT:  vector.ph:
; AFTER-UNROLL-NEXT:    EMIT vp<%active.lane.mask.entry> = active lane mask ir<0>, vp<[[VP4]]>, ir<2>, ir<8>
; AFTER-UNROLL-NEXT:  Successor(s): vector loop
; AFTER-UNROLL-EMPTY:
; AFTER-UNROLL-NEXT:  <x1> vector loop: {
; AFTER-UNROLL-NEXT:  vp<[[VP6:%[0-9]+]]> = CANONICAL-IV
; AFTER-UNROLL-EMPTY:
; AFTER-UNROLL-NEXT:    vector.body:
; AFTER-UNROLL-NEXT:      ACTIVE-LANE-MASK-PHI vp<[[VP7:%[0-9]+]]> = phi vp<%active.lane.mask.entry>, vp<%active.lane.mask.next>
; AFTER-UNROLL-NEXT:      vp<[[VP8:%[0-9]+]]> = SCALAR-STEPS vp<[[VP6]]>, ir<1>, vp<[[VP0]]>
; AFTER-UNROLL-NEXT:      CLONE ir<%ptr> = getelementptr inbounds ir<%x>, vp<[[VP8]]>
; AFTER-UNROLL-NEXT:      vp<[[VP9:%[0-9]+]]> = vector-pointer inbounds ir<%ptr>, ir<1>
; AFTER-UNROLL-NEXT:      WIDEN ir<%ld> = load x2 vp<[[VP9]]>, vp<[[VP7]]>
; AFTER-UNROLL-NEXT:      EMIT vp<[[VP10:%[0-9]+]]> = extract-sub-vector-for-part ir<%ld>, ir<0>
; AFTER-UNROLL-NEXT:      EMIT vp<[[VP11:%[0-9]+]]> = extract-sub-vector-for-part ir<%ld>, ir<1>
; AFTER-UNROLL-NEXT:      WIDEN ir<%add> = add vp<[[VP10]]>, ir<1>
; AFTER-UNROLL-NEXT:      WIDEN ir<%add>.1 = add vp<[[VP11]]>, ir<1>
; AFTER-UNROLL-NEXT:      vp<[[VP12:%[0-9]+]]> = vector-pointer inbounds ir<%ptr>, ir<1>
; AFTER-UNROLL-NEXT:      EMIT vp<[[VP13:%[0-9]+]]> = insert-sub-vector-for-part ir<%add>, ir<%add>.1
; AFTER-UNROLL-NEXT:      WIDEN store x2 vp<[[VP12]]>, vp<[[VP13]]>, vp<[[VP7]]>
; AFTER-UNROLL-NEXT:      EMIT vp<%index.next> = add vp<[[VP6]]>, vp<[[VP1]]>
; AFTER-UNROLL-NEXT:      EMIT vp<%active.lane.mask.next> = active lane mask vp<%index.next>, vp<[[VP4]]>, ir<2>, ir<8>
; AFTER-UNROLL-NEXT:      EMIT vp<[[VP14:%[0-9]+]]> = not vp<%active.lane.mask.next>
; AFTER-UNROLL-NEXT:      EMIT branch-on-cond vp<[[VP14]]>
; AFTER-UNROLL-NEXT:    No successors
; AFTER-UNROLL-NEXT:  }
; AFTER-UNROLL-NEXT:  Successor(s): middle.block
; AFTER-UNROLL-EMPTY:
; AFTER-UNROLL-NEXT:  middle.block:
;
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %next, %loop ]
  %ptr = getelementptr inbounds i64, ptr %x, i64 %iv
  %ld = load i64, ptr %ptr, align 8
  %add = add i64 %ld, 1
  store i64 %add, ptr %ptr, align 8
  %next = add nuw i64 %iv, 1
  %cmp = icmp ult i64 %next, %n
  br i1 %cmp, label %loop, label %exit, !llvm.loop !0

exit:
  ret void
}

!0 = distinct !{!0, !1, !2, !3}
!1 = !{!"llvm.loop.vectorize.enable", i1 true}
!2 = !{!"llvm.loop.vectorize.width", i32 4}
!3 = !{!"llvm.loop.vectorize.scalable.enable", i1 true}
